<?php


?>

<p><i class="fa fa-arrows"></i>  Register on Flutterwave  <a href="https://www.flutterwavedev.com/signup/" target="_blank" style="color: red;">https://www.flutterwavedev.com/signup/</a></p>
<br>
<p><img alt="Flutterwave Registration page" src="<?php  echo $this->basepath("img/flutterLogin.png")?>" style="width: 100%; display: block;"></p>

<br><br>
<p> <i class="fa fa-arrows"></i>  Click on the <strong>Setting >> Go Live </strong>, tabs fill the required information, and upload the required files </p>

<br>
<p><img alt="Flutterwave settings page" src="<?php  echo $this->basepath("img/settings2.png")?>" style="width: 100%; display: block;"></p>

<p> <i class="fa fa-arrows"></i> Copy the  <strong>Live Merchant Key and Live Api Key </strong>, respectively to your IMAPP acount  </p>

<br>
<p><img alt="Flutterwave Keys" src="<?php  echo $this->basepath("img/live.png")?>" style="width: 100%; display: block;">
<img alt="IMAPP fluterwave account" src="<?php  echo $this->basepath("img/imappflutter.png")?>" style="width: 100%; display: block;">
</p>
