<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BrokersTool\Module' => __DIR__ . '/Module.php',
    'BrokersTool\Controller\BrokerToolController' => __DIR__ . '/src/BrokersTool/Controller/BrokerToolController.php',
    'BrokersToolTest\Framework\TestCase' => __DIR__ . '/tests/BrokersTool/Framework/TestCase.php',
    'BrokersToolTest\SampleTest' => __DIR__ . '/tests/BrokersTool/SampleTest.php'
);
