<?php


?>

<div class="panel panel-default curriculum paper-shadow" data-z="0.5">
            <div class="panel-heading panel-heading-gray" data-toggle="collapse" data-target="#curriculum-3">
              <div class="media">
                <div class="media-left">
                  <span class="icon-block half img-circle bg-green-300 text-white"><i class="fa fa-comments-o"></i></span>
                </div>
                <div class="media-body">
                  <h4 class="text-headline">Offer Comments and Discussions</h4>
                  <p>Access all comments on the this offer</p>
                </div>
              </div>
              <span class="collapse-status collapse-open">Open</span>
              <span class="collapse-status collapse-close">Close</span>
            </div>
            <div class="list-group collapse" id="curriculum-3">
              <h5 class="text-subhead-2 text-light">Comments</h5>

          <form>
            <div class="form-group input-group">
              <input type="text" class="form-control" placeholder="Your comment ..">
              <span class="input-group-btn">
            <button class="btn btn-primary" type="button"><i class="fa fa-plus"></i></button>
        </span>
            </div>
          </form>

          <div class="media s-container">
            <a class="media-left" href="">
              <img class="media-object" src="images/people/50/guy-2.jpg" alt="people" />
            </a>
            <div class="media-body">
              <div class="panel panel-default">
                <div class="panel-body">
                  <small class="text-grey-400 pull-right">2 minutes ago</small>
                  <h5 class="media-heading margin-v-5">Andrew B.</h5>
                  <p class="margin-none">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias asperiores doloremque nulla omnis perspiciatis repudiandae sit suscipit temporibus vitae voluptates?</p>
                </div>
              </div>
            </div>
          </div>
          <div class="comment-reply">
            <div class="media s-container">
              <a class="media-left" href="">
                <img class="media-object" src="images/people/50/woman-5.jpg" alt="people" />
              </a>
              <div class="media-body">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <small class="text-grey-400 pull-right">2 hours ago</small>
                    <h5 class="media-heading margin-v-5">Jane D.</h5>
                    <p class="margin-none">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet facere laborum nam numquam quia tempora.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
              <div class="list-group-item media" data-target="website-take-course.html">
                <div class="media-left">
                  <div class="text-crt">2.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> The MVC architectural pattern
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">25:01 min</div>
                </div>
              </div>
              <div class="list-group-item media" data-target="website-take-course.html">
                <div class="media-left">
                  <div class="text-crt">3.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> Database Models
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">12:10 min</div>
                </div>
              </div>
              <div class="list-group-item media" data-target="website-take-course.html">
                <div class="media-left">
                  <div class="text-crt">4.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> Database Access
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">1:25 min</div>
                </div>
              </div>
              <div class="list-group-item media" data-target="website-take-course.html">
                <div class="media-left">
                  <div class="text-crt">5.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> Eloquent Basics
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">22:30 min</div>
                </div>
              </div>
              <div class="list-group-item media" data-target="website-take-quiz.html">
                <div class="media-left">
                  <div class="text-crt">6.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> Take Quiz
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">10:00 min</div>
                </div>
              </div>
            </div>
          </div>