<?php


?>

<div class="panel panel-default paper-shadow" data-z="0.5"
			data-hover-z="1" data-animated>
			<div class="panel-heading">
				<div class="media">
			<div class="media-left">
				<span class="icon-block img-circle bg-red-300 half text-white"><i
					class="fa fa-dollar"></i></span>
			</div>
			<div class="media-body">
				<h4 class="text-headline">1234</h4>
				
			</div>
			<div class="media-right">
				Estimated Premium
			</div>
		</div>
			</div>
			
			<hr class="margin-none" />
			<div class="panel-body text-center">

				<p>
					<a class="btn btn-success btn-lg paper-shadow relative" data-z="1"
						data-hover-z="2" data-animated
						href="<?php // echo $this->url("cus_pack/default", array("action"=>"preacquire", "id"=>$package[0]->getPackages()->getId()))?>">MAKE PAYMENT</a>
				</p>
				<!--               <p class="text-body-2">or <a href="#">buy course for $1</a></p> -->
			</div>
			
		</div>