<?php

?>

<div class="panel panel-default curriculum paper-shadow" data-z="0.5">
            <div class="panel-heading panel-heading-gray" data-toggle="collapse" data-target="#curriculum-2">
              <div class="media">
                <div class="media-left">
                  <span class="icon-block half img-circle bg-orange-300 text-white"><i class="fa fa-files-o"></i></span>
                </div>
                <div class="media-body">
                  <h4 class="text-headline">Property and Documents</h4>
                  <p>All documents and properties associated with this offer</p>
                  <a href="#" class="btn btn-primary">Add Property</a> &nbsp;&nbsp; <a href="" class="btn btn-success">Upload Documents</a>
                </div>
              </div>
              <span class="collapse-status collapse-open">Open</span>
              <span class="collapse-status collapse-close">Close</span>
            </div>
            <div class="list-group collapse" id="curriculum-2">
              <div class="list-group-item media" data-target="website-take-course.html">
                <div class="media-left">
                  <div class="text-crt">1.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> Installation
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">2:03 min</div>
                </div>
              </div>
              <div class="list-group-item media" data-target="website-take-course.html">
                <div class="media-left">
                  <div class="text-crt">2.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> The MVC architectural pattern
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">25:01 min</div>
                </div>
              </div>
              <div class="list-group-item media" data-target="website-take-course.html">
                <div class="media-left">
                  <div class="text-crt">3.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> Database Models
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">12:10 min</div>
                </div>
              </div>
              <div class="list-group-item media" data-target="website-take-course.html">
                <div class="media-left">
                  <div class="text-crt">4.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> Database Access
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">1:25 min</div>
                </div>
              </div>
              <div class="list-group-item media" data-target="website-take-course.html">
                <div class="media-left">
                  <div class="text-crt">5.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> Eloquent Basics
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">22:30 min</div>
                </div>
              </div>
              <div class="list-group-item media" data-target="website-take-quiz.html">
                <div class="media-left">
                  <div class="text-crt">6.</div>
                </div>
                <div class="media-body">
                  <i class="fa fa-fw fa-circle text-grey-200"></i> Take Quiz
                </div>
                <div class="media-right">
                  <div class="width-100 text-right text-caption">10:00 min</div>
                </div>
              </div>
            </div>
          </div>