<?php
?>
<img src="<?php  echo $this->basepath()?>/images/logo.dark.png" alt=""
	height="60" id="yui_3_16_0_ym19_1_1480501585433_7557" />
<table cellpadding="8" cellspacing="0" border="0"
	id="yui_3_16_0_ym19_1_1480501585433_7507">
	<tbody id="yui_3_16_0_ym19_1_1480501585433_7506">
		<tr id="yui_3_16_0_ym19_1_1480501585433_7505">
			<td valign="top" id="yui_3_16_0_ym19_1_1480501585433_7504"><table
					cellpadding="0" cellspacing="0" border="0" align="center"
					id="yui_3_16_0_ym19_1_1480501585433_7515">
					<tbody id="yui_3_16_0_ym19_1_1480501585433_7514">
						<tr id="yui_3_16_0_ym19_1_1480501585433_7513">
							<td id="yui_3_16_0_ym19_1_1480501585433_7512"><table
									cellpadding="0" cellspacing="0" border="0" align="center"
									id="yui_3_16_0_ym19_1_1480501585433_7511">
									<tbody id="yui_3_16_0_ym19_1_1480501585433_7510">
										<tr id="yui_3_16_0_ym19_1_1480501585433_7509">
											<td height="16" colspan="3"
												id="yui_3_16_0_ym19_1_1480501585433_7508"></td>
										</tr>
										<tr id="yui_3_16_0_ym19_1_1480501585433_7517">
											<td width="36"></td>
											<td width="454" valign="top" align="left"
												id="yui_3_16_0_ym19_1_1480501585433_7516"><br />
                    Hello <?php echo $fullname?><br /> <br />
                   <?php  echo $message?>
                    <div align="center"
													id="yui_3_16_0_ym19_1_1480501585433_7519"></div> <br />
												Thank You.<br /> <br /> Administrator<br /> <strong>IMAPP</strong>
												<hr id="yui_3_16_0_ym19_1_1480501585433_7558" />
												<p id="yui_3_16_0_ym19_1_1480501585433_7575">
													THIS IS AN AUTOMATED RESPONSE.<br /> THIS IS AN UNMONITORED
													EMAIL ADDRESS. DO NOT REPLY THIS MAIL.
												</p></td>
											<td width="36" id="yui_3_16_0_ym19_1_1480501585433_7566"></td>
										</tr>
										<tr id="yui_3_16_0_ym19_1_1480501585433_7573">
											<td height="36" colspan="3"
												id="yui_3_16_0_ym19_1_1480501585433_7572"></td>
										</tr>
									</tbody>
								</table></td>
						</tr>
					</tbody>
				</table>
				<table cellpadding="0" cellspacing="0" border="0" align="center">
					<tbody>
						<tr>
							<td height="10"></td>
						</tr>
						<tr>
							<td><table cellpadding="0" cellspacing="0" border="0"
									align="center">
									<tbody>
										<tr valign="top">
											<td colspan="2" align="right">©<?php echo date('Y')?> IMAPP. All rights reserved.</td>
										</tr>
									</tbody>
								</table></td>
						</tr>
					</tbody>
				</table></td>
		</tr>
	</tbody>
</table>
