<hr>
<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('buildingType'))?> <strong style="color: red">*</strong>	

		<div class="col-md-7 col-sm-7 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('buildingType'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('buildingType'));?>
					</div>
</div>



<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('noOfRooms'))?><strong style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('noOfRooms'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('noOfRooms'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('wallType'))?><strong style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('wallType'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('wallType'));?>
					</div>
</div>
<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('roofType'))?><strong style="color: red">*</strong>	
							

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('roofType'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('roofType'));?>
					</div>
</div>



<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('houseDescription'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('houseDescription'))?>
							
						</div>
	<i class="fa fa-info" data-toggle='tooltip' data-placement='top'
		title='This includes, but not limited to, building color , year it was built, estimated number of rooms '></i>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('houseDescription'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('houseAdd1'))?><strong style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('houseAdd1'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('houseAdd1'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('houseAdd2'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('houseAdd2'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('houseAdd2'));?>
					</div>
</div>



<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('country'))?><strong style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('country'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('country'));?>
					</div>
</div>


<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('state'))?><strong style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('state'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('state'));?>
					</div>
</div>


<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('city'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('city'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('city'));?>
					</div>
</div>






<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('floorArea'))?>	
							

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('floorArea'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('floorArea'));?>
					</div>
</div>





<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('isIntruderAlarmSystem'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('isIntruderAlarmSystem'))?>
							
						</div>
<!-- 	<i class="fa fa-info" data-toggle='tooltip' data-placement='top' -->
<!-- 		title='Check box if true'></i> -->
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('isIntruderAlarmSystem'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('isFireAlarmSystem'))?>

		<div class="col-md-6 col-sm-6 col-xs-9">
						<?php echo $this->formElement($objectBuilding->get('isFireAlarmSystem'))?>
							
						</div>
<!-- 	<i class="fa fa-info" data-toggle='tooltip' data-placement='top' -->
<!-- 		title='Check box if true'></i> -->
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('isFireAlarmSystem'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBuilding->get('isFireProtectionSystem'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBuilding->get('isFireProtectionSystem'))?>
							
						</div>
	
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBuilding->get('isFireProtectionSystem'));?>
					</div>
</div>
<?php 

//echo $this->headScript()->appendFile($this->basePath('js/jquery.min.js'));?>

<script type="text/javascript">
<!--

//-->

$(document).ready(function(){
	
})
</script>
