
	<div class="ln_solid"></div>
	<hr>
	<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusinessEquipment->get('equipmentCategory'))?><strong style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBusinessEquipment->get('equipmentCategory'))?>
							
						</div>
		<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBusinessEquipment->get('equipmentCategory'));?>
					</div>
	</div>
	
	<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusinessEquipment->get('make'))?><strong style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBusinessEquipment->get('make'))?>
							
						</div>
		<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectBusinessEquipment->get('make'));?>
					</div>
	</div>
	
	<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusinessEquipment->get('purchaseDate'))?><strong style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBusinessEquipment->get('purchaseDate'))?>
							
						</div>
		<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectBusinessEquipment->get('purchaseDate'));?>
					</div>
	</div>
	
	<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusinessEquipment->get('purchaseValue'))?><strong style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBusinessEquipment->get('purchaseValue'))?>
							
						</div>
		<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectBusinessEquipment->get('purchaseValue'));?>
					</div>
	</div>


<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusinessEquipment->get('equipmentDesc'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBusinessEquipment->get('equipmentDesc'))?>
							
						</div>
		<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBusinessEquipment->get('equipmentDesc'));?>
					</div>
	</div>

	<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusinessEquipment->get('itemNo'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBusinessEquipment->get('itemNo'))?>
							
						</div>
		<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBusinessEquipment->get('itemNo'));?>
					</div>
	</div>

	

	<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusinessEquipment->get('regNo'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
			
						<?php echo $this->formElement($objectBusinessEquipment->get('regNo'))?>
						
		</div>
		<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectBusinessEquipment->get('regNo'));?>
					</div>
	</div>

	<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusinessEquipment->get('yearManufacture'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectBusinessEquipment->get('yearManufacture'))?>
							
						</div>
		<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectBusinessEquipment->get('yearManufacture'));?>
					</div>
	</div>

	



