

<hr>
<div class="item form-group">
						
							<?php  echo $this->formLabel($objectTravel->get('title'))?><strong
		style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectTravel->get('title'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectTravel->get('title'));?>
					</div>
</div>
<div class="item form-group">
						
							<?php  echo $this->formLabel($objectTravel->get('passportName'))?><strong
		style="color: red">*</strong><i class="fa fa-info"
		data-toggle='tooltip' data-placement='top'
		title='As it appears on the document'></i>

	<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectTravel->get('passportName'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectTravel->get('passportName'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectTravel->get('passportNumber'))?><strong
		style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectTravel->get('passportNumber'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectTravel->get('passportNumber'));?>
					</div>
</div>


<div class="item form-group">
						
							<?php  echo $this->formLabel($objectTravel->get('passportDateCreated'))?><strong
		style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectTravel->get('passportDateCreated'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectTravel->get('passportDateCreated'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectTravel->get('passportExpiryDate'))?><strong
		style="color: red">*</strong>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectTravel->get('passportExpiryDate'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectTravel->get('passportExpiryDate'));?>
					</div>
</div>



<div class="item form-group">
	
						
							<?php  echo $this->formLabel($objectTravel->get('sex'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectTravel->get('sex'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectTravel->get('sex'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectTravel->get('age'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
			
						<?php echo $this->formElement($objectTravel->get('age'))?>
						
		</div>
	<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectTravel->get('age'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php // echo $this->formLabel($objectTravel->get('mobileNumber'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php // echo $this->formElement($objectTravel->get('mobileNumber'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php // echo $this->formElementErrors($objectTravel->get('mobileNumber'));?>
					</div>
</div>





<div class="item form-group">
						
							<?php  echo $this->formLabel($objectTravel->get('placeOfIssue'))?>

		<div class="col-md-6 col-sm-6 col-xs-12">
						<?php echo $this->formElement($objectTravel->get('placeOfIssue'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo $this->formElementErrors($objectTravel->get('placeOfIssue'));?>
					</div>
</div>


