<hr>
<div class="item form-group">
						
							<?php  echo $this->formLabel($objectNonBusiness->get('equipmentCategory'))?> 	

		<div class="col-md-8 col-sm-8 col-xs-12">
						<?php echo $this->formElement($objectNonBusiness->get('equipmentCategory'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectNonBusiness->get('equipmentCategory'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectNonBusiness->get('equipmentName'))?> 	

		<div class="col-md-8 col-sm-8 col-xs-12">
						<?php echo $this->formElement($objectNonBusiness->get('equipmentName'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectNonBusiness->get('equipmentName'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectNonBusiness->get('equipmentDesc'))?> 	

		<div class="col-md-8 col-sm-8 col-xs-12">
						<?php echo $this->formElement($objectNonBusiness->get('equipmentDesc'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectNonBusiness->get('equipmentDesc'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectNonBusiness->get('equipmentUid'))?> 	

		<div class="col-md-8 col-sm-8 col-xs-12">
						<?php echo $this->formElement($objectNonBusiness->get('equipmentUid'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectNonBusiness->get('equipmentUid'));?>
					</div>
</div>