<hr>
<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusiness->get('businessName'))?> 	<strong style="color: red">*</strong>

		<div class="col-md-8 col-sm-8 col-xs-12">
						<?php echo $this->formElement($objectBusiness->get('businessName'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBusiness->get('businessName'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusiness->get('businessCategory'))?> <strong style="color: red">*</strong>	

		<div class="col-md-8 col-sm-8 col-xs-12">
						<?php echo $this->formElement($objectBusiness->get('businessCategory'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBusiness->get('businessCategory'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusiness->get('businessRegNo'))?> 	<strong style="color: red">*</strong>

		<div class="col-md-8 col-sm-8 col-xs-12">
						<?php echo $this->formElement($objectBusiness->get('businessRegNo'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBusiness->get('businessRegNo'));?>
					</div>
</div>

<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusiness->get('businessDesc'))?> 	

		<div class="col-md-8 col-sm-8 col-xs-12">
						<?php echo $this->formElement($objectBusiness->get('businessDesc'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBusiness->get('businessDesc'));?>
					</div>
</div>





<div class="item form-group">
						
							<?php  echo $this->formLabel($objectBusiness->get('businessAddress'))?> 	

		<div class="col-md-8 col-sm-8 col-xs-12">
						<?php echo $this->formElement($objectBusiness->get('businessAddress'))?>
							
						</div>
	<div style="font-size: 9px; color: red;">
						<?php echo  $this->formElementErrors($objectBusiness->get('businessAddress'));?>
					</div>
</div>

