
<?php
echo $this->headtitle("Buy SMS");
$smsForm->prepare();
?>
<div id="wasabi_modal"></div>
<div class="row" ng-app="SmsModule">
	<div ng-controller="buySms">

		<div class='col-md-6 col-sm-6 col-xs-12'>
			<div class="x_panel">
				<div class="x_title">
					<h2>Buy SMS</h2>
					<ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
						<li class="dropdown"><a href="#" class="dropdown-toggle"
							data-toggle="dropdown" role="button" aria-expanded="false"><i
								class="fa fa-wrench"></i></a></li>

					</ul>
					<div class="clearfix"></div>
				</div>
	<?php echo $this->form()->openTag($smsForm);?>
	<?php echo $this->partial("sms-smsunit-fielset-snipet", array("smsunit"=>$smsForm->get("smsUnitFieldset")))?>
	 <?php // echo $this->partial("transaction_user_card_payment_snipet", array("payForm"=>$smsForm->get("card_payment")))?>
	 
	 <div class="form-group">
									
							<?php  echo $this->formrow($smsForm->get('submit'))?>
							</div>
	 <?php echo $this->form()->closeTag()?>
	 </div>
			
		</div>

		<div class='col-md-6 col-sm-6 col-xs-12'>
			<div class="x_panel">
				<div class="x_title">
					<h2>Available SMS</h2>

					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<div class="row">
						<div
							class="animated flipInY col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="tile-stats">

								<div class="count" ng-model="availableSMS"> <?php
        echo $availableSms?> SMS</div>


								<div class="clearfix"></div>


							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="x_panel">
				<div class="x_title">
					<h2>Top Up SMS</h2>

					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<div class="row">
						<div
							class="animated flipInY col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="tile-stats">

								<div class="count">{{topup}} SMS</div>


								<div class="clearfix"></div>


							</div>
						</div>
					</div>
				</div>
			</div>


			<div class="x_panel">
				<div class="x_title">
					<h2>Amount Payable</h2>

					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<div class="row">
						<div
							class="animated flipInY col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="tile-stats">

								<div class="count">&#x20A6 {{sumPayable}}</div>


								<div class="clearfix"></div>


							</div>
						</div>
					</div>
				</div>
			</div>




		</div>
	</div>
</div>
<?php
echo $this->headScript()
//     ->appendFile($this->basePath('js/jquery.mask.min.js'))
    ->appendFile($this->basePath('angular/controllers/SmsController.js'));
?>



