<?php

namespace DoctrineORMModule\Proxy\__CG__\Settings\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Packages extends \Settings\Entity\Packages implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'id', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'packageName', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'packageCategory', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'packageDesc', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'maxEmployee', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isDesktop', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isApi', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isCustomerPolicyManage', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isManualProposal', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isPaymentMapping', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isReporting', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isEmailSupport', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isAutoProposal', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isPaymentImport', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'customerImport', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isBIAnalytics', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'supportService', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'term', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isMobileApp', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'price', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'sms'];
        }

        return ['__isInitialized__', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'id', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'packageName', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'packageCategory', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'packageDesc', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'maxEmployee', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isDesktop', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isApi', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isCustomerPolicyManage', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isManualProposal', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isPaymentMapping', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isReporting', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isEmailSupport', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isAutoProposal', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isPaymentImport', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'customerImport', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isBIAnalytics', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'supportService', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'term', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'isMobileApp', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'price', '' . "\0" . 'Settings\\Entity\\Packages' . "\0" . 'sms'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Packages $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackageName($packageName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackageName', [$packageName]);

        return parent::setPackageName($packageName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageName', []);

        return parent::getPackageName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackageCat($cat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackageCat', [$cat]);

        return parent::setPackageCat($cat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageCat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageCat', []);

        return parent::getPackageCat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackageDesc($packageDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackageDesc', [$packageDesc]);

        return parent::setPackageDesc($packageDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageDesc', []);

        return parent::getPackageDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxEmployee($maxEmployee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxEmployee', [$maxEmployee]);

        return parent::setMaxEmployee($maxEmployee);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxEmployee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxEmployee', []);

        return parent::getMaxEmployee();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDesktop($isDesktop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDesktop', [$isDesktop]);

        return parent::setIsDesktop($isDesktop);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDesktop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDesktop', []);

        return parent::getIsDesktop();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsApi($isApi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsApi', [$isApi]);

        return parent::setIsApi($isApi);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsApi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsApi', []);

        return parent::getIsApi();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerPolicyManage($po)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerPolicyManage', [$po]);

        return parent::setCustomerPolicyManage($po);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerPolicyManage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerPolicyManage', []);

        return parent::getCustomerPolicyManage();
    }

    /**
     * {@inheritDoc}
     */
    public function setManualProposal($mp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManualProposal', [$mp]);

        return parent::setManualProposal($mp);
    }

    /**
     * {@inheritDoc}
     */
    public function getManualProposal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManualProposal', []);

        return parent::getManualProposal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMapping($pm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMapping', [$pm]);

        return parent::setPaymentMapping($pm);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMapping()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMapping', []);

        return parent::getPaymentMapping();
    }

    /**
     * {@inheritDoc}
     */
    public function setReporting($report)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReporting', [$report]);

        return parent::setReporting($report);
    }

    /**
     * {@inheritDoc}
     */
    public function getReporting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReporting', []);

        return parent::getReporting();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailSupport($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailSupport', [$email]);

        return parent::setEmailSupport($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailSupport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailSupport', []);

        return parent::getEmailSupport();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoProposal($pro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutoProposal', [$pro]);

        return parent::setAutoProposal($pro);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutoProposal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutoProposal', []);

        return parent::getAutoProposal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerImport($im)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerImport', [$im]);

        return parent::setCustomerImport($im);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerImport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerImport', []);

        return parent::getCustomerImport();
    }

    /**
     * {@inheritDoc}
     */
    public function setBIAnalytics($bi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBIAnalytics', [$bi]);

        return parent::setBIAnalytics($bi);
    }

    /**
     * {@inheritDoc}
     */
    public function getBIAnalytics()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBIAnalytics', []);

        return parent::getBIAnalytics();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupportService($supportService)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupportService', [$supportService]);

        return parent::setSupportService($supportService);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupportService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupportService', []);

        return parent::getSupportService();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerm(\Settings\Entity\Terms $term = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerm', [$term]);

        return parent::setTerm($term);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerm', []);

        return parent::getTerm();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsMobileApp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsMobileApp', []);

        return parent::getIsMobileApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMobileApp($isMo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMobileApp', [$isMo]);

        return parent::setIsMobileApp($isMo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function setSms($sms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSms', [$sms]);

        return parent::setSms($sms);
    }

    /**
     * {@inheritDoc}
     */
    public function getSms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSms', []);

        return parent::getSms();
    }

}
