<?php

namespace DoctrineORMModule\Proxy\__CG__\Offer\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offer extends \Offer\Entity\Offer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'id', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'offerName', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'offerCode', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'createdOn', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'updatedOn', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'offerServiceType', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isRenewable', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isHidden', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isPolicized', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'idPreferdInsurer', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'recommendedInsurer', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isRecommendedInsurer', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'idInsuranceBroker', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'offerStatuses', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'customer', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'object', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'idDoc', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'offerSpecificService', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isDeclared', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'value', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'currency', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'valueType', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'coverNote', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'invoice', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'duration', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'messages', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'coverDuration', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'termedDuration', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'manualPremium', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isManualPremium'];
        }

        return ['__isInitialized__', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'id', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'offerName', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'offerCode', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'createdOn', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'updatedOn', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'offerServiceType', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isRenewable', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isHidden', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isPolicized', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'idPreferdInsurer', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'recommendedInsurer', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isRecommendedInsurer', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'idInsuranceBroker', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'offerStatuses', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'customer', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'object', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'idDoc', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'offerSpecificService', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isDeclared', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'value', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'currency', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'valueType', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'coverNote', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'invoice', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'duration', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'messages', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'coverDuration', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'termedDuration', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'manualPremium', '' . "\0" . 'Offer\\Entity\\Offer' . "\0" . 'isManualPremium'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Offer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferName', []);

        return parent::getOfferName();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferName($offer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferName', [$offer]);

        return parent::setOfferName($offer);
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferCode($offerCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferCode', [$offerCode]);

        return parent::setOfferCode($offerCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferCode', []);

        return parent::getOfferCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer($customer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', [$customer]);

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn($updatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferServiceType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferServiceType', []);

        return parent::getOfferServiceType();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferServiceType($ost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferServiceType', [$ost]);

        return parent::setOfferServiceType($ost);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRenewable($isRenewable = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRenewable', [$isRenewable]);

        return parent::setIsRenewable($isRenewable);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRenewable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRenewable', []);

        return parent::getIsRenewable();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsHidden($isHidden = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsHidden', [$isHidden]);

        return parent::setIsHidden($isHidden);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsHidden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsHidden', []);

        return parent::getIsHidden();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPolicized($isPolicized = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPolicized', [$isPolicized]);

        return parent::setIsPolicized($isPolicized);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPolicized()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPolicized', []);

        return parent::getIsPolicized();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPreferdInsurer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPreferdInsurer', []);

        return parent::getIdPreferdInsurer();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPreferdInsurer(\Settings\Entity\Insurer $idPreferdInsurer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPreferdInsurer', [$idPreferdInsurer]);

        return parent::setIdPreferdInsurer($idPreferdInsurer);
    }

    /**
     * {@inheritDoc}
     */
    public function setRecommendedInsurer($ins)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecommendedInsurer', [$ins]);

        return parent::setRecommendedInsurer($ins);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecommendedInsurer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecommendedInsurer', []);

        return parent::getRecommendedInsurer();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRecommendedInsurer($ins)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRecommendedInsurer', [$ins]);

        return parent::setIsRecommendedInsurer($ins);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRecommendedInsurer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRecommendedInsurer', []);

        return parent::getIsRecommendedInsurer();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdInsuranceBroker(\Users\Entity\InsuranceBrokerRegistered $idInsuranceBroker = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdInsuranceBroker', [$idInsuranceBroker]);

        return parent::setIdInsuranceBroker($idInsuranceBroker);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdInsuranceBroker()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdInsuranceBroker', []);

        return parent::getIdInsuranceBroker();
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferStatuses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferStatuses', []);

        return parent::getOfferStatuses();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferStatuses(\Offer\Entity\OfferStatus $offerStatuses = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferStatuses', [$offerStatuses]);

        return parent::setOfferStatuses($offerStatuses);
    }

    /**
     * {@inheritDoc}
     */
    public function getValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', []);

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setValue($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValue', [$val]);

        return parent::setValue($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getValueType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueType', []);

        return parent::getValueType();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($cur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$cur]);

        return parent::setCurrency($cur);
    }

    /**
     * {@inheritDoc}
     */
    public function setValueType($val)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValueType', [$val]);

        return parent::setValueType($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getObject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObject', []);

        return parent::getObject();
    }

    /**
     * {@inheritDoc}
     */
    public function addObject(\Object\Entity\Object $object)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObject', [$object]);

        return parent::addObject($object);
    }

    /**
     * {@inheritDoc}
     */
    public function removeObject(\Object\Entity\Object $object)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeObject', [$object]);

        return parent::removeObject($object);
    }

    /**
     * {@inheritDoc}
     */
    public function addIdDoc(\GeneralServicer\Entity\Document $idDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdDoc', [$idDoc]);

        return parent::addIdDoc($idDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdDoc(\GeneralServicer\Entity\Document $idDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdDoc', [$idDoc]);

        return parent::removeIdDoc($idDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDoc', []);

        return parent::getIdDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferSpecificService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferSpecificService', []);

        return parent::getOfferSpecificService();
    }

    /**
     * {@inheritDoc}
     */
    public function setOfferSpecificService($service)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOfferSpecificService', [$service]);

        return parent::setOfferSpecificService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotorOfferData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotorOfferData', []);

        return parent::getMotorOfferData();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotorOfferData($motor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotorOfferData', [$motor]);

        return parent::setMotorOfferData($motor);
    }

    /**
     * {@inheritDoc}
     */
    public function getOfferStatusWord()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOfferStatusWord', []);

        return parent::getOfferStatusWord();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoice', []);

        return parent::getInvoice();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoice($invo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoice', [$invo]);

        return parent::setInvoice($invo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoverNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoverNote', []);

        return parent::getCoverNote();
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', []);

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration($dur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', [$dur]);

        return parent::setDuration($dur);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessages', []);

        return parent::getMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoverDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoverDuration', []);

        return parent::getCoverDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoverDuration($dur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoverDuration', [$dur]);

        return parent::setCoverDuration($dur);
    }

    /**
     * {@inheritDoc}
     */
    public function getTermedDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermedDuration', []);

        return parent::getTermedDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setTermedDuration($term)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTermedDuration', [$term]);

        return parent::setTermedDuration($term);
    }

    /**
     * {@inheritDoc}
     */
    public function getManualPremium()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManualPremium', []);

        return parent::getManualPremium();
    }

    /**
     * {@inheritDoc}
     */
    public function setManualPremium($set)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManualPremium', [$set]);

        return parent::setManualPremium($set);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsManualPremium()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsManualPremium', []);

        return parent::getIsManualPremium();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsManualPremium($man)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsManualPremium', [$man]);

        return parent::setIsManualPremium($man);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractAllRisk()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractAllRisk', []);

        return parent::getContractAllRisk();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractAllRisk($risk)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractAllRisk', [$risk]);

        return parent::setContractAllRisk($risk);
    }

}
