<?php

namespace DoctrineORMModule\Proxy\__CG__\GeneralServicer\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Document extends \GeneralServicer\Entity\Document implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'id', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'docName', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'docUrl', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'isConfirmed', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'createdOn', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'updatedOn', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'isHidden', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'mimeType', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'docExt', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'docCode', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'docStatus', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'coverNote'];
        }

        return ['__isInitialized__', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'id', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'docName', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'docUrl', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'isConfirmed', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'createdOn', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'updatedOn', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'isHidden', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'mimeType', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'docExt', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'docCode', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'docStatus', '' . "\0" . 'GeneralServicer\\Entity\\Document' . "\0" . 'coverNote'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Document $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocName($docName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocName', [$docName]);

        return parent::setDocName($docName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocName', []);

        return parent::getDocName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocUrl($docUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocUrl', [$docUrl]);

        return parent::setDocUrl($docUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocUrl', []);

        return parent::getDocUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsConfirmed($isConfirmed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsConfirmed', [$isConfirmed]);

        return parent::setIsConfirmed($isConfirmed);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsConfirmed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsConfirmed', []);

        return parent::getIsConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn($updatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsHidden($isHidden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsHidden', [$isHidden]);

        return parent::setIsHidden($isHidden);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsHidden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsHidden', []);

        return parent::getIsHidden();
    }

    /**
     * {@inheritDoc}
     */
    public function setMimeType($mimeType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMimeType', [$mimeType]);

        return parent::setMimeType($mimeType);
    }

    /**
     * {@inheritDoc}
     */
    public function getMimeType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMimeType', []);

        return parent::getMimeType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocExt($docExt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocExt', [$docExt]);

        return parent::setDocExt($docExt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocExt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocExt', []);

        return parent::getDocExt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocCode($docCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocCode', [$docCode]);

        return parent::setDocCode($docCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocCode', []);

        return parent::getDocCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocStatus(\GeneralServicer\Entity\DocumentStatus $docStatus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocStatus', [$docStatus]);

        return parent::setDocStatus($docStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocStatus', []);

        return parent::getDocStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdOffer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOffer', []);

        return parent::getIdOffer();
    }

    /**
     * {@inheritDoc}
     */
    public function getPolicy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPolicy', []);

        return parent::getPolicy();
    }

    /**
     * {@inheritDoc}
     */
    public function setPolicy($policy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPolicy', [$policy]);

        return parent::setPolicy($policy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoverNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoverNote', []);

        return parent::getCoverNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoverNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoverNote', [$note]);

        return parent::setCoverNote($note);
    }

}
