<?php

namespace DoctrineORMModule\Proxy\__CG__\IMServices\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MotorData extends \IMServices\Entity\MotorData implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'id', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'nonStandardAccesory', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isCoverAccessory', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isSoleOwner', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'owner', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isLockedUp', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isSafetyDevice', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isDriverLicense', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isPreviousClaim', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isDecline', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'declineDetails', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isCancel', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'cancelReason', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'purposeOfUse', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isCommercialGoods', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isCommercialTraveling', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'commercialDetails', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isPuposeOfUse', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'extraPurposeOfUse', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isExtendedFunc', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isLimitedToOnlyMe', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'peopleDrivingCar', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isUsageInNigeria', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'countrieOfUse', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isGeneralInfo', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'generalInfo', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'previousClaims'];
        }

        return ['__isInitialized__', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'id', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'nonStandardAccesory', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isCoverAccessory', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isSoleOwner', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'owner', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isLockedUp', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isSafetyDevice', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isDriverLicense', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isPreviousClaim', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isDecline', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'declineDetails', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isCancel', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'cancelReason', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'purposeOfUse', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isCommercialGoods', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isCommercialTraveling', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'commercialDetails', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isPuposeOfUse', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'extraPurposeOfUse', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isExtendedFunc', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isLimitedToOnlyMe', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'peopleDrivingCar', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isUsageInNigeria', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'countrieOfUse', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'isGeneralInfo', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'generalInfo', '' . "\0" . 'IMServices\\Entity\\MotorData' . "\0" . 'previousClaims'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MotorData $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNonStandardAccesory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNonStandardAccesory', []);

        return parent::getNonStandardAccesory();
    }

    /**
     * {@inheritDoc}
     */
    public function setNonStandardAccesory($nonStandardAccesory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNonStandardAccesory', [$nonStandardAccesory]);

        return parent::setNonStandardAccesory($nonStandardAccesory);
    }

    /**
     * {@inheritDoc}
     */
    public function addNonStandardAccesory($stan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNonStandardAccesory', [$stan]);

        return parent::addNonStandardAccesory($stan);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNonStandardAccesory($stan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNonStandardAccesory', [$stan]);

        return parent::removeNonStandardAccesory($stan);
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeOfVehicle($typeOfVehicle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeOfVehicle', [$typeOfVehicle]);

        return parent::setTypeOfVehicle($typeOfVehicle);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeOfVehicle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeOfVehicle', []);

        return parent::getTypeOfVehicle();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPurposeOfUse($purpose = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPurposeOfUse', [$purpose]);

        return parent::setIsPurposeOfUse($purpose);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPurposeOfUse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPurposeOfUse', []);

        return parent::getIsPurposeOfUse();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraPurposeOfUse($purpose)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraPurposeOfUse', [$purpose]);

        return parent::setExtraPurposeOfUse($purpose);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraPuposeOfUse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraPuposeOfUse', []);

        return parent::getExtraPuposeOfUse();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsExtendedFunction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsExtendedFunction', []);

        return parent::getIsExtendedFunction();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsExtendedFunction($func = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsExtendedFunction', [$func]);

        return parent::setIsExtendedFunction($func);
    }

    /**
     * {@inheritDoc}
     */
    public function setPurposeOfUse($damageDeductible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurposeOfUse', [$damageDeductible]);

        return parent::setPurposeOfUse($damageDeductible);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurposeOfUse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurposeOfUse', []);

        return parent::getPurposeOfUse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourtesyCar($courtesyCar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourtesyCar', [$courtesyCar]);

        return parent::setCourtesyCar($courtesyCar);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourtesyCar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourtesyCar', []);

        return parent::getCourtesyCar();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsExtendedFunc($isExtendedFunc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsExtendedFunc', [$isExtendedFunc]);

        return parent::setIsExtendedFunc($isExtendedFunc);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsExtendedFunc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsExtendedFunc', []);

        return parent::getIsExtendedFunc();
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectMotorData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectMotorData', []);

        return parent::getObjectMotorData();
    }

    /**
     * {@inheritDoc}
     */
    public function setRiskCovered($riskCovered)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRiskCovered', [$riskCovered]);

        return parent::setRiskCovered($riskCovered);
    }

    /**
     * {@inheritDoc}
     */
    public function getRiskCovered()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRiskCovered', []);

        return parent::getRiskCovered();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehicleValueType(\Settings\Entity\VehicleValueType $vehicleValueType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehicleValueType', [$vehicleValueType]);

        return parent::setVehicleValueType($vehicleValueType);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehicleValueType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehicleValueType', []);

        return parent::getVehicleValueType();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffer($offer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffer', [$offer]);

        return parent::setOffer($offer);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffer', []);

        return parent::getOffer();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPreviousClaims()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPreviousClaims', []);

        return parent::getIsPreviousClaims();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPreviousClaims($set)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPreviousClaims', [$set]);

        return parent::setIsPreviousClaims($set);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousClaims()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousClaims', []);

        return parent::getPreviousClaims();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreviousClaims($claims)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreviousClaims', [$claims]);

        return parent::setPreviousClaims($claims);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoverDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoverDetails', []);

        return parent::getCoverDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoverDetails($set)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoverDetails', [$set]);

        return parent::setCoverDetails($set);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSoleOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSoleOwner', []);

        return parent::getIsSoleOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsLockedUp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsLockedUp', []);

        return parent::getIsLockedUp();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSafetyDevice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSafetyDevice', []);

        return parent::getIsSafetyDevice();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDriverLicense()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDriverLicense', []);

        return parent::getIsDriverLicense();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPreviousClaim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPreviousClaim', []);

        return parent::getIsPreviousClaim();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclineDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeclineDetails', []);

        return parent::getDeclineDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function getCancelReason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancelReason', []);

        return parent::getCancelReason();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPuposeOfUse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPuposeOfUse', []);

        return parent::getIsPuposeOfUse();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraPurposeOfUse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraPurposeOfUse', []);

        return parent::getExtraPurposeOfUse();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsLimitedToOnlyMe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsLimitedToOnlyMe', []);

        return parent::getIsLimitedToOnlyMe();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeopleDrivingCar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeopleDrivingCar', []);

        return parent::getPeopleDrivingCar();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsUsageInNigeria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsUsageInNigeria', []);

        return parent::getIsUsageInNigeria();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountrieOfUse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountrieOfUse', []);

        return parent::getCountrieOfUse();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsGeneralInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsGeneralInfo', []);

        return parent::getIsGeneralInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeneralInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeneralInfo', []);

        return parent::getGeneralInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSoleOwner($isSoleOwner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSoleOwner', [$isSoleOwner]);

        return parent::setIsSoleOwner($isSoleOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner($owner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsLockedUp($isLockedUp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsLockedUp', [$isLockedUp]);

        return parent::setIsLockedUp($isLockedUp);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSafetyDevice($isSafetyDevice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSafetyDevice', [$isSafetyDevice]);

        return parent::setIsSafetyDevice($isSafetyDevice);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDriverLicense($isDriverLicense)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDriverLicense', [$isDriverLicense]);

        return parent::setIsDriverLicense($isDriverLicense);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPreviousClaim($isPreviousClaim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPreviousClaim', [$isPreviousClaim]);

        return parent::setIsPreviousClaim($isPreviousClaim);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeclineDetails($declineDetails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeclineDetails', [$declineDetails]);

        return parent::setDeclineDetails($declineDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function setCancelReason($cancelReason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCancelReason', [$cancelReason]);

        return parent::setCancelReason($cancelReason);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPuposeOfUse($isPuposeOfUse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPuposeOfUse', [$isPuposeOfUse]);

        return parent::setIsPuposeOfUse($isPuposeOfUse);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsLimitedToOnlyMe($isLimitedToOnlyMe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsLimitedToOnlyMe', [$isLimitedToOnlyMe]);

        return parent::setIsLimitedToOnlyMe($isLimitedToOnlyMe);
    }

    /**
     * {@inheritDoc}
     */
    public function setPeopleDrivingCar($peopleDrivingCar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeopleDrivingCar', [$peopleDrivingCar]);

        return parent::setPeopleDrivingCar($peopleDrivingCar);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUsageInNigeria($isUsageInNigeria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUsageInNigeria', [$isUsageInNigeria]);

        return parent::setIsUsageInNigeria($isUsageInNigeria);
    }

    /**
     * {@inheritDoc}
     */
    public function setCountrieOfUse($countrieOfUse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountrieOfUse', [$countrieOfUse]);

        return parent::setCountrieOfUse($countrieOfUse);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsGeneralInfo($isGeneralInfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsGeneralInfo', [$isGeneralInfo]);

        return parent::setIsGeneralInfo($isGeneralInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function setGeneralInfo($generalInfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeneralInfo', [$generalInfo]);

        return parent::setGeneralInfo($generalInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDecline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDecline', []);

        return parent::getIsDecline();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDecline($isDecline)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDecline', [$isDecline]);

        return parent::setIsDecline($isDecline);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCancel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCancel', []);

        return parent::getIsCancel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCancel($isCancel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCancel', [$isCancel]);

        return parent::setIsCancel($isCancel);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCommercialGoods()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCommercialGoods', []);

        return parent::getIsCommercialGoods();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCommercialGoods($isCommercialGoods)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCommercialGoods', [$isCommercialGoods]);

        return parent::setIsCommercialGoods($isCommercialGoods);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCommercialTraveling()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCommercialTraveling', []);

        return parent::getIsCommercialTraveling();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCommercialTraveling($isCommercialTraveling)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCommercialTraveling', [$isCommercialTraveling]);

        return parent::setIsCommercialTraveling($isCommercialTraveling);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommercialDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommercialDetails', []);

        return parent::getCommercialDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommercialDetails($commercialDetails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommercialDetails', [$commercialDetails]);

        return parent::setCommercialDetails($commercialDetails);
    }

}
