<?php

// if(count($proposals) == 0){
// echo "";
// }
foreach ($proposals as $proposal) {
    ?>

<tr>
	<td><span class="label label-default"><?php echo $this->dateFormat($proposal->getCreatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_US")?></span></td>
	<td><a
		href="<?php echo $this->url("cus_proposal/default", array("action"=>"pre-view", "id"=>$proposal->getId())); ?>"> <?php  echo ($proposal->getProposalTitle() == NULL ? "No Title": $proposal->getProposalTitle())?></a>
	</td>
	<td>

                     <?php echo ($proposal->getServiceType() == NULL ? "" : $proposal->getServiceType()->getInsuranceService())?>
                    </td>
	<td>  <?php   echo ($proposal->getInsurer() == NULL ? "No Insurer Selected" : "<img alt='' src='".$this->insurerLogohelper($proposal->getInsurer()->getId())."' class='img-circle   img-responsive' width=100 >");?></td>
	<!--                     <td>Miami, FL<a href="#"><i class="fa fa-map-marker fa-fw text-muted"></i></a></td> -->
	<!--                     <td> -->
	<!--                       <div class="progress"> -->
	<!--                         <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"> -->
	<!--                         </div> -->
	<!--                       </div> -->
	<!--                     </td> -->
	<td class="text-right"><a
		href="<?php echo $this->url("cus_proposal/default", array("action"=>"pre-view", "id"=>$proposal->getId())); ?>"
		class="btn btn-default btn-xs" data-toggle="tooltip"
		data-placement="top" title="View Proposal"><i class="fa fa-eye"></i></a>

	</td>
</tr>
<?php }?>