<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Packages\Module'                        => __DIR__ . '/Module.php',
    'Packages\Controller\PackageController' => __DIR__ . '/src/Packages/Controller/PackageController.php',
    'PackagesTest\Framework\TestCase'        => __DIR__ . '/tests/Packages/Framework/TestCase.php',
    'PackagesTest\SampleTest'                => __DIR__ . '/tests/Packages/SampleTest.php',
);
