<?php
echo $this->headtitle('All Claims');

$claims = $this->unsettledClaims;
if ($this->identity()) {
    ?>

<div class="row">
	<div class="col-md-9 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Unsettled Claims</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<div class="table-responsive">
					<table class="table table-striped projects">
						<thead>
							<tr>
								<th>Claim ID</th>
								<th>Title</th>
								<th>Policy</th>
								<th>Status</th>
								<th style="width: 20%">Action</th>
							</tr>
						</thead>
						<tbody>


	
			<?php  echo $this->partial('claims-all-broker-snipet', array('claims'=>$claims))?>
				  </tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-3 col-xs-1">

		<div class="x_panel">

			<div class="x_content">
				<img alt="" style='width: 100%;'
					src="<?php echo $this->basepath("imappadd/banner2.jpg")?>">
			</div>
		</div>
	</div>
</div>
<?php }?>

