<?php
$this->headtitle("View Proposals");
if($this->identity()){
   
?>
<div class="row">

<div  class="col-md-9 col-sm-9 col-xs-12">
<div class="row">
	
                    <?php  echo $this->partial("proposal-view-proposal", array("proposal"=>$proposal));?>

<?php   echo $this->partial("proposal-view-buttons-snipet", array("jects"=>$proposal))?>
	<?php   //echo $this->partial("proposal-view-generated-premium-snipet", array("jects"=>$proposal))?>

</div>
<div class="row">

	<?php  echo $this->partial("proposal-customer-snipet", array("customer"=>$proposal->getCustomer()));?>
	
				<?php  //echo $this->partial("proposal-invoices-snipet", array('proposalInvoice'=>$proposal->getInovice()));?>
		
	
	<?php  //echo $this->partial('proposal-related-objects-snipet', array("jects"=>$proposal->getObject()->toArray()))?>
</div><?php }?>
</div>
<!-- <div id="winpopup"></div> -->
<div class="col-md-3 col-xs-12">

		<div class="x_panel">

			<div class="x_content">
				<img alt="" style='width: 100%;'
					src="<?php echo $this->basepath("imappadd/banner1.jpg")?>">
			</div>
		</div>
	</div>
</div>

