
<?php
echo $this->HeadScript()->appendFile($this->basepath() . '/js/parsley/parsley.min.js', 'text/javascript')?>

<?php

$objectForm = $this->form;
$objectForm->setAttributes(array('novalidate'));
$objectForm->prepare();
//
//
// ?>


<div class="row" ng-app="ObjectModule">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Create an Object/Property</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					<!-- 					<li class="dropdown"><a href="#" class="dropdown-toggle" -->
					<!-- 						data-toggle="dropdown" role="button" aria-expanded="false"><i -->
					<!-- 							class="fa fa-wrench"></i></a> -->
					<!-- 						<ul class="dropdown-menu" role="menu"> -->
					<!-- 							<li><a href="#">Settings 1</a></li> -->
					<!-- 							<li><a href="#">Settings 2</a></li> -->
					<!-- 						</ul></li> -->
					<li><a class="close-link"><i class="fa fa-close"></i></a></li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">

<?php

echo $this->form()->openTag($objectForm);
$objectField = $form->get('objectFieldset');

?>

<?php echo $this->partial('new_object_partial', array('objectField'=>$objectField));?>		


				<div class="ln_solid"></div>
				<div class="form-group">
					<div class="col-md-6 col-md-offset-3">
							
							<?php echo $this->formsubmit($objectForm->get('reset'));?>
							<?php echo $this->formsubmit($objectForm->get('submit'));?>
						</div>
				</div>
				<?php 
 echo $this->formRow($objectForm->get('csrf'));
    echo $this->form()->closeTag();
    ?>

			</div>
		</div>
	</div>
</div>
<?php

echo $this->headScript()
    ->appendFile($this->basePath('angular/ObjectModule.js'))
->appendFile($this->basePath('js/jquery.mask.min.js'))
    ->appendFile($this->basePath('angular/controllers/ObjectController.js'));
?>
<script type="text/javascript">


        $(document).ready(function () {
             $('.money').mask('000,000,000,000,000.00', {reverse: true});
            $('.phone').mask('0-000-000-0000');
            

        });

        // for the type of customer
        
    </script>


