<?php
// $offerInfo = $this->offerInfo;
echo $this->headtitle('OBJECT VIEW ');
$user = $this->user;
$userInfo = $this->userInfo;
$ct = $this->objectE;

?>

<div class="row">
	<div class="col-md-8 col-sm-8 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>OBJECT</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>

				</ul>
				<div class="clearfix"></div>

			</div>
			<div class="x_content">
                  

                     <?php echo $this->partial('object-info-snipet', array('ject'=>$ct));?>
              
                  
                   </div>

		</div>
	</div>
              
             <?php  echo $this->partial("proposal-customer-snipet", array("customer"=>$ct->getCustomer()));?>
              
              </div>
<div class="row">
              
               
              <?php echo $this->partial('general-doc-snipet', array('doc'=>$ct->getDocument()));?>
              
              
              
              
              
            </div>