<?php

?>

<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif !important; color: #666666; background:white; text-decoration: none;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" summary="">
    <tbody>
      <tr align="center">
        <td style="height: 30px; width: 100%;">
          &nbsp;
        </td>
      </tr>
      <tr align="center">
        <td valign="top" style="width: 100%;">
          <table cellspacing="0" cellpadding="0" border="0" summary="">
            <tbody>
              <tr align="center">
                <td valign="middle" style="width: 100%;">
                  <img height="71" style="border:0;height:71px;" src="<?php echo $logo ?>" alt="Logo">
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
      <tr align="center">
        <td style="height: 50px; width: 100%;">
          &nbsp;
        </td>
      </tr>
      <tr align="center">
        <td valign="top" style="width: 100%;">
          <table style="padding: 0px; border: 0; max-width: 520px; text-align: center;" width="100%" cellpadding="0" cellspacing="0" border="0" summary="">
            <tbody>
              
              <tr align="center">
                <td style="height: 10px; width: 100%;">
                  &nbsp;
                </td>
              </tr>

              <tr align="center">
                <td style="width: 100%; margin: 0px 10px; line-height: 24px; font-size: 16pt; font-weight: bold; color: #333333;">
                  <p style="margin: 0; padding: 0;">
                    You have a new message
                  </p>
                </td>
              </tr>
              <tr align="center" style="margin: 0px 10px;">
                <td style="width: 100%; line-height: 24px; font-size: 13pt;">
                  <p>
                   You have a new message from <?php echo $sender ?>
                  </p>
                </td>
              </tr>
              <tr align="center">
                <td style="height: 30px; width: 100%;">
                  &nbsp;
                </td>
              </tr>
              
              <tr>
                <td style="height: 40px; width: 100%;">
                  &nbsp;
                </td>
              </tr>
              <tr align="center" style="margin: 0px 10px;">
                <td style="width: 100%; font-size: 9pt; color: #b3b3b3;">
                  <p style="line-height: 16px; max-width: 400px;">
                    <?php echo $message ?> </p>
                </td>
              </tr>
            </tbody>
          </table>
          <table style="border-collapse:collapse; max-width: 520px; text-align: center;" cellpadding="0" cellspacing="0" border="0" summary="">
            <tbody>
              <tr>
                <td style="height: 80px; width: 100%;">
                  &nbsp;
                </td>
              </tr>
              <tr>
                <td align="center" style="width: 100%;">
                  <p style="line-height: 20px; font-size: 9pt; color: #b3b3b3;">
                    <a href="<?php echo $brokerWebsite ?>" style="color: #b3b3b3; text-decoration: underline;" target="_blank"><?php echo $brokerName ?></a>
                    
                  </p>
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
      <tr align="center">
        <td style="height: 55px; width: 100%;">
          &nbsp;
        </td>
      </tr>
    </tbody>
  </table>


</body>