<?php


//var_dump($doc);

?>


<div class="col-md-6 col-xs-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Related Documents:</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  
                 <?php if(count($doc) == 0){?>
                 There are no documents available
                 <?php } else {
                     foreach ($doc as $docs){?>
                     <?php $this->partial('', array());?>
                <?php }}?>
                   </div>
                </div>
              </div>