  <?php
  use Zend\Session\Container;
  
  $chatkitSession = new Container("pusher_chatkit_session");
  $userEntity = $this->identity();
  echo $this->headscript()->appendFile("https://unpkg.com/@pusher/chatkit-client@1/dist/web/chatkit.js");
  ?>
  
  <div id="low"></div>
  
  <script type="text/javascript">
  <!--
  
  //-->
  
  
  function connection(chatManager){
	  chatManager.connect().then().err()
  }
  
  
  $(document).ready(function(){
  const chatManager = new ChatManager({
		instanceLocator: 'v1:us1:80215247-1df3-4956-8ba8-9744ffd12161',
		userId:<?php echo $userEntity->getUsername()?>,
		tokenProvider: <?php  echo json_encode($chatkitSession->token)?>
	  })
	  
	  
	  chatManager.
	  
	 
  
  
	
  
  
  })
  </script>
  
