<?php

?>

<div class="col-md-6 col-sm-6 col-xs-12">
                  <div class="x_panel">
                    <div class="x_title">
                      <h2>Registered Properties</h2>
                      
                      <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                      <div class="">
                       <ul class="list-unstyled top_profiles scroll-view">
                        <?php echo $this->proposal_object_list_helper($proposalEntity)?>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>