<?php
$customer = $this->customer;
?>
<div class="col-md-3 col-xs-12 widget widget_tally_box">
                        <div class="x_panel fixed_height_390">
                          <div class="x_content">

                            <div class="flex">
                              <ul class="list-inline widget_profile_box">
                                <li>
                                  <a>
<!--                                     <i class="fa fa-facebook"></i> -->
                                  </a>
                                </li>
                                <li>
                                  <img src="<?php  echo $this->basepath('img/customeravatar/').$this->customer_category_avatar_helper($customer->getCustomerCategory()->getId())?>" alt="" class="img-circle profile_img">
                                </li>
                                <li>
                                  <a>
<!--                                     <i class="fa fa-twitter"></i> -->
                                  </a>
                                </li>
                              </ul>
                            </div>

                            <h3 class="name"><?php echo $customer->getName()?></h3>

                            <div class="flex">
<!--                               <ul class="list-inline count2"> -->
<!--                                 <li> -->
<!--                                   <h3>123</h3> -->
<!--                                   <span>Articles</span> -->
<!--                                 </li> -->
<!--                                 <li> -->
<!--                                   <h3>1234</h3> -->
<!--                                   <span>Followers</span> -->
<!--                                 </li> -->
<!--                                 <li> -->
<!--                                   <h3>123</h3> -->
<!--                                   <span>Following</span> -->
<!--                                 </li> -->
<!--                               </ul> -->
                            </div>
                            <p>
                              <?php  echo $customer->getUser()->getEmail()?>
                            </p>
                            <p>
                              <?php  echo $customer->getFullAddress()?>
                            </p>
                          </div>
                        </div>
                      </div>