

<div class="col-md-6 col-sm-6 col-xs-12">
                  <div class="x_panel">
                    <div class="x_title">
                      <h2>Uploaded Documents</h2>
                      
                      <div class="clearfix"></div>
                    </div>
                    <div class="x_content ">
                    <?php  echo $this->partial("general-dropzone-upload-form-snippet", array("dropZoneUploadForm"=>$dropZoneForm))?>
                    <hr>
<?php  echo $this->proposal_process_doc_helper($proposalEntity->getId()) // echo $this->partial("general-dropzone-upload-form-snippet", array("dropZoneUploadForm"=>$dropZoneUploadForm))?>
                      
                    </div>
                  </div>
                </div>
                