<?php

?>
<div class="animated flipInY col-lg-3 col-md-3 col-sm-12 col-xs-12">
		<a href="" data-toggle='modal' data-target='.proposal-modal-lg' > <img alt=""
			src="<?php  echo $this->basepath("img/update.png")?>"
			style="width: 100%">

		</a>

	</div>
	<div class="animated flipInY col-lg-3 col-md-3 col-sm-12 col-xs-12">
		<a href="" data-toggle='modal'  data-target='.bs-object-modal-lg'> <img alt=""
			src="<?php  echo $this->basepath("img/generate.png")?>"
			style="width: 100%">
		</a>

	</div>

	<div class="animated flipInY col-lg-3 col-md-3 col-sm-12 col-xs-12">

		<img alt="" src="<?php  echo $this->basepath("img/upload.png")?>"
			style="width: 100%">

	</div>


	<div class="animated flipInY col-lg-3 col-md-3 col-sm-12 col-xs-12">

		<img alt="" src="<?php  echo $this->basepath("img/preview.png")?>"
			style="width: 100%">

	</div>