<?php
echo $this->headtitle("Renew Subcription");
$form->prepare();
$form->get("subscription")->get("package")->setValue(3);
?>

<div class="row" ng-app="SubModule">
	 <div class='col-md-3 col-sm-3 col-xs-12'>
      <?php  echo $this->partial("settings-navigation")?>
    </div>
    <?php echo  $this->form()->openTag($form)?>
	<div class='col-md-6 col-sm-6 col-xs-12'>
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>Select Prefered Package</h2>
					<ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
						</li>
						<li class="dropdown"><a href="#" class="dropdown-toggle"
							data-toggle="dropdown" role="button" aria-expanded="false"><i
								class="fa fa-wrench"></i></a></li>

					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					<br />
					<div class="row">          
   
  <?php 
  echo $this->partial('broker-package-select-snipet', array('form'=>$form->get('subscription')))?>

  <?php echo $this->partial("transaction_user_card_payment_snipet", array("payForm"=>$form->get("card_payment")))?>
    <br>
   </div>
					<div class="row"> 
    <?php // echo $this->partial('account-package-display-snipet', array('pack'=>$repo))?>
    </div>
				</div>
			</div>
		</div>

	</div>
	<div class='col-md-3 col-sm-3 col-xs-12'>
		<div class="x_panel">
			<div class="x_title">
				<h2>Total Amount Payable</h2>

				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<div class="row">
					<div
						class="animated flipInY col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="tile-stats">

							<div ng-cloak class="count"> {{totalAmount | currency :"&#x20A6;"}} <?php // echo $this->myCurrencyFormat(0, 'NGN', 'en_NG', true)?></div>

							<h4>VAT: {{taxes | currency : "&#x20A6;"}}</h4>
							<div class="clearfix"></div>
							<p> <?php  echo $this->formrow($form->get('submit'))?></p>

						</div>
					</div>
				</div>
			</div>
		</div>
		
       <?php echo $this->dashboard_broker_account_helper($broker); ?>
       <?php  echo $this->dashboard_broker_sub_helper($broker->getSubscription())?>
   
	</div>
 <?php echo $this->form()->closeTag()?>

</div>

<?php

echo $this->headScript()
    
    ->appendFile($this->basePath('js/jquery.mask.min.js'))
    ->appendFile($this->basePath('angular/controllers/subscriptionController.js'));
?>