<?php
echo $this->headtitle("All Cover Notes");

?> 
<div class="row">
              <div class="col-md-9 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>My Cover Notes</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      
                     
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <?php  echo $this->partial("general-error-ponters")?>
                  <div class="x_content">

<!--                     <p>Simple table with project listing with progress and editing options</p> -->

                    <!-- start project list -->
                    <div class="table-responsive">
                    <p style="color: red;">All cover note has a count down of 30 day to be issued. The system uses this as a measure of the companies efficiency and hence rates the company high</p>
				<table id="datatable"
					class="table table-striped table-bordered">
					<thead>
						<tr>
							
							<th>Customer Details</th>
							<th>CoverNote Details</th>
							<th>Policy CountDown</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
                    <?php  echo $this->partial("policy-my-covernore-snipet", array("coverNote"=>$coverNote))?>
                    </tbody>
				</table>
				</div>
				
                    <!-- end project list -->

                  </div>
                </div>
              </div>
              <div class="col-md-3 col-xs-12">

		<div class="x_panel">

			<div class="x_content">
				<img alt="" style='width: 100%;'
					src="<?php echo $this->basepath("imappadd/banner2.jpg")?>">
			</div>
		</div>
	</div>
            </div>
            
             <script src="<?php echo $this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.flash.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/datatables.net-scroller/js/datatables.scroller.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/jszip/dist/jszip.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/pdfmake/build/pdfmake.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('vendors/pdfmake/build/vfs_fonts.js') ?>"></script>
<?php  echo $this->partial("general-datable-script")?>