<?php
echo $this->partial("general-dropzone-upload-form-snippet", array("dropZoneUploadForm"=>$logoForm));

?>

<?php 

// echo $this->headScript()->appendFile($this->basePath('/vendors/dropzone/dist/dropzone.js'));
//echo $this->headscript()->appendFile($this->basepath("/credit-card/js/index.js"));
// echo $this->headLink()->appendStylesheet('/vendors/dropzone/dist/basic.css');
// echo $this->headLink()->appendStylesheet('/vendors/dropzone/dist/dropzone.css');
//echo $this->headLink()->appendStylesheet('/credit-card/css/style.css');

?>