<?php


?>

<div class="form-group">
							
								<?php  echo $this->formLabel($brokerCeoFieldset->get('firstname'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php  echo $this->formElement($brokerCeoFieldset->get('firstname'));?>
									
								</div>

	<div style="font-size: 9px; color: red;">
		
								<?php  echo $this->formElementErrors($brokerCeoFieldset->get('firstname'));  // this defines the error?> 
							</div>
	
</div>

<div class="form-group">
							
								<?php  echo $this->formLabel($brokerCeoFieldset->get('lastname'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php  echo $this->formElement($brokerCeoFieldset->get('lastname'));?>
									
								</div>

	<div style="font-size: 9px; color: red;">
		
								<?php  echo $this->formElementErrors($brokerCeoFieldset->get('lastname'));  // this defines the error?> 
							</div>
	
</div>

<div class="form-group">
							
								<?php  echo $this->formLabel($brokerCeoFieldset->get('email'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php  echo $this->formElement($brokerCeoFieldset->get('email'));?>
									
								</div>

	<div style="font-size: 9px; color: red;">
		
								<?php  echo $this->formElementErrors($brokerCeoFieldset->get('email'));  // this defines the error?> 
							</div>
	
</div>

<div class="form-group">
							
								<?php  echo $this->formLabel($brokerCeoFieldset->get('linkedIn'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php  echo $this->formElement($brokerCeoFieldset->get('linkedIn'));?>
									
								</div>

	<div style="font-size: 9px; color: red;">
		
								<?php  echo $this->formElementErrors($brokerCeoFieldset->get('linkedIn'));  // this defines the error?> 
							</div>
	
</div>


<div class="form-group">
							
								<?php  echo $this->formLabel($brokerCeoFieldset->get('facebook'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php  echo $this->formElement($brokerCeoFieldset->get('facebook'));?>
									
								</div>

	<div style="font-size: 9px; color: red;">
		
								<?php  echo $this->formElementErrors($brokerCeoFieldset->get('facebook'));  // this defines the error?> 
							</div>
	
</div>

<div class="form-group">
							
								<?php  echo $this->formLabel($brokerCeoFieldset->get('tweeter'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php  echo $this->formElement($brokerCeoFieldset->get('tweeter'));?>
									
								</div>

	<div style="font-size: 9px; color: red;">
		
								<?php  echo $this->formElementErrors($brokerCeoFieldset->get('tweeter'));  // this defines the error?> 
							</div>
	
</div>

