<?php
$form = $this->form;

?>
<h2>Broker Address</h2>
<div class="form-group">
							
								<?php echo $this->formLabel($form->get('address1'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($form->get('address1'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
		<br>
								<?php echo $this->formElementErrors($form->get('address1'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">
							
								<?php echo $this->formLabel($form->get('address2'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($form->get('address2'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
		<br>
								<?php echo $this->formElementErrors($form->get('address2'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">
							
								<?php echo $this->formLabel($form->get('country'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($form->get('country'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
		<br>
								<?php echo $this->formElementErrors($form->get('country'));  // this defines the error?> 
							</div>
</div>
<div class="form-group">
							
								<?php echo $this->formLabel($form->get('state'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($form->get('state'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
		<br>
								<?php echo $this->formElementErrors($form->get('state'));  // this defines the error?> 
							</div>
</div>
<div class="form-group">
							
								<?php echo $this->formLabel($form->get('zipCode'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($form->get('zipCode'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
		<br>
								<?php echo $this->formElementErrors($form->get('zipCode'));  // this defines the error?> 
							</div>
</div>