<?php
$invoiceData = $this->invoiceData;
$userInfo = $this->userInfo;
$info = $this->offerInfo;
$payment = $this->payment;
$policy = $this->policy;
$description= 'Type of policy, and insuring company , start Date and End Date  and type of coverage ';

$date = new \Datetime();

?>

<section class="content invoice">
                      <!-- title row -->
                      <div class="row">
                        <div class="col-xs-12 invoice-header">
                          <h1>
                                          <i class="fa fa-globe"></i> Invoice.
                                          <small class="pull-right">Date: <?php echo  date('Y-m-d'); ?></small>
                                      </h1>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- info row -->
                      <div class="row invoice-info">
                       <?php  echo $this->ImappInvoiceOfficeViewHelper()?>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                          To
                          <address>
                                          <strong><?php// $userInfo->getFirstname()?></strong> 
                                          <br>795 Freedom Ave, Suite 600 <?php //$userInfo->getAddress()?>
                                          <br>New York, CA 94107 <?php ?>
                                          <br>Phone: 1 (804) 123-9876
                                          <br>Email: jon@ironadmin.com <?php //$userInfo->getPhoneNo();?>
                                      </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                          <b>Invoice No.</b>
                          <br>
                         
                          <b>Order ID:</b> 4F3S8J
                          <br>
                          <b>Payment Date:</b> 2/22/2014
                          <br>

                          <b>Policy No.: </b><i>Not Issued</i>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <!-- Table row -->
                      <div class="row">
                        <div class="col-xs-12 table">
                          <table class="table table-striped">
                            <thead>
                              <tr>
<!--                                 <th>Qty</th> -->
                                <th>Product</th>
<!--                                 <th>Serial #</th> -->
                                <th style="width: 45%">Description</th>
                                <th>Sum</th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                              
                                <td>Call of Duty</td>
<!--                                 <td>455-981-221</td> -->
                                <td> <?php echo $description ?>
                                </td>
                                <td>&#x20A6;64.50</td>
                              </tr>
                              <tr>
                                
                                <td>Need for Speed IV</td>
<!--                                 <td>247-925-726</td> -->
                                <td>Wes Anderson umami biodiesel</td>
                                <td>&#x20A6;50.00</td>
                              </tr>
                              <tr>
                                
                                <td>Monsters DVD</td>
<!--                                 <td>735-845-642</td> -->
                                <td>Terry Richardson helvetica tousled street art master, El snort testosterone trophy driving gloves handsome letterpress erry Richardson helvetica tousled</td>
                                <td>&#x20A6;10.70</td>
                              </tr>
                              <tr>
                              
                                <td>Grown Ups Blue Ray</td>
<!--                                 <td>422-568-642</td> -->
                                <td>Tousled lomo letterpress erry Richardson helvetica tousled street art master helvetica tousled street art master, El snort testosterone</td>
                                <td>&#x20A6;25.99</td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <div class="row">
                        <!-- accepted payments column -->
                        <div class="col-xs-6">
                        <!-- Include the payment mode view Helper here -->
                          <p class="lead">Payment(s):</p>
                          <?php  echo $this->paymentMethodViewHelper();?>
<!--                           <img src="images/visa.png" alt="Visa"> -->
<!--                           <img src="images/mastercard.png" alt="Mastercard"> -->
<!--                           <img src="images/american-express.png" alt="American Express"> -->
<!--                           <img src="images/paypal.png" alt="Paypal"> -->
                          <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                           Payment Status goes Here
                          </p>
                        </div>
                        <!-- /.col -->
                        <div class="col-xs-6">
                          <p class="lead">Amount Due 2/22/2014</p>
                          <div class="table-responsive">
                            <table class="table">
                              <tbody>
                               
                                
                              
                                <tr>
                                  <th>Total:</th>
                                  <td>&#x20A6;265.24</td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <!-- this row will not appear when printing -->
                      <div class="row no-print">
                        <div class="col-xs-12">
                          <button class="btn btn-default" onclick="window.print();"><i class="fa fa-print"></i> Print</button>
                          <button class="btn btn-success pull-right"><i class="fa fa-credit-card"></i> Submit Payment</button>
                          <button class="btn btn-primary pull-right" style="margin-right: 5px;"><i class="fa fa-download"></i> Generate PDF</button>
                        </div>
                      </div>
                    </section>