<?php
if (count($unsettleClaims) > 0) {
    
    foreach ($unsettleClaims as $off) {
        ?>

<tr>

	<td><?php  echo ($off->getClaimUid() == NULL ? "": strtoupper($off->getClaimUid()))?><br>
							TOPIC :<?php  echo ($off->getClaimTopic() == NULL ? "": $off->getClaimTopic())?><br>
		<strong><small>Created On: <?php  echo $this->dateFormat($off->getCreatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, "en_US")?></small></strong>
	<?php echo ($off->getClaimStatus() != NULL ? $this->statusHelper($off->getClaimStatus()->getStatus()) : '')?>
	</td>
	<td><?php echo strtoupper($off->getPolicy()->getPolicyCode())?><br>
							POLICY NAME : <?php  echo ($off->getPolicy()->getPolicyName() == NULL ? "" : $off->getPolicy()->getPolicyName())?><br>
		<strong>EXPIRES ON : <?php  echo ($off->getPolicy()->getEndDate() == NULL ? "" : $this->dateFormat($off->getpolicy()->getEndDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, "en_US"))?></strong>
	 
	</td>
	<td>
<?php echo $this->customer_claims_unsettledclaims_action_helper($off);?>
</td>



</tr>
<?php
    }
}

?>

<?php  //echo $this->paginationcontrol($unsettleClaims, "Sliding"); ?>

