<?php

?>

<div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
            <div class="panel-heading panel-collapse-trigger">
              <h4 class="panel-title">Claims Menu</h4>
            </div>
            <div class="panel-body list-group">
              <ul class="list-group list-group-menu">
                <li class="list-group-item"><a id="btn3" class="ajax_element link-text-color"
							data-json='{"type":"standard"}'
							data-href="<?php  echo $this->url("board", array("action"=>"layclaimmodal"))?>" 
							
						data-animated >New Claims</a></li>
                <li class="list-group-item"><a class="link-text-color" href="<?php  echo $this->url("cus_claims")?>">Unsettled Claims</a></li>
               
           
              </ul>
            </div>
          </div>
          
         