<?php
?>
<?php
echo $this->headtitle("Missing UID")?>

<div class="c-404">
<div class="c-alert c-alert--danger alert">
			<span class="c-alert__icon"> <i class="feather icon-slash"></i>
			</span>
			<div class="c-alert__content">
				<h4 class="c-alert__title">Error!! MISSING UID.</h4>
				<p>The unique identifier is missing</p>
			</div>
		</div>
	<div class="c-404__content">
		
		<h2>Missing UID</h2>
		<p class="c-404__des">The portal UID must be available before u can
			access this information</p>

		<!--         <a class="c-404__link" href="#"><i class="feather icon-arrow-left"></i> Retrun to Homepage</a> -->
	</div>

	<span class="c-404__shape1"></span> <span class="c-404__shape2"></span>
</div>