<?php
echo $this->headtitle("Not AUthorized")?>

<div class="c-404">
<div class="c-alert c-alert--danger alert">
			<span class="c-alert__icon"> <i class="feather icon-slash"></i>
			</span>
			<div class="c-alert__content">
				<h4 class="c-alert__title">Error!! NOT AUTHORIZED.</h4>
				<p>Authorization Error</p>
			</div>
		</div>
	<div class="c-404__content">
		
		<h2>Authorization Revoked</h2>
		<p class="c-404__des">Sorry !! you are no more authorized to view this
			information</p>

		<!--         <a class="c-404__link" href="#"><i class="feather icon-arrow-left"></i> Retrun to Homepage</a> -->
	</div>

	<span class="c-404__shape1"></span> <span class="c-404__shape2"></span>
</div>