
<div class="alert alert-info alert-dismissible fade in" role="alert">
	<strong>Payment can be made into either of these bank account listed below</strong>
</div>
<p align="center">
	Notify Broker about payment <a style="width: 100%;"
		class="btn btn-success btn-sm" href="#modal-update-manual-process"
		data-toggle="modal" class="btn btn-white paper-shadow relative"
		data-animated data-z="0.5" data-hover-z="1">CLICK TO NOTIFY BROKER</a>
</p>
<?php
if ($brokerEntity->getBrokerBankAccount() != NULL) {
    
    foreach ($brokerEntity->getBrokerBankAccount() as $account) {
        ?>
<div
	class="media media-grid media-paper-shadow margin-top-none s-container">
	<div class="media-left">
		<div class="icon-block half img-circle bg-grey-300">
			<i class="fa fa-file-text text-white"></i>
		</div>
	</div>
	<div class="media-body">
		<div class="panel panel-default paper-shadow" data-z="0.5">
			<div class="panel-body">
				<div class="pull-right">
					<a href="" class="btn btn-white btn-flat"></a>
				</div>
				<h4 class="text-title media-heading">
					<a href="" class="link-text-color"><?php echo $account->getBankName()->getBankName()?></a>
				</h4>
				<p class="text-light text-caption">
					Account Number: <a href="#">
                       <?php echo $account->getBankAccountNo()?></a> <br>
				</p>
				<p class="text-light">
                  AccountName : <?php  echo $account->getAccountName()?><br>
                  SwiftCode : <?php  echo ($account->getSwiftCode() == NULL ? " ": $account->getSwiftCode())?><br>
                   SwiftCode : <?php  echo ($account->getSortCode() == NULL ? " ": $account->getSortCode())?><br>
				</p>
			</div>
		</div>
	</div>
</div>

<?php
    }
    
    ?>



<?php }?>
