<?php
use Transactions\Service\InvoiceService;
?>






<div class="item col-xs-12 col-lg-6">
	<div class="panel panel-default paper-shadow" data-z="0.5">
		<div class="panel-heading">
			<div class="media v-middle">
				<div class="media-body">
					<h4 class="text-headline margin-none">My Invoices</h4>

				</div>
				<div class="media-right">
					<!--                       <a class="btn btn-white btn-flat" href="website-instructor-statement.html">Statement</a> -->
				</div>
			</div>
		</div>
		<div class="table-responsive">
			<table class="table text-subhead v-middle">
				<tbody>
						
						
						
					
<?php
$count = (count($invoices) < 10 ? count($invoices) : 10);
if (count($invoices) == 0) {
    echo "<li class='list-group-item media v-middle'><div class='media-body'>No invoices issued yet</div></li>";
} else {
    for ($i = 0; $i < $count; $i ++) {
        ?>
		<tr>
						<td class="width-100 text-caption">
							<div
								class="label <?= ($invoices[$i]->getStatus()->getId() == InvoiceService::INVOICE_PAID_STATUS ? 'label-success' : 'label-danger')?> label-xs">
								<a
									href="<?php echo $this->url("cus_invoice/default", array("action"=>"view", "id"=>$invoices[$i]->getInvoiceUid()))?>"><?php echo $this->dateFormat($invoices[$i]->getGeneratedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, 'en_US')?></a>
							</div>
						</td>
						<td><?php  echo $invoices[$i]->getInvoiceCategory()->getCategory()?></td>

						<td class="width-50 text-center"><a
							href="<?php echo $this->url("cus_invoice/default", array("action"=>"view", "id"=>$invoices[$i]->getInvoiceUid()))?>"><?php  echo $this->myCurrencyFormat((float)$invoices[$i]->getAmount(), $invoices[$i]->getCurrency()->getCode(), 'en_NG', true)?></a></td>
					</tr>

<?php
    }
}
?>

 </tbody>
			</table>
		</div>

		<div class="panel-footer">
			<a href="<?php  echo $this->url("cus_invoice")?>"
				class="btn btn-default paper-shadow relative" data-z="0"
				data-hover-z="1" data-animated href="#"> View All</a>
		</div>
	</div>
</div>