<?php
$proposalForm = $this->proposalForm;

?>

<div class="form-group">
							
								<?php echo $this->formLabel($customerFieldset->get('name'))?> 
								
								<div class="col-md-9 col-sm-9 col-xs-12">
								<?php echo $this->formElement($customerFieldset->get('name'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($customerFieldset->get('name'));  // this defines the error?> 
							</div>
</div>
<div class="form-group" data-ng-show="isDob">
							
								<?php echo $this->formLabel($customerFieldset->get('dob'))?> 
								
								<div class="col-md-9 col-sm-9 col-xs-12">
								<?php echo $this->formElement($customerFieldset->get('dob'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo $this->formElementErrors($customerFieldset->get('dob'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">
							
								<?php echo $this->formLabel($customerFieldset->get('phone'))?> 
								
								<div class="col-md-9 col-sm-9 col-xs-12">
								<?php echo $this->formElement($customerFieldset->get('phone'));?>
									
								</div>
								<?php echo  $this->formElementErrors($customerFieldset->get('phone'));  // this defines the error?> 
							</div>

<div class="form-group">
							
								<?php echo $this->formLabel($customerFieldset->get('email'))?> 
								
								<div class="col-md-9 col-sm-9 col-xs-12">
								<?php echo $this->formElement($customerFieldset->get('email'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo $this->formElementErrors($customerFieldset->get('email'));  // this defines the error?> 
							</div>
</div>
<div class="form-group">
							
								<?php echo $this->formLabel($customerFieldset->get('address1'))?> 
								
								<div class="col-md-9 col-sm-9 col-xs-12">
								<?php echo $this->formElement($customerFieldset->get('address1'));?>
									
								</div>
								<?php echo $this->formElementErrors($customerFieldset->get('address1'));  // this defines the error?> 
							</div>

<div class="form-group">
							
								 <?php echo $this->formLabel($customerFieldset->get('address2'))?> 
								
								<div class="col-md-9 col-sm-9 col-xs-12">
								<?php echo $this->formElement($customerFieldset->get('address2'));?>
									
								</div>
								<?php echo  $this->formElementErrors($customerFieldset->get('address2'));  // this defines the error?> 
							</div>

<div class="form-group">
							
								<?php echo $this->formLabel($customerFieldset->get('city'))?> 
								
								<div class="col-md-9 col-sm-9 col-xs-12">
								<?php echo $this->formElement($customerFieldset->get('city'));?>
									
								</div>
								<?php echo $this->formElementErrors($customerFieldset->get('city'));  // this defines the error?> 
							</div>

<div class="form-group">
							
								<?php echo $this->formLabel($customerFieldset->get('country'))?> 
								
								<div class="col-md-9 col-sm-9 col-xs-12">
								<?php echo $this->formElement($customerFieldset->get('country'));?>
									
								</div>
								<?php echo $this->formElementErrors($customerFieldset->get('country'));  // this defines the error?> 
							</div>

<div class="ln_solid"></div>