

<div class="col-md-12"></div>
<!-- <div class="row"> -->
<div class="col-sm-3 mail_list_column" style="background-color: #e1eeda">
	<div class="x_content">
		<table class="table table-hover">

			<tbody>
		<?php
if (count($data) > 0) {
    foreach ($data as $dat) {
        $dataJson = json_encode(array(
            "data" => $dat->getId()
        ));
        ?>
<tr>
					<td><strong><a data-ajax-loader="portal_info_loader"
							id="sending_data_button" class="ajax_element"
							data-json='{"data":"<?= $dat->getPortalUid()?>"}'
							data-href="<?php  echo $this->url("proposalmodal/default", array("action"=>"insurerportalinfo"));?>"><?php echo $dat->getEmail(); ?></a></strong></td>
				</tr>

<?php }}else{ echo "No Data Available";}?>

</tbody>
		</table>

	</div>
	<hr>
	<div style="text-align: center;">
		<i id="portal_info_loader" class="fa fa-lg"
			style="display: none; text-align: center;"><img alt=""
			src="<?php  echo $this->basepath("/processin.gif")?>" height=50>
			<hr></i>
	</div>
</div>
<!-- /MAIL LIST -->

<!-- CONTENT MAIL -->
<div class="col-sm-9 mail_view">
	<div class="inbox-body">
		<div class="mail_heading row" style="background-color: #eeebda">
			<div class="col-md-8">
				
			</div>
			<div class="col-md-4 text-right">
				<p class="date">8:02 PM 12 FEB 2014</p>
			</div>

			<div class="col-md-12">
				<div id="portal_info"  ></div>
			</div>


		</div>

	</div>
	
</div>
 <?php   echo $this->headLink()->appendStylesheet($this->basePath('css/custom.css'));?>