<?php
echo "{$data} is life ";
?>

<div class="row">


	<div class="col-md-6 col-sm-6 col-xs-12">



		<div class="row">

			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">

					<div class="x_content">
						<div class="dashboard-widget-content">



							<div class="col-md-12 col-sm-12 col-xs-12">
								<a style="width: 100%" class="btn btn-app" href=""><i
									class="fa fa-eye"></i>View Policy</a>
							</div>
							<div class="col-md-12 col-sm-12 col-xs-12">
								<a style="width: 100%" class="btn btn-app" href=""><i
									class="fa fa-comment"></i>Customer Message</a>
							</div>
							<div class="col-md-12 col-sm-12 col-xs-12">
								<a style="width: 100%" class="btn btn-app" href="">View Policy</a>
							</div>


						</div>
					</div>
				</div>
			</div>

		</div>

	</div>


	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">

				<div class="x_content">
					<div class="row">
						<div class="col-sm-12">
                          <?php  //echo $this->partial("general-dropzone-upload-form-snippet", array("dropZoneUploadForm"=>$dropZoneForm))?>
                        </div>
					</div>

				</div>
			</div>

		</div>
		<div class="x_panel">
			<div class="x_title">
				<h2>
					Recent Activities <small>Sessions</small>
				</h2>

				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<div class="dashboard-widget-content">

					<ul class="list-unstyled timeline widget top_profiles scroll-view">
						<li><div class="block">
								<div class="block_content">
									<h2 class="title">
										<a>Who Needs Sundance When Youve Got Crowdfunding</a>
									</h2>
									<div class="byline">
										<span>13 hours ago</span> by <a>Jane Smith</a>
									</div>
									<p class="excerpt">Film festivals used to be do-or-die moments
										for movie makers. They were where you met the producers that
										could fund your project, and if the buyers liked your flick,
										they d pay to Fast-forward and</p>
								</div>
							</div></li>

						<li><div class="block">
								<div class="block_content">
									<h2 class="title">
										<a>Who Needs Sundance When Youve Got Crowdfunding</a>
									</h2>
									<div class="byline">
										<span>13 hours ago</span> by <a>Jane Smith</a>
									</div>
									<p class="excerpt">Film festivals used to be do-or-die moments
										for movie makers. They were where you met the producers that
										could fund your project, and if the buyers liked your flick,
										they d pay to Fast-forward and</p>
								</div>
							</div></li>

						<li><div class="block">
								<div class="block_content">
									<h2 class="title">
										<a>Who Needs Sundance When Youve Got Crowdfunding</a>
									</h2>
									<div class="byline">
										<span>13 hours ago</span> by <a>Jane Smith</a>
									</div>
									<p class="excerpt">Film festivals used to be do-or-die moments
										for movie makers. They were where you met the producers that
										could fund your project, and if the buyers liked your flick,
										they d pay to Fast-forward and</p>
								</div>
							</div></li>

					</ul>
				</div>
			</div>
		</div>
	</div>



</div>

<div class="row">


	<!-- Start to do list -->
	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Uploaded Documents</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					<li class="dropdown"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown" role="button" aria-expanded="false"><i
							class="fa fa-wrench"></i></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="#">Settings 1</a></li>
							<li><a href="#">Settings 2</a></li>
						</ul></li>
					<li><a class="close-link"><i class="fa fa-close"></i></a></li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">

				<div class="">
                      <?php  //echo $this->policy_document_list($policyEntity)?>
                        <ul class="to_do">
						<li>
							<p>
								<input type="checkbox" class="flat"> Schedule meeting with new
								client
							</p>
						</li>

					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- End to do list -->

	<!-- start of weather widget -->
	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Uploader</h2>

				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<div class="row">
					<div class="col-sm-12">
                          <?php  //echo $this->partial("general-dropzone-upload-form-snippet", array("dropZoneUploadForm"=>$dropZoneForm))?>
                        </div>
				</div>

			</div>
		</div>

	</div>
	<!-- end of weather widget -->
</div>

<div class="row">


	<!-- Start to do list -->
	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Uploaded Documents</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					<li class="dropdown"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown" role="button" aria-expanded="false"><i
							class="fa fa-wrench"></i></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="#">Settings 1</a></li>
							<li><a href="#">Settings 2</a></li>
						</ul></li>
					<li><a class="close-link"><i class="fa fa-close"></i></a></li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">

				<div class="">
                      <?php  //echo $this->policy_document_list($policyEntity)?>
                        <ul class="to_do">
						<li>
							<p>
								<input type="checkbox" class="flat"> Schedule meeting with new
								client
							</p>
						</li>

					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- End to do list -->

	<!-- start of weather widget -->
	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Uploader</h2>

				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<div class="row">
					<div class="col-sm-12">
                          <?php  //echo $this->partial("general-dropzone-upload-form-snippet", array("dropZoneUploadForm"=>$dropZoneForm))?>
                        </div>
				</div>

			</div>
		</div>

	</div>
	<!-- end of weather widget -->
</div>

