<?php

?>

<table cellspacing="0" cellpadding="0"
											style="text-align: left !important; max-width: 480px; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											align="center" width="100%" bgcolor="#FFFFFF">
											<tbody>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td height="24"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td height="1" bgcolor="#DDDDDD"
														style="border-collapse: collapse;"></td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
											</tbody>
										</table>

										<table cellspacing="0" cellpadding="0"
											style="text-align: left !important; max-width: 480px; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											align="center" width="100%" bgcolor="#FFFFFF">
											<tbody>
												<tr>
													<td height="24"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td style="border-collapse: collapse;"><a
														href="https://support.vsco.co/hc/en-us"
														style="color: #000000;" target="_blank">Help Center</a><br>
														<br> <a href="https://vsco.co/about/terms_of_use"
														style="color: #000000;" target="_blank">Terms &amp;
															Conditions</a></td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
											</tbody>
										</table>