<?php

?>

<table cellspacing="0" cellpadding="0"
											style="text-align: left !important; max-width: 480px; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											align="center" width="100%" bgcolor="#FFFFFF">
											<tbody>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td colspan="6" height="48"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td align="left" valign="middle" width="52"
														style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse;">
														<a href="https://twitter.com/vsco" target="_blank"
														style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; color: #000000; display: block; width: 100%;">
															<img border="0"
															src="http://assets.vsco.co/assets/images/email/social_2/social_twitter.png"
															width="20" height="17" class="socialImage" alt="Twitter"
															style="-ms-interpolation-mode: bicubic; height: auto; outline-style: none; font-size: 14px; font-weight: bold; line-height: 100%; text-decoration: none; text-transform: capitalize; max-width: 24px; display: inline; outline: none; margin: 0 auto; border: 0 none;">
													</a>
													</td>
													<td align="left" valign="middle" width="52"
														style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse;">
														<a
														href="https://www.youtube.com/channel/UCVRgWg3gjoDO5KasrQoxMUw"
														target="_blank"
														style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; color: #000000; display: block; width: 100%;">
															<img border="0"
															src="http://assets.vsco.co/assets/images/email/social_2/social_youtube.png"
															width="22" height="17" class="socialImage" alt="YouTube"
															style="-ms-interpolation-mode: bicubic; height: auto; outline-style: none; font-size: 14px; font-weight: bold; line-height: 100%; text-decoration: none; text-transform: capitalize; max-width: 24px; display: inline; outline: none; margin: 0 auto; border: 0 none;">
													</a>
													</td>
													<td align="left" valign="middle" width="52"
														style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse;">
														<a href="https://instagram.com/vsco/" target="_blank"
														style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; color: #000000; display: block; width: 100%;">
															<img border="0"
															src="http://assets.vsco.co/assets/images/email/social_2/social_insta.png"
															width="22" height="22" class="socialImage"
															alt="Instagram"
															style="-ms-interpolation-mode: bicubic; height: auto; outline-style: none; font-size: 14px; font-weight: bold; line-height: 100%; text-decoration: none; text-transform: capitalize; max-width: 24px; display: inline; outline: none; margin: 0 auto; border: 0 none;">
													</a>
													</td>
													<td align="left" valign="middle" width="42"
														style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse;">
														<a href="https://www.facebook.com/VSCO" target="_blank"
														style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; color: #000000; display: block; width: 100%;">
															<img border="0"
															src="http://assets.vsco.co/assets/images/email/social_2/social_fb.png"
															width="10" height="22" class="socialImage" alt="Facebook"
															style="-ms-interpolation-mode: bicubic; outline-style: none; font-size: 14px; font-weight: bold; line-height: 100%; text-decoration: none; text-transform: capitalize; max-width: 22px; display: inline; outline: none; height: auto; margin: 0 auto; border: 0 none;">
													</a>
													</td>
													<td class="mobile-hide"
														style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse;">&nbsp;</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
											</tbody>
										</table>