<?php
?>


<?php
?>


<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width">


<style>
body {
	width: 100% !important;
	min-width: 100%;
	-webkit-text-size-adjust: 100%;
	-ms-text-size-adjust: 100%;
	margin: 0;
	padding: 0;
}

.ExternalClass {
	width: 100%;
}

.ExternalClass {
	line-height: 100%;
}

#backgroundTable {
	margin: 0;
	padding: 0;
	width: 100% !important;
	line-height: 100% !important;
}

img {
	outline: none;
	text-decoration: none;
	-ms-interpolation-mode: bicubic;
}

h1 a:active {
	color: #000000 !important;
}

h2 a:active {
	color: #000000 !important;
}

h3 a:active {
	color: #000000 !important;
}

h4 a:active {
	color: #000000 !important;
}

h5 a:active {
	color: #000000 !important;
}

h6 a:active {
	color: #000000 !important;
}

h1 a:visited {
	color: #000000 !important;
}

h2 a:visited {
	color: #000000 !important;
}

h3 a:visited {
	color: #000000 !important;
}

h4 a:visited {
	color: #000000 !important;
}

h5 a:visited {
	color: #000000 !important;
}

h6 a:visited {
	color: #000000 !important;
}

body {
	width: 100% !important;
	position: relative;
	margin: 0;
	padding: 0;
	-webkit-text-size-adjust: none;
}

img {
	border: none;
	font-size: 14px;
	font-weight: bold;
	height: auto;
	line-height: 100%;
	outline: none;
	text-decoration: none;
	text-transform: capitalize;
}

#backgroundTable {
	height: 100% !important;
	margin: 0;
	padding: 0;
	width: 100% !important;
}

body {
	background-color: #FFFFFF;
	font-size: 14px;
	line-height: 21px;
}

.bodyContent div a:visited {
	color: #AE995A;
	font-weight: normal;
	text-decoration: none;
}

.footerContent div a:visited {
	color: #AE995A;
	font-weight: normal;
	text-decoration: none;
}

@media only screen and (max-width:480px) {
	body {
		min-width: 100%;
	}
}
</style>
</head>

<body
	style="min-width: 100%; width: 100% !important; -webkit-text-size-adjust: none; -ms-text-size-adjust: 100%; position: relative; font-size: 14px; line-height: 21px; margin: 0; padding: 0;"
	bgcolor="#FFFFFF">
	<div
		style="max-height: 0; height: 0; visibility: hidden; display: none; font-size: 0;"></div>
	<center>
		<table align="center" border="0" cellpadding="0" cellspacing="0"
			width="100%"
			style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; border-collapse: collapse !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; height: 100% !important; width: 100% !important; margin: 0; padding: 0;">
			<tbody>
				<tr>
					<td align="center" valign="top" style="border-collapse: collapse;">
						<table border="0" cellpadding="0" cellspacing="0" width="100%"
							class="container"
							style="max-width: 480px; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
							bgcolor="#FFFFFF">
							<tbody>
								<tr>
									<td align="center" valign="top" class="main_content"
										style="border-collapse: collapse; font-family: -apple-system, BlinkMacSystemFont, 'Roboto', 'Droid Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;">

										<table cellspacing="0" cellpadding="0"
											style="text-align: left !important; max-width: 480px; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											align="center" width="100%" bgcolor="#FFFFFF">
											<tbody>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td height="48"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td align="left" height="24" valign="top"
														style="border-collapse: collapse;"><img height="24" width="120" src="<?= $brokerLogo  ?>"
														alt="Broker Logo"
														style="outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; font-size: 14px; font-weight: bold; height: auto; line-height: 100%; text-transform: capitalize; border: none;">
													</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td height="4"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td style="border-collapse: collapse;">
														<h2
															style="color: #343434; font-size: 18px; font-weight: 500; line-height: 27px; display: block; font-family: Helvetica, Arial, sans-serif; margin: 0px;"><?php echo $brokerName ?></h2>
													</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
											</tbody>
										</table>

										<table cellspacing="0" cellpadding="0"
											style="text-align: left !important; max-width: 480px; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											align="center" width="100%" bgcolor="#FFFFFF">
											<tbody>
												<tr>
													<td height="48"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td style="border-collapse: collapse;">Dear <?php echo $recipient?><br> <br>
														<?php echo $defaultText ; ?>

													</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td height="24"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<?php  echo ($invoiceTableTemplate == NULL ? "" : $invoiceTableTemplate);?>
											</tbody>
										</table>

										

										

										<?php echo $extraDetailTemplate == NULL ? "" : $extraDetailTemplate ?>

									</td>
								</tr>
								<tr id="templateFooter"
									style="max-width: 480px; border-top-width: 0; font-family: -apple-system, BlinkMacSystemFont, 'Roboto', 'Droid Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;"
									align="center">
									<td valign="top" align="center" class="footerContent"
										style="border-collapse: collapse;">

										<table cellspacing="0" cellpadding="0"
											style="text-align: left !important; max-width: 480px; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											align="center" width="100%" bgcolor="#FFFFFF">
											<tbody>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td height="80"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">

														<img
														src="https://api.mixpanel.com/track/?data=eyJwcm9wZXJ0aWVzIjp7ImNhbXBhaWduX2lkIjowLCJkaXN0aW5jdF9pZCI6IjMxMzE5OCIsIm1lc3NhZ2VfaWQiOjAsInRva2VuIjoiNzRmYzFkNDQ4MGY1NTRhZTcwZjQwZTRjZjcyNmE2NDgifSwidXNlcklkIjoiMzEzMTk4IiwiZXZlbnQiOiIkY2FtcGFpZ25fb3BlbiJ9&amp;ip=1&amp;img=1"
														width="1" height="1"
														style="outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; font-size: 14px; font-weight: bold; height: auto; line-height: 100%; text-transform: capitalize; display: inline; border: none;">

													</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td height="2" bgcolor="#000000"
														style="font-size: 0; line-height: 0; border-collapse: collapse;"></td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
											</tbody>
										</table>

										

										<?php echo ($socialMediaTemplate == NULL ? "" : $socialMediaTemplate)?>

										<table cellspacing="0" cellpadding="0"
											style="text-align: left !important; max-width: 480px; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											align="center" width="100%" bgcolor="#FFFFFF">
											<tbody>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td height="48"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td
														style="font-size: 0; line-height: 0; border-collapse: collapse;">

														<div
															style="color: #646464; font-size: 12px; font-weight: 300 !important; line-height: 12px; font-family: -apple-system, BlinkMacSystemFont, 'Roboto', 'Droid Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;"
															align="left">Powered By IMAPP</div>
													</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td height="8"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
												
												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td height="24"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>

												<tr>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
													<td height="24"
														style="font-size: 0; line-height: 0; border-collapse: collapse;">&nbsp;</td>
													<td width="24"
														style="width: 24px; line-height: 0px; font-size: 0px; border-collapse: collapse;">&nbsp;</td>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
							</tbody>
						</table>
					</td>
				</tr>
			</tbody>
		</table>
	</center>

</body>












