<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Policy\Module' => __DIR__ . '/Module.php',
    'Policy\Controller\IndexController' => __DIR__ . '/src/Policy/Controller/IndexController.php',
    'PolicyTest\Framework\TestCase' => __DIR__ . '/tests/Policy/Framework/TestCase.php',
    'PolicyTest\SampleTest' => __DIR__ . '/tests/Policy/SampleTest.php'
);
