<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Offer\Module' => __DIR__ . '/Module.php',
    'Offer\Controller\IndexController' => __DIR__ . '/src/Offer/Controller/IndexController.php',
    'OfferTest\Framework\TestCase' => __DIR__ . '/tests/Offer/Framework/TestCase.php',
    'OfferTest\SampleTest' => __DIR__ . '/tests/Offer/SampleTest.php'
);
