<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Analytics\Module'                        => __DIR__ . '/Module.php',
    'Analytics\Controller\AnalyticsController' => __DIR__ . '/src/Analytics/Controller/AnalyticsController.php',
    'AnalyticsTest\Framework\TestCase'        => __DIR__ . '/tests/Analytics/Framework/TestCase.php',
    'AnalyticsTest\SampleTest'                => __DIR__ . '/tests/Analytics/SampleTest.php',
);
