
<?php
echo $this->headtitle("All Policy");

$policy = $this->policy;

?>

<div id="wasabi_modal"></div>
<div class="row">
 
</div>
<div class="row">


	<div class="col-md-9 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>My Policy</h2>
				
				<div class="clearfix"></div>
			</div>
                  <?php  echo $this->partial("general-error-ponters")?>
                  <div class="x_content">

				<!--                     <p>Simple table with project listing with progress and editing options</p> -->

				<!-- start project list -->
				<div class="table-responsive">
					<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    
						<thead>
							<tr>
								<th>ID</th>
								<th>Customer Details</th>
								<th>Policy Details</th>

								<th>Action</th>
							</tr>
						</thead>
						<tbody>
                    <?php  
//                     print_r($policy);                   
                    echo $this->partial("policy-list-policy-snipet", array("policy"=>$policy));
                    ?>
                    </tbody>
					</table>
				</div>

				<!-- end project list -->

			</div>
		</div>
	</div>
	<div class="col-md-3 col-xs-12">

		<div class="x_panel">

			<div class="x_content">
				<img alt="" style='width: 100%;'
					src="<?php echo $this->basepath("imappadd/banner2.jpg")?>">
			</div>
		</div>
	</div>
</div>

<?php  echo $this->headLink()->appendStylesheet('/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'); ?>

<script
	src="<?php echo $this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/buttons.flash.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-scroller/js/datatables.scroller.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/jszip/dist/jszip.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/pdfmake/build/pdfmake.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/pdfmake/build/vfs_fonts.js') ?>"></script>
<?php  //echo $this->partial("general-datable-script")?>

<?php
?>
<script>
      $(document).ready(function() {
        var handleDataTableButtons = function() {
          if ($("#datatable-buttons").length) {
            $("#datatable-buttons").DataTable({
              dom: "Bfrtip",
              buttons: [
                {
                  extend: "copy",
                  className: "btn-sm"
                },
                {
                  extend: "csv",
                  className: "btn-sm"
                },
                {
                  extend: "excel",
                  className: "btn-sm"
                },
                {
                  extend: "pdfHtml5",
                  className: "btn-sm"
                },
                {
                  extend: "print",
                  className: "btn-sm"
                },
              ],
              responsive: true
            });
          }
        };

        TableManageButtons = function() {
          "use strict";
          return {
            init: function() {
              handleDataTableButtons();
            }
          };
        }();

        $('#datatable').DataTable({
    		ordering: false
    });

        $('#datatable-keytable').DataTable({
          keys: true
        });

        $('#datatable-responsive').DataTable();

        $('#datatable-scroller').DataTable({
          ajax: "js/datatables/json/scroller-demo.json",
          deferRender: true,
          scrollY: 380,
          scrollCollapse: true,
          scroller: true
        });

        $('#datatable-fixed-header').DataTable({
          fixedHeader: true
        });

        var $datatable = $('#datatable-checkbox');

        $datatable.dataTable({
          'order': [[ 1, 'desc' ]],
          'columnDefs': [
            { orderable: false, targets: [0] }
          ]
        });
        $datatable.on('draw.dt', function() {
          $('input').iCheck({
            checkboxClass: 'icheckbox_flat-green'
          });
        });

        TableManageButtons.init();
      });
    </script>