<?php
use GeneralServicer\Service\GeneralService;

echo $this->headTitle("Unpublished Policy");

?>

<div id="wasabi_modal"></div>
<div class="row">
	
	
	<div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Unpublished Policy</h2>
                   
                    <div class="clearfix"></div>
                  </div>
                  <?php  echo $this->partial("general-error-ponters")?>
                  <div class="x_content">
                    
                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                      <thead>
                        <tr>
                        <th></th>
                          <th>Policy Details</th>
<!--                           <th>Cover Note</th> -->
                          <th>Customer</th>
                          <th> </th>
<!--                           <th>Age</th> -->
<!--                           <th>Start date</th> -->
<!--                           <th>Salary</th> -->
<!--                           <th>Extn.</th> -->
<!--                           <th>E-mail</th> -->


                        </tr>
                      </thead>
                      <tbody>
                      <?php if(count($all) == 0){ echo "No unpublished policy yet";}else{
                          foreach ($all as $unPolicy){
                          ?>
                        <tr>
                          <td></td>
                          <td>
                          
                          <?php echo ($unPolicy->getPolicyFloatUid() != NULL ? strtoupper($unPolicy->getPolicyFloatUid()) : GeneralService::GENERAL_EMPTY_FIELD)?><br>
                          <strong>Policy Name :</strong>  <?php echo ($unPolicy->getFloatName() != NULL ? strtoupper($unPolicy->getFloatName()) : GeneralService::GENERAL_EMPTY_FIELD)?><br>
                          <strong>Cover Start Date :</strong> <?php  echo ($unPolicy->getPolicyStartDate() != NULL ? $this->dateformat($unPolicy->getPolicyStartDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE,'en_US'): GeneralService::GENERAL_EMPTY_FIELD)?><br>
                         <strong>Cover End Date :</strong> <?php  echo ($unPolicy->getPolicyEndDate() != NULL ? $this->dateformat($unPolicy->getPolicyEndDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE,'en_US'): GeneralService::GENERAL_EMPTY_FIELD)?><br>
                          </td>
<!--                           <td>System Architect</td> -->
                          <td><?php 
                          $customerEntity = $unPolicy->getCoverNote()->getCustomer(); ?>
                          <strong>Customer Name: </strong> <?php echo ($customerEntity->getName() != NULL ? $this->escapehtml($customerEntity->getName()) : GeneralService::GENERAL_EMPTY_FIELD)?><br>
                          <strong>Phone: </strong><?php echo ($customerEntity->getUser() != NULL ? $this->escapehtml($customerEntity->getUser()->getUsername()) : GeneralService::GENERAL_EMPTY_FIELD)?><br>
                          </td>
                          <td><a href="<?php  echo $this->url("policy/default", array("action"=>"floatmanager", "id"=>$unPolicy->getPolicyFloatUid()))?>" class="btn btn-xs btn-success" style="width: 100%"><i class="fa fa-eye"></i></a></td>
<!--                           <td>2011/04/25</td> -->
<!--                           <td>$320,800</td> -->
<!--                           <td>5421</td> -->
<!--                           <td>t.nixon@datatables.net</td> -->
                        </tr>
                        <?php }}?>
                      </tbody>
                    </table>

                  </div>
                </div>
              </div>
              
              
</div>

<?php  echo $this->headLink()->appendStylesheet('/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'); ?>

<script
	src="<?php echo $this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/buttons.flash.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-scroller/js/datatables.scroller.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/jszip/dist/jszip.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/pdfmake/build/pdfmake.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/pdfmake/build/vfs_fonts.js') ?>"></script>
	
<?php  echo $this->partial("general-datable-script")?>