<?php


use Transactions\Service\InvoiceService;

?>
<style>
    .invoice-box{
        max-width:800px;
        margin:auto;
        padding:30px;
        border:1px solid #eee;
        box-shadow:0 0 10px rgba(0, 0, 0, .15);
        font-size:16px;
        line-height:24px;
        font-family:'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color:#555;
    }
    
    .invoice-box table{
        width:100%;
        line-height:inherit;
        text-align:left;
    }
    
    .invoice-box table td{
        padding:5px;
        vertical-align:top;
    }
	.invoice-box table tr td{
        
    }
    
    .invoice-box table tr td:nth-child(2){
        text-align:right;
    }
    
    .invoice-box table tr.top table td{
        padding-bottom:20px;
    }
    
    .invoice-box table tr.top table td.title{
        font-size:45px;
        line-height:45px;
        color:#333;
    }
    
    .invoice-box table tr.information table td{
        padding-bottom:40px;
    }
    
    .invoice-box table tr.heading td{
        background:#eee;
        border-bottom:1px solid #ddd;
        font-weight:bold;
		
    }
	
	.invoice-box table tr.heading td.des{
       
		text-align:left;
    }
    
    .invoice-box table tr.details td{
        padding-bottom:20px;
		
    }
    
    .invoice-box table tr.item td.des{
        border-bottom:1px solid #eee;
		text-align:left;;
    }
    
    .invoice-box table tr.item.last td{
        border-bottom:none;
    }
    
    .invoice-box table tr.total td:nth-child(2){
        border-top:2px solid #eee;
        font-weight:bold;
    }
    
    @media only screen and (max-width: 600px) {
        .invoice-box table tr.top table td{
            width:100%;
            display:block;
            text-align:center;
        }
        
        .invoice-box table tr.information table td{
            width:100%;
            display:block;
            text-align:center;
        }
    }
    </style>
    
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">
                               <img
					alt="<?php echo $this->customer_broker_name_helper()." Logo"?>"
					src="<?php  echo $this->customer_broker_logo_helper()?>" height=75> </td>
                            
                            <td>
                                Invoice #: <?php  echo strtoupper($invoiceEntity->getInvoiceUid()) ?><br>
                                Created: <?php echo $this->dateFormat($invoiceEntity->getGeneratedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_US")?><br>
                                Due: <?php echo $this->dateFormat($invoiceEntity->getExpiryDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_US")?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                               <?php  echo $invoiceEntity->getCustomer()->getCustomerBroker()->getBroker()->getBrokerName() ?><br>
                                <?php  echo $invoiceEntity->getCustomer()->getCustomerBroker()->getBroker()->getBrokerAddress() ?><br>
                               
                            </td>
                            
                            <td>
                                Customer Name: <?php echo $invoiceEntity->getCustomer()->getName() ?><br>
                                Phone: <?php  echo $invoiceEntity->getCustomer()->getUser()->getUserName() ?><br>
                               Email: <?php  echo $invoiceEntity->getCustomer()->getUser()->getEmail() ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            
            
           
            
            <tr class="heading">
                <td>
                   Service
                </td>
				<td class="des">
                  Description
                </td>
                
                <td>
                    Price
                </td>
            </tr>
            
            <tr class="item">
                <td>
                 <br>
                    <?php  echo $invoiceEntity->getInvoiceCategory()->getCategory() ;?>
                </td>
                <td  class="des"> <br> </td>
                <td>
                <br>
                   <?php echo $this->myCurrencyFormat($invoiceEntity->getAmount(), $invoiceEntity->getCurrency()->getCode()) ?>
                </td>
            </tr>
            
            
            
            
            
            <tr class="total">
                <td></td>
                
                <td>
				<br><br>
                   Total: <?php echo $this->myCurrencyFormat($invoiceEntity->getAmount(), $invoiceEntity->getCurrency()->getCode()) ?>
                </td>
            </tr>
        </table>
        <br>
        <?php  if ($invoiceEntity->getStatus()->getId() == InvoiceService::INVOICE_PAID_STATUS){?>
        <span class="label label-success" style="width: 100%;">Fully Paid</span>
        <?php }else{?>
        <a href="<?php  echo $this->url("board/default", array("action"=>"payment"))?>" style="width: 100%;" class="btn btn-lg btn-primary">PAY NOW</a>
    <?php }?>
    </div>
    
    