<?php

if($invoices != NULL){
   foreach ($invoices as $invoice) {
?>

<tr>
                 
                  <td>
                  <?php echo strtoupper($invoice->getInvoiceUid())?><br>
                  <?php echo $invoice->getInvoiceCategory()->getCategory()?><br>
                 <div class="text-light"> Generated On:<?php echo $this->dateFormat($invoice->getGeneratedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_US")?></div><br>
                  </td>
                  
                  <td><?php echo $this->statusHelper($invoice->getStatus()->getStatus()) ?></td>
                  <td><?php echo $this->myCurrencyFormat($invoice->getAmount(), $invoice->getCurrency()->getCode()) ?></td>
                  <td><a class="btn btn-success btn-xs" href="<?php  echo $this->url("cus_invoice/default", array("action"=>"view","id"=>$invoice->getInvoiceUid()))?>"><i class="fa fa-eye"></i> View</a></td>
                </tr>
                
                <?php  }}?>