<?php

?>
<?php foreach ($pack as $package){?>

				<div class="col-md-6 col-sm-12 col-xs-12">
                          <div class="pricing">
                            <div class="title">
                             <h2><?php  echo $this->escapehtml($package->getPackageName());?></h2>
                              <h1><?php echo $this->myCurrencyFormat($package->getPrice(), 'NGN', null, 'en_NG'); ?> </h1>
									 
									 <div class="x_content">
                              <div class="">
                                <div class="pricing_features">
                                  <ul class="list-unstyled text-left">
                                    <li><i class="fa fa-times text-danger"></i><strong>Max No. of Employees:</strong> <?php echo $this->escapehtml($package->getMaxEmployee()); ?></li>
                                    <li><i class="fa fa-times text-danger"></i> <strong>Unlimited</strong> storage</li>
                                    <li><i class="fa fa-check text-success"></i> Limited <strong> download quota</strong></li>
                                    <li><i class="fa fa-check text-success"></i> <strong>Cash on Delivery</strong></li>
                                    <li><i class="fa fa-check text-success"></i> All time <strong> updates</strong></li>
                                    <li><i class="fa fa-times text-danger"></i> <strong>Unlimited</strong> access to all files</li>
                                    <li><i class="fa fa-times text-danger"></i> <strong>Allowed</strong> to be exclusing per sale</li>
                                  </ul>
                                </div>
                              </div>
<!--                               <div class="pricing_footer"> -->
<!--                                 <a href="javascript:void(0);" class="btn btn-success btn-block" role="button">Download <span> now!</span></a> -->
<!--                                 <p> -->
<!--                                   <a href="javascript:void(0);">Sign up</a> -->
<!--                                 </p> -->
<!--                               </div> -->
                            </div>
								</div>
							
									
								
						
						</div>
					</div>

					<?php }?>
