<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Json\Module'                        => __DIR__ . '/Module.php',
    'Json\Controller\PackageController' => __DIR__ . '/src/Json/Controller/PackageController.php',
    'JsonTest\Framework\TestCase'        => __DIR__ . '/tests/Json/Framework/TestCase.php',
    'JsonTest\SampleTest'                => __DIR__ . '/tests/Json/SampleTest.php',
);
