<?php
$this->headtitle('Term Acceptance');
$info = $this->info;
$form = $this->setUpForm;
$form->prepare();

?>

<div class="row" ng-app></div>


<div class="row">

	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Agent Setup Form</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					
				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
			<?php echo $this->form()->openTag($form);?>
			
			<?php  echo  $this->partial('setup-info-snipet', array('info'=>$info, 'form'=>$form));?>
                                    
                <hr>	
					<?php echo  $this->formelement($form->get('csrf'))?>
					<?php  echo $this->formSubmit($form->get('submit'))?>
					
					<?php  echo $this->form()->closeTag();?>                    
                                    			</div>
		</div>
	</div>

</div>