<?php
$profileForm = $this->profileForm;
$profileForm->setAttribute('action', $this->url('user_ind', array(
    'action' => 'set-profile'
)));
$profileForm->prepare();
?>
<div class="row" ng-app></div>


<div class="row">
	<div class="col-md-6 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>
					Users Profile <small>Please complete your profile </small>
				</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<br />
				<?php echo $this->form()->openTag($profileForm);?>
				 <?php $setupProfileField = $profileForm->get('ind_fieldset')?>
				

					<div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
						<?php  echo  $this->formElement($setupProfileField->get('firstname'));?> <span
						class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
							<?php  echo  $this->formElementErrors($setupProfileField->get('firstname'));?>
					</div>

				<div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
						<?php  echo  $this->formElement($setupProfileField->get('lastname'));?> <span
						class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
						<?php  echo  $this->formElementErrors($setupProfileField->get('lastname'));?>
				</div>

				<div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
						<?php  echo  $this->formElement($setupProfileField->get('othername'));?>  <span
						class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
						<?php  echo  $this->formElementErrors($setupProfileField->get('othername'));?>
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
					<input type="text" class="form-control" disabled="disabled"
						placeholder="Disabled">
				</div>



				<div class="form-group">
						<?php  echo  $this->formLabel($setupProfileField->get('dob'));?>
						<div class="col-md-9 col-sm-9 col-xs-12">
							<?php  echo  $this->formElement($setupProfileField->get('dob'));?>  
						</div>
						<?php  echo  $this->formElementErrors($setupProfileField->get('dob'));?>
				</div>

				<div class="form-group">
						<?php  echo  $this->formLabel($setupProfileField->get('gender'));?>
						<div class="col-md-9 col-sm-9 col-xs-12">
							<?php  echo  $this->formElement($setupProfileField->get('gender'));?>  
						</div>
						<?php  echo  $this->formElementErrors($setupProfileField->get('gender'));?>
					</div>


				<div class="ln_solid"></div>
					<?php $setupContactField = $setupProfileField->get('contact')?>
					<div class="form-group">
						<?php  echo  $this->formLabel($setupContactField->get('address1'));?>
						<div class="col-md-9 col-sm-9 col-xs-12">
							<?php  echo  $this->formElement($setupContactField->get('address1'));?> 
						</div>
						<?php  echo  $this->formElementErrors($setupContactField->get('address1'));?>
					</div>

				<div class="form-group">
						<?php  echo  $this->formLabel($setupContactField->get('address2'));?>
						<div class="col-md-9 col-sm-9 col-xs-12">
							<?php  echo  $this->formElement($setupContactField->get('address2'));?> 
						</div>
						<?php  echo  $this->formElementErrors($setupContactField->get('address2'));?>
					</div>

				<div class="form-group">
						<?php  echo  $this->formLabel($setupContactField->get('stateProvince'));?>
						<div class="col-md-9 col-sm-9 col-xs-12">
							<?php  echo  $this->formElement($setupContactField->get('stateProvince'));?> 
						</div>
						<?php  echo  $this->formElementErrors($setupContactField->get('stateProvince'));?>
					</div>

				<div class="form-group">
						<?php  echo  $this->formLabel($setupContactField->get('city'));?>
						<div class="col-md-9 col-sm-9 col-xs-12">
							<?php  echo  $this->formElement($setupContactField->get('city'));?> 
						</div>
						<?php  echo  $this->formElementErrors($setupContactField->get('city'));?>
					</div>

				<div class="form-group">
						<?php  echo  $this->formLabel($setupContactField->get('postalCode'));?>
						<div class="col-md-9 col-sm-9 col-xs-12">
							<?php  echo  $this->formElement($setupContactField->get('postalCode'));?> 
						</div>
						<?php  echo  $this->formElementErrors($setupContactField->get('postalCode'));?>
					</div>

				<div class="form-group">
						<?php  echo  $this->formLabel($setupContactField->get('phoneNumber1'));?>
						<div class="col-md-9 col-sm-9 col-xs-12">
							<?php  echo  $this->formElement($setupContactField->get('phoneNumber1'));?> 
						</div>
						<?php  echo  $this->formElementErrors($setupContactField->get('phoneNumber1'));?>
					</div>

				<div class="ln_solid"></div>
				<div class="form-group">
					<div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
					<?php echo $this->formsubmit($profileForm->get('reset'))?>
					<?php echo $this->formsubmit($profileForm->get('submit'))?>
						
					</div>
				</div>

				<?php echo  $this->formRow($form->get('csrf')); echo $this->form()->closeTag(); ?>
			</div>
		</div>







	</div>

	<div class="col-md-6 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<div class="clearfix"></div>



			</div>
			<div class="x_content">
				<img src="<?= $this->basePath();?>/images/ban1.jpg">
			</div>
		</div>
	</div>



</div>