<?php
echo $this->headtitle("Complete Property Information");
$objectForm->prepare();
$objectForm->get("submit")->setAttributes(array(
    "value" => "UPDATE"
));
?>
<style>
.thumbnail {
	display: inline-block;
	margin: 10px auto;
	width: 300px;
}

.thumbnail, .progress, #error {
	display: none;
}
</style>
<div class="row">
	<div class="col-md-9">
		<div class="page-section padding-top-none">
			<div class="media v-middle">
				<div class="media-body">
					<h1 class="text-display-1 margin-none">Update Property Information</h1>
				</div>

			</div>
		</div>
		<div class="panel panel-default">
			<br>
		<?php  echo $this->form()->openTag($objectForm)?>
		
		<?php
echo $this->objectCompleteObjectPartialFormViewHelper($objectEntity, $objectForm);
echo $this->formsubmit($objectForm->get('submit'));
?>
			
			<?php  echo $this->form()->closeTag() ?>
		</div>
	</div>

	<div class="item col-xs-12 col-lg-3 col-md-3">
		<div class="panel panel-default paper-shadow" data-z="0.5">
			<div class="panel-body">
				
                  <?php
                
// $uploadForm->prepare();
//                 $uploadForm->setAttributes(array(
//                     "action" => "/my/property/upload"
//                 ));
//                 echo $this->form()->openTag($uploadForm);
//                 echo $this->formelement($uploadForm->get("file"));
//                 ?>
<!--                   <hr> -->
                  <?php
//                 echo $this->formsubmit($uploadForm->get("upload"));
//                 echo $this->form()->closeTag();
//                 ?>
<?php  echo $this->partial("general-dropzone-upload-form-snippet", array("dropZoneUploadForm"=>$dropZoneForm))?>
                 
				<br>
				

			</div>
		</div>
		<div class="panel panel-default paper-shadow" data-z="0.5">
			<div class="panel-heading">
				<h3>Uploaded Document</h3>
			</div>
			<div class="panel-body">
                  <?php  echo $this->customerObjectUploadedDocHelper($objectEntity->getDocument())?>
                </div>
		</div>
	</div>

</div>
<?php  echo $this->headScript()->appendFile($this->basePath('/fileupload/script.js')); ?>

<script type="text/javascript">


        $(document).ready(function () {
//         	$("#isTemredValue").hide();
//         		$('#ajaxStatus')
//         		.ajaxStart(function() {
//         		$(this).show();
//         		})
//         		.ajaxStop(function() {
//         		$(this).hide();
//         		});
            // $('.money').mask('000,000,000,000,000.0', {reverse: true});
//             $('.phone').mask('0-000-000-0000');
            $("#country_id").change(function(){
//                 alert("The index chosen is ");
               //$("#pack_cover").val(303);
                $.ajax({
                    type:"POST",
                    data: { 
                        'service':$("#country_id").val() , 
//                         'ca$libri': 'no$libri' // <-- the $ sign in the parameter name seems unusual, I would avoid it
                    },
                    url:"/general/state",
                    dataType:"html",
                    success:function(data, status){
                        $("#state_id").html(data)
                    },
                    error:function(){
                        alert("we could not retrive the State/Territory list")
                    }
                })
            	//$("#pack_cover").html("<option value='303'>PUM PUM </option>");
            })
            

//             if($("#coverduration").val() == "100"){
//               	 $("#isTemredValue").show();
//                }else{
//               	 $("#isTemredValue").hide();
//                }

//             $("#coverduration").change(function(){
// 				if($("#coverduration").val() == "100"){
// 					$("#isTemredValue").show();
// 				}else{
// 					$("#isTemredValue").hide();
// 				}
// 			});
           

        });

       

        

        
    

</script>
