<?php
$invoices = $this->unpublishedPolicy;
$currentDate = new DateTime();
$count = (count($invoices) < 10 ? count($invoices) : 10);
?>


<div class="col-md-4 col-sm-12   col-xs-12 ">
	<div class="x_panel">
		<div class="x_title">
			<h2>Unpublished Policy</h2>
			<ul class="nav navbar-right panel_toolbox">
				<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="x_content">
                  <?php
                
                if ($invoices == NULL) {
                    echo "No Unpublished Policy
                 ";
                } else {
                    ?>
                  <ul class="list-unstyled top_profiles scroll-view">
                          <?php for($i=0; $i < $count ; $i++){?>
                          <li class="media event"><a
					class="pull-left border-green profile_thumb"> <i
						class="fa fa-edit green"></i>
				</a>
					<div class="media-body">
						<a class="title"
							href="<?php  echo $this->url('policy/default', array('action'=>'floatmanager', 'id'=>$invoices[$i]->getPolicyFloatUid()));?>"> <?php echo strtoupper($invoices[$i]->getPolicyFloatUid())?></a>
						

						<p>
							<small><?php  echo $this->dateFormat($invoices[$i]->getCreatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, 'en_US') ?></small>
						</p>
					</div></li>
                          <?php }?>
                          
                       
                        <?php }?>
                         </ul>
		</div>
	</div>
</div>