<?php
use CsnUser\Service\UserService;

echo $this->headtitle('Registered Customer');
$customer = $this->customer;
$flashMessenger = $this->flashMessenger()
->setMessageOpenFormat("<div%s>
     <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>
         &times;
     </button>
     <ul><li style='color: red'>")
     ->setMessageSeparatorString("</li><li>")
     ->setMessageCloseString('</li></ul></div>');
// echo $this->headLink()->appendStylesheet('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css');
// echo $this->headLink()->appendStylesheet('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css');
// echo $this->headLink()->appendStylesheet('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css');
// echo $this->headLink()->appendStylesheet('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css');
// echo $this->headLink()->appendStylesheet('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css');
?>
<div id="wasabi_modal"></div>
<div id="wasabi_modal_view"></div>
<div class="row">

	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>
					My Customers
				</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					
					
				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
			<?php echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger')); ?>
 <?php echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info')); ?>
 <?php echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning')); ?>
 <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
				<p class="text-muted font-13 m-b-30">This show a list of all customers you registered or are assigned to you </p> 
				
				<div class="table-responsive">
				  <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                   
					<thead>
						<tr>
						<th>#</th>
							<th>CUSTOMER</th>
							<th style="width: 15%"> </th>
							
<!-- 							<th>Start date</th> -->
<!-- 							<th>Salary</th> -->
<!-- 							<th>Extn.</th> -->
							<th style="width: 15%"></th>
						</tr>
					</thead>
					<tbody>
						<?php  echo $this->partial('customer-list-snipet', array('customer'=>$customer))?>
					</tbody>
				</table>
				</div>

			</div>
		</div>
	</div>
</div>

<?php  echo $this->headLink()->appendStylesheet('/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'); ?>

<script
	src="<?php echo $this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/buttons.flash.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-scroller/js/datatables.scroller.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/jszip/dist/jszip.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/pdfmake/build/pdfmake.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/pdfmake/build/vfs_fonts.js') ?>"></script>
	
	
	<?php  echo $this->partial("general-datable-script")?>