<?php
use GeneralServicer\Service\GeneralService;

echo $this->headtitle("Customer Objects");

?>
<div class="row">
<?php  echo $this->partial("general-error-ponters")?>
	<div class="col-md-9 col-sm-9 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2><?php  echo $customer->getName()?> Object(s)</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<div class="table-responsive">
					<table id="datatable" class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>Object</th>
								<th>Status</th>
								<th>Action</th>

							</tr>
						</thead>


						<tbody>
	<?php

if (count($objects) == 0) {
    echo "<span>No Objects Registered</span>";
} else {
    
    for ($i = 0; $i < count($objects); $i ++) {

        ?>
	<tr>
								<td><a
									href="<?php echo $this->url("object/default", array("action"=>"view", "inf"=>$objects[$i]->getId()))?>"><?php  echo strtoupper(($objects[$i]->getObjectUid() != NULL ? $objects[$i]->getObjectUid() : " No UID"))?></a><br>
		<?php echo ($objects[$i]->getObjectName() == NULL ? "": $objects[$i]->getObjectName())?> <br>
									<strong>Crrated On: </strong><?php echo ($objects[$i]->getCreatedOn() != NULL ? $this->dateFormat($objects[$i]->getCreatedOn(), IntlDateFormatter::FULL, IntlDateFormatter::NONE, "en_us") : GeneralService::GENERAL_EMPTY_FIELD)?></strong>
			
			</td>
								<td><?php  echo $this->customerAllObjectStatus($objects[$i])?></td>
								<td><a data-toggle='tooltip' data-placement='top'
									title='View Property'
									href="<?php  echo $this->url("object/default", array("action"=>"view", "inf"=>$objects[$i]->getObjectUid()))?>"
									title="View Property" alt="View Property"
									class="btn btn-warning btn-xs"><i class="fa fa-eye"></i></a> <a
									href="<?php  //echo $this->url("object/default", array("action"=>"delete", "id"=>$objects[$i]->getId()))?>"
									data-toggle='tooltip' data-placement='top'
									title='Delete Property' class="btn btn-danger btn-xs"><i
										class="fa fa-trash"></i></a></td>

							</tr>
	<?php
    }
    
}
?>
		
		
	</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3 col-xs-12">

		<div class="x_panel">

			<div class="x_content">
				<img alt="" style='width: 100%;'
					src="<?php echo $this->basepath("imappadd/banner1.jpg")?>">
			</div>
		</div>
	</div>


</div>

<?php  echo $this->headLink()->appendStylesheet('/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'); ?>

<script
	src="<?php echo $this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/buttons.flash.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/datatables.net-scroller/js/datatables.scroller.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/jszip/dist/jszip.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/pdfmake/build/pdfmake.min.js') ?>"></script>
<script
	src="<?php //echo $this->basePath('vendors/pdfmake/build/vfs_fonts.js') ?>"></script>


<?php  echo $this->partial("general-datable-script")?>
