<?php
use CsnUser\Service\UserService;

echo $this->headtitle('Mother Broker Customer');
$customer = $this->customer;
echo $this->headLink()->appendStylesheet('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css');
echo $this->headLink()->appendStylesheet('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css');
echo $this->headLink()->appendStylesheet('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css');
echo $this->headLink()->appendStylesheet('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css');
echo $this->headLink()->appendStylesheet('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css');
?>
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>
					Mother Broker Customers
				</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					
					
				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
			
				<p class="text-muted font-13 m-b-30">This show a list of all customers you registered or are assigned to you </p> 
				<?php if ($this->identity()->getRole()->getId() == UserService::USER_ROLE_BROKER_CHILD){?>
				<a class=" btn btn-round btn-primary" href="<?php echo $this->url('customer/default', array('action'=>'mother-broker'))?>">Click to View The Company Customers</a>
				<?php }?>
				<div class="table-responsive">
				<table id="datatable" class="table table-striped table-bordered">
					<thead>
						<tr>
							<th>Account Number</th>
							<th>Customer Name</th>
							<th>Type</th>
							<th>Phone Number</th>
							<th>Email</th>
<!-- 							<th>Start date</th> -->
<!-- 							<th>Salary</th> -->
<!-- 							<th>Extn.</th> -->
							<th style="width: 15%"></th>
						</tr>
					</thead>
					<tbody>
						<?php  echo $this->partial('customer-mother-broker-snipet', array('customer'=>$customer))?>
					</tbody>
				</table>
				</div>

			</div>
		</div>
	</div>
</div>

<?php
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-buttons/js/buttons.flash.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/datatables.net-scroller/js/datatables.scroller.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/jszip/dist/jszip.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/pdfmake/build/pdfmake.min.js'));
echo $this->inlineScript()->appendFile($this->basePath('vendors/pdfmake/build/vfs_fonts.js'));

?>
<script>
      $(document).ready(function() {
        var handleDataTableButtons = function() {
          if ($("#datatable-buttons").length) {
            $("#datatable-buttons").DataTable({
              dom: "Bfrtip",
              buttons: [
                {
                  extend: "copy",
                  className: "btn-sm"
                },
                {
                  extend: "csv",
                  className: "btn-sm"
                },
                {
                  extend: "excel",
                  className: "btn-sm"
                },
                {
                  extend: "pdfHtml5",
                  className: "btn-sm"
                },
                {
                  extend: "print",
                  className: "btn-sm"
                },
              ],
              responsive: true
            });
          }
        };

        TableManageButtons = function() {
          "use strict";
          return {
            init: function() {
              handleDataTableButtons();
            }
          };
        }();

        $('#datatable').dataTable();

        $('#datatable-keytable').DataTable({
          keys: true
        });

        $('#datatable-responsive').DataTable();

        $('#datatable-scroller').DataTable({
          ajax: "js/datatables/json/scroller-demo.json",
          deferRender: true,
          scrollY: 380,
          scrollCollapse: true,
          scroller: true
        });

        $('#datatable-fixed-header').DataTable({
          fixedHeader: true
        });

        var $datatable = $('#datatable-checkbox');

        $datatable.dataTable({
          'order': [[ 1, 'asc' ]],
          'columnDefs': [
            { orderable: false, targets: [0] }
          ]
        });
        $datatable.on('draw.dt', function() {
          $('input').iCheck({
            checkboxClass: 'icheckbox_flat-green'
          });
        });

        TableManageButtons.init();
      });
    </script>