<?php
echo $this->headtitle("New Customer ");
$customerForm = $this->customerForm;
$myCustomers = $this->myCustomers;
$customerForm->prepare();
$flashMessenger = $this->flashMessenger()
    ->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');
?>
<div class="row" ng-app="CustomerModule">
	<div class="col-md-9 col-sm-9 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>New Customer</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<!-- Enter the view helper heere -->
				<?php echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger')); ?>
 <?php echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info')); ?>
 <?php echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning')); ?>
 <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>

<?php

echo $this->form()->openTag($customerForm);
$customerFieldset = $customerForm->get('customerFieldset');
// $objectMotorData = $objectField->get('objectMotor');
// $objectHouseData = $objectField->get('objectHouse');
?>

	
				
				
				<div class="checkbox">
					<label>
								<?php echo $this->formElement($customerForm->get('individual'));?>
								
								 </label>
								 
				</div>



			<br>

				
<?php echo $this->partial('customer-new', array('customerFieldset'=>$customerFieldset))?>
				
			
<div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-10">

				
				<?php
    echo $this->formRow($customerForm->get('csrf'));
    echo $this->formRow($customerForm->get('submit'));
    // echo $this->formRow($customerForm->get('reset'));
    echo $this->form()->closeTag();
    ?>
    </div>

			</div>
		</div>
	</div>
	<div class="col-md-3 col-sm-12 col-xs-12">
		<div>
			<div class="x_title">
				<h2>My Customers</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


				</ul>
				<div class="clearfix"></div>
			</div>
			<ul class="list-unstyled top_profiles scroll-view">
                          
                          <?php  echo $this->partial("customer-side-bar-list-snipet", array('customers'=>$myCustomers))?>
                        </ul>
		</div>
	</div>

</div>


<?php

echo $this->headScript()
    ->appendFile($this->basePath('js/jquery.mask.min.js'))
    ->appendFile($this->basePath('angular/CustomerModule.js'))
    ->appendFile($this->basePath('angular/controllers/customerController.js'));
?>

<script type="text/javascript">


        $(document).ready(function () {
             $('.money').mask('000,000,000,000,000.00', {reverse: true});
            $('.phone').mask('00000000000');
            

        });

        // for the type of customer
        
    </script>

