<?php
echo $this->headTitle("Active Offer");
if($this->identity()){
?>
<div class="row">
	<div class="col-md-8 col-lg-9">
		<div class="panel panel-default">
		
			<!-- Progress table -->
			<div class="table-responsive">
			
				<table id="myTable"  class="table v-middle">
					<thead>
						<tr>
							
							<th>Updated</th>
							<th>Offer Name</th>
							<th>Offer Code</th>
							
							<th>Progress</th>
							<th class="text-right">Action</th>
							
						</tr>
					</thead>
					<tbody id="responsive-table-body">
						<?php  echo $this->partial("customer-offer-active-list", array("offer"=>$offer))?>
					</tbody>
				</table>
			</div>
			<!-- // Progress table -->

<!-- 			<div class="panel-footer padding-none text-center"> -->
<!-- 				<ul class="pagination"> -->
<!-- 					<li class="disabled"><a href="#">&laquo;</a></li> -->
<!-- 					<li class="active"><a href="#">1</a></li> -->
<!-- 					<li><a href="#">2</a></li> -->
<!-- 					<li><a href="#">3</a></li> -->
<!-- 					<li><a href="#">4</a></li> -->
<!-- 					<li><a href="#">5</a></li> -->
<!-- 					<li><a href="#">&raquo;</a></li> -->
<!-- 				</ul> -->
<!-- 			</div> -->
		</div>

	</div>

<div class="col-lg-3 col-md-3 col-sm-3"> 
        <!-- .panel -->
          
          <!-- // END .panel -->
          <?php echo $this->partial("customer-offer-menu")?>
      <?php  echo $this->partial("customer-board-featured-packages")?></div>
      
      <?php }?>
</div>

