<?php

$offerPremium = $this->offerPremium;
?>
<div class="col-md-6 col-xs-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Offer Premium:</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                 
                      <?php if($offerPremium == NULL){?> 
                      
                      show Premium information acquisition inform / premium 
                      <?php 
                      /**
                       * This shows no premium generated yet
                       * and provides information on how to make 
                       * a premium available 
                       * a list of objects must be 
                       */
                      ?>
                      
                      <?php }else{?>
                      
                      show premium value and status
                      <?php }?>
                      
                  
                   </div>
                </div>
              </div>