<?php


?>

                  
                    
                    <div class="x_content">

                      <div class="">
                        <ul class="to_do">
                          <?php echo $this->offer_process_all_object_view($objects);?>
                          
                        </ul>
                      </div>
                    </div>
                  
                