
<div class="col-md-12 col-sm-12 col-xs-12">
<?php echo $this->partial("message-form-snippet", array("messageForm"=>$this->messageForm))?>

<div id="success"></div>
	<div id="error"></div>

	<i id="myLoader" class="fa  fa-pulse fa-lg" style="display: none;"><img
		alt=""
		src="<?php  echo $this->basepath("/animated-loading-gif-2.gif")?>"
		height=100></i>
	<div class="x_content">
		<ul class="list-unstyled timeline">
			<div id="sentmessage"></div>
			
<?php  echo $this->brokerMessageOfferHelper($offerEntity)?>
</ul>
	</div>
</div>