<footer class="footer">
	<strong>Powered By: </strong><a href=""><?php  echo $this->customer_broker_name_helper()?></a>
</footer>
<!-- // Footer -->

<!-- Inline Script for colors and config objects; used by various external scripts; -->
<script>
    var colors = {
      "danger-color": "#e74c3c",
      "success-color": "#81b53e",
      "warning-color": "#f0ad4e",
      "inverse-color": "#2c3e50",
      "info-color": "#2d7cb5",
      "default-color": "#6e7882",
      "default-light-color": "#cfd9db",
      "purple-color": "#9D8AC7",
      "mustard-color": "#d4d171",
      "lightred-color": "#e15258",
      "body-bg": "#f6f6f6"
    };
    var config = {
      theme: "html",
      skins: {
        "default": {
          "primary-color": "#42a5f5"
        }
      }
    };
  </script>
  
  <?php // echo $this->headScript()->appendFile($this->basePath('js/jquery.js'));?>

<!-- Vendor Scripts Bundle
    Includes all of the 3rd party JavaScript libraries above.
    The bundle was generated using modern frontend development tools that are provided with the package
    To learn more about the development process, please refer to the documentation.
    Do not use it simultaneously with the separate bundles above. -->
<script src="<?php echo $this->basePath("client/js/vendor/all.js")?>"></script>
<script src="<?php echo $this->basePath('js/wasabi.gritter.js')?>"></script> 
<script src="<?php echo $this->basePath('js/wasabi.suggest.js')?>"></script> 
<script src="<?php echo $this->basePath('js/wasabilib.min.js')?>"></script> 

<!-- Vendor Scripts Standalone Libraries -->


<!-- App Scripts Bundle
    Includes Custom Application JavaScript used for the current theme/module;
    Do not use it simultaneously with the standalone modules below. -->
<script src="<?php //echo $this->basePath("client/js/app/app.js")?>"></script>

<!-- App Scripts Standalone Modules
    As a convenience, we provide the entire UI framework broke down in separate modules
    Some of the standalone modules may have not been used with the current theme/module
    but ALL the modules are 100% compatible -->

<script
	src="<?php echo $this->basePath("/client/js/app/essentials.js")?>"></script>
<script src="<?php echo $this->basePath("/client/js/app/material.js")?>"></script>
<script src="<?php echo $this->basePath("/client/js/app/layout.js")?>"></script>
<script src="<?php echo $this->basePath("/client/js/app/sidebar.js")?>"></script>

<script src="<?php echo $this->basePath("/client/js/app/media.js")?>"></script>

<script src="<?php echo $this->basePath("/client/js/app/messages.js")?>"></script>

<!-- <script src="js/app/maps.js"></script> -->
<script src="<?php //echo $this->basePath("/client/js/app/charts.js")?>"></script>
<script src="<?php //echo $this->basePath("/client/js/app/charts.js")?>"></script>
<script src="<?php echo $this->basePath("/vendors/validator/validator.js")?>"></script>

<script type="text/javascript">
$(document).ready(function() {
    $('#myTable').DataTable( {
        "paging":   true,
        "ordering": false,
        "info":     false
    } );
} );
</script>

<?php 
echo $this->headScript()->appendFile($this->basePath('vendors/dropzone/dist/dropzone.js'));
//echo $this->headscript()->appendFile($this->basepath("/credit-card/js/index.js"));
//echo $this->headLink()->appendStylesheet('/vendors/dropzone/dist/basic.css');
echo $this->headLink()->appendStylesheet('/vendors/dropzone/dist/dropzone.css');
//echo $this->headLink()->appendStylesheet('/credit-card/css/style.css');
?>
<?php

echo $this->headScript()

    ->appendFile($this->basePath('js/jquery.maskMoney.js'));
?>

<script>
  $(function() {
    $('#objectValue').maskMoney();
    $(".money").maskMoney();
  })
</script>
<!-- App Scripts CORE [html]:
        Includes the custom JavaScript for this theme/module;
        The file has to be loaded in addition to the UI modules above;
        app.js already includes main.js so this should be loaded
        ONLY when using the standalone modules; -->
<!-- <script src="js/app/main.js"></script> -->

</body>
</html>