<?php
?>

<div
	class="navbar navbar-default navbar-fixed-top navbar-size-large navbar-size-xlarge paper-shadow"
	data-z="0" data-animated role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#main-nav">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<div class="navbar-brand navbar-brand-logo">
				<a class="svg" href="<?php echo $this->url("board")?>"> <img
					alt="logo"
					src="<?php  echo $this->customer_broker_logo_helper()?>" height=50>
				</a>
			</div>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="main-nav">
			<ul class="nav navbar-nav navbar-nav-margin-left">
				<li class="dropdown"><a href="#" class="dropdown-toggle"
					data-toggle="dropdown">My Board<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="<?php  echo $this->url("board")?>">My Dasboard</a></li>
						<li><a href="<?php  echo $this->url("cus_invoice")?>">My Invoices</a></li>
						<li><a href="<?php  echo $this->url("cus_object")?>">My Property</a></li>
						<li><a href="<?php  echo $this->url("cus_claims")?>">My Unsettled
								Claims</a></li>
						<li><a href="<?php  echo $this->url("cus_risk")?>">My Risk </a></li>
						<li><a href="<?php  echo $this->url("cus_policy")?>">My Policy </a></li>
						<li><a href="<?php  echo $this->url("cus_proposal")?>">My
								Proposals </a></li>
						<li><a href="<?php echo $this->url("cus_offer")?>">My Quotes</a></li>


					</ul></li>
				<!--           <li class="dropdown"> -->
				<!--             <a href="#" class="dropdown-toggle" data-toggle="dropdown">Proposals<span class="caret"></span></a> -->
				<!--             <ul class="dropdown-menu"> -->
				<!--               <li><a href="website-directory-grid.html">Grid Directory</a></li> -->
				<!--               <li><a href="website-directory-list.html">List Directory</a></li> -->
				<!--               <li><a href="website-course.html">Single Course</a></li> -->
				<!--             </ul> -->
				<!--           </li> -->
				<li class="dropdown"><a href="#" class="dropdown-toggle"
					data-toggle="dropdown">Quotes<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a
							href="<?php  echo $this->url("cus_offer/default", array("action"=>"prenew"));?>">New
								Quote</a></li>
						<li><a
							href="<?php  echo $this->url("cus_offer/default", array("action"=>"active"))?>">My
								Active Quotes</a></li>

					</ul></li>
				<li class="dropdown"><a href="#" class="dropdown-toggle"
					data-toggle="dropdown">Packages <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="<?php echo $this->url("cus_pack")?>">View All
								Packages</a></li>
						<li><a
							href="<?php echo $this->url("cus_pack/default", array("action"=>"active"))?>">Active
								Packages</a></li>

					</ul></li>



				<li class="dropdown"><a href="#" class="dropdown-toggle"
					data-toggle="dropdown">Accounts<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a
							href="<?php  echo $this->url("board/default", array("action"=>"profile"))?>"><i
								class="fa fa-user"></i> Profile</a></li>
						<li><a id="btn3" class="ajax_element"
							data-json='{"type":"standard"}'
							data-href="<?php  echo $this->url("board", array("action"=>"layclaimmodal"))?>"><i
								class="fa fa-bookmark-o"></i> Lay Claims</a></li>
						<!-- 									<li><a href="<?php // echo $this->url("cus_invoice/default", array("action"=>"transactions"))?>"><i
								class="fa fa-euro"></i> Transactions</a></li> -->
						<li><a href="<?php echo $this->url("cus_message")?>"><i
								class="fa fa-comment"></i> Messages</a></li>
							<li><a id="btn3" class="ajax_element"
							data-json='{"type":"standard"}'
							data-href="<?php  echo $this->url("board", array("action"=>"layclaimmodal"))?>"><i
								class="fa fa-credit-card"></i> Add Card</a></li>	
								
						<li><a href="<?php echo $this->url("client_logout")?>"><i
								class="fa fa-sign-out"></i> Logout</a></li>

					</ul></li>
			</ul>
			<div class="navbar-right">
				<ul
					class="nav navbar-nav navbar-nav-bordered navbar-nav-margin-right">
					<!-- user -->
					<li class="dropdown user"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown"> <img src="images/people/110/guy-6.jpg"
							alt="" class="img-circle" /><?php echo $this->customer_layout_customer_name_helper()  ?><span
							class="caret"></span>
					</a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="<?php  echo $this->url("board")?>"><i
									class="fa fa-bar-chart-o"></i> Dashboard</a></li>

							<li><a
								href="<?php  echo $this->url("board/default", array("action"=>"profile"))?>"><i
									class="fa fa-user"></i>My Profile</a></li>

						</ul></li>
					<!-- // END user -->
				</ul>
				<a
					href="<?php  echo ($this->identity() == TRUE ? $this->url("client_logout"): " ")?>"
					class="navbar-btn btn btn-primary"><?php  echo ($this->identity() == TRUE ? "LOGOUT":"")?></a>
			</div>
		</div>
		<!-- /.navbar-collapse -->

	</div>
</div>

