<?php
?>
<div class="container">

	<div class="page-section">
      <?php  echo $this->partial("general-error-ponters")?>
<!--       <div class="panel panel-default"> -->
<!-- 			<div class="media v-middle"> -->
<!-- 				<div class="media-left"> -->
<!-- 					<div class="bg-green-400 text-white"> -->
<!-- 						<div class="panel-body"> -->
<!-- 							<i class="fa fa-align-justify fa-fw fa-2x"></i> -->
<!-- 						</div> -->
<!-- 					</div> -->
<!-- 				</div> -->
<!-- 				<div class="media-body"> -->
<!-- 					<a -->
<!-- 						class="btn btn-default text-grey-400 btn-lg btn-circle paper-shadow relative" -->
<!-- 						data-hover-z="0.5" data-animated data-toggle="tooltip" -->
<!-- 						data-title="policy Renewals"> <i class="fa fa-file-text "></i> -->
<!-- 					</a> -->
<!-- 				</div> -->
				
<!-- 			</div> -->
<!-- 		</div> -->
		<div id="wasabi"></div>
      <?php  echo $this->content ?>
    </div>

</div>