<?php
?>

<div class="parallax overflow-hidden bg-blue-400 page-section third">
    <div class="container parallax-layer" data-opacity="true">
      <div class="media v-middle">
        
        <div class="media-body">
          <h4 class=" text-display-10 margin-v-0"><?php  echo $this->customer_broker_name_helper()?></h4>
          
        </div>
        
      </div>
    </div>
  </div>