<ul class="nav side-menu">
<?php

foreach ($this->container as $page) :
    /** @var Zend\Navigation\Page\AbstractPage $page */

    ?>
            <li class="<?php echo $page->hasPages() ?>"><a>
                    <?php echo $page->getLabel()?>
                   
                </a>
                <?php if ($page->hasPages()): ?>
                    <ul class="nav child_menu" style="display: none">
                        <?php
        
foreach ($page->getPages() as $child) :
            /** @var Zend\Navigation\Page\AbstractPage $child */
            ?>
                            <li><a
				href="<?php echo $child->getHref() ?>">
                                    <?php echo $child->getLabel()?>
                                </a></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>