<?php
?>
 <ul class="form-list">
<div class="form-group">
         
            <?php
            // $element = $userForm->get('password');
            echo $this->formlabel($bankPaymentFieldset->get("bank"));
            ?>
             <div class="col-md-9 col-sm-9 col-xs-12">
           <?php
        
        echo $this->formElement($bankPaymentFieldset->get("bank"));
        ?>
            </div>
	<div style="font-size: 9px; color: red;">
              <?php
            echo $this->formElementErrors($bankPaymentFieldset->get("bank"));
            ?>
              </div>
</div>

 <li class="form-list__row">

         <label>
            <?php
            // $element = $userForm->get('password');
            echo $this->formlabel($bankPaymentFieldset->get("accNumber"));
            ?>
            </label>
            <div class="bank-icon">
           <?php
        
        echo $this->formElement($bankPaymentFieldset->get("accNumber"));
        ?>
            </div>
	<div style="font-size: 9px; color: red;">
              <?php
            echo $this->formElementErrors($bankPaymentFieldset->get("accNumber"));
            ?>
              </div>
</li>

<div class="form-list__row" id="dob">
         
<!--              <div class="col-md-3 col-sm-3 col-xs-3"> -->
           <?php
        
//         echo $this->formElement($bankPaymentFieldset->get("passcode_d"));
//         ?>
<!--             </div> -->
<!-- 	<div class="col-md-3 col-sm-3 col-xs-3"> -->
           <?php
        
//         echo $this->formElement($bankPaymentFieldset->get("passcode_m"));
//         ?>
<!--             </div> -->
	<div class="col-md-9 col-sm-9 col-xs-9">
           <?php
        
        echo $this->formElement($bankPaymentFieldset->get("passcode_y"));
        ?>
            </div>
	<div style="font-size: 9px; color: red;">
              <?php
            echo $this->formElementErrors($bankPaymentFieldset->get("passcode_d"));
            ?>
              </div>
</div>

</ul>

<br>
<?php 
echo $this->headScript()->appendFile($this->basePath('js/jquery.mask.min.js'));
// echo $this->headscript()->appendFile($this->basepath("/credit-card/js/index.js"));

echo $this->headLink()->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css');
echo $this->headLink()->appendStylesheet('/credit-card/css/style.css');
?>




<script type="text/javascript">


        $(document).ready(function () {
            
            $('#acc_number').mask('0000000000');
            $("#dob").hide();
            $("#bank").change(function(){
            	if($("#bank").val() == "220"){
					$("#dob").show();
				}else{
					$("#dob").hide();
				}
            })
            

        });

        // for the type of customer
        
    </script>