
<div class="modal__container">

	<div class="modal__content">
      <?php
    $bankPaymentForm->prepare();
    
    echo $this->form()->openTag($bankPaymentForm);
    
    ?>
<?php
echo $this->partial("transaction-bank-payment-fieldset-snippet", array(
    "bankPaymentFieldset" => $bankPaymentForm->get("bankPaymentFieldset")
));
?>
<br>
<?php 

echo $this->formrow($bankPaymentForm->get("csrf"));
echo $this->formrow($bankPaymentForm->get("submit"));
echo $this->form()->closeTag()?>


</div>
</div>
<script type="text/javascript">


        $(document).ready(function () {
            
            $('#acc_number').mask('0000000000');
           // $('.url').mask('http://#.#', {'translation': {
              //  A: {pattern: /[A-Za-z0-9]/},
              //  S: {pattern: /[A-Za-z]/}
               
             // }
        //});
            

        });

        // for the type of customer
        
    </script>