<?php
$forme = $this->payForm;
?>
<div class="modal__container">
	<div class="modal__content">
		<ul class="form-list">
			<li class="form-list__row"><label>Name</label>
             <?php echo $this->formElement($forme->get('cc_name'))?>
            </li>
			<li class="form-list__row"><label>Card Number</label>
				<div id="input--cc" class="creditcard-icon">
               
                 <?php echo $this->formElement($forme->get('cc_number'))?>
              </div></li>
			<li class="form-list__row form-list__row--inline">
				<div>
					<label>Expiration Date</label>
					<div class="form-list__input-inline">
                 <?php echo $this->formElement($forme->get('cc_month'))?>
                 <?php echo $this->formElement($forme->get('cc_year'))?>
                </div>
				</div>
				<div>
					<label> CVC <a href="#cvv-modal"
						class="button--transparent modal-open button--info"> <svg
								class="nc-icon glyph" xmlns="http://www.w3.org/2000/svg"
								xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
								width="16px" height="16px" viewBox="0 0 16 16">
								<g> <path fill="#35a4fb"
									d="M8,0C3.6,0,0,3.6,0,8s3.6,8,8,8s8-3.6,8-8S12.4,0,8,0z M8,13c-0.6,0-1-0.4-1-1c0-0.6,0.4-1,1-1s1,0.4,1,1 C9,12.6,8.6,13,8,13z M9.5,8.4C9,8.7,9,8.8,9,9v1H7V9c0-1.3,0.8-1.9,1.4-2.3C8.9,6.4,9,6.3,9,6c0-0.6-0.4-1-1-1 C7.6,5,7.3,5.2,7.1,5.5L6.6,6.4l-1.7-1l0.5-0.9C5.9,3.6,6.9,3,8,3c1.7,0,3,1.3,3,3C11,7.4,10.1,8,9.5,8.4z"></path> </g></svg>
							<span class="visuallyhidden">What is CVV?</span>
					</a>
					</label>
                
                 <?php echo $this->formElement($forme->get('cc_cvc'))?>
               
              </div>
			</li>

			<li class="form-list__row"><label>Card PIN</label>
              
               
                  <?php echo $this->formElement($forme->get('cc_pin'))?>
            
            </li>


			<li class="form-list__row form-list__row--agree"><label>
               <?php echo $this->formElement($forme->get('save_cc'))?>
                Save my card for future purchases
              </label></li>
			<!--             <li> -->
			<!--               <button type="submit" class="button">Pay Now</button> -->
			<!--             </li> -->
		</ul>
	</div>
</div>
<?php
echo $this->headScript()->appendFile($this->basePath('js/jquery.mask.min.js'));
echo $this->headscript()->appendFile($this->basepath("/credit-card/js/index.js"));

echo $this->headLink()->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css');
echo $this->headLink()->appendStylesheet('/credit-card/css/style.css');
?>


<script type="text/javascript">


        $(document).ready(function () {
            
            $('#pin').mask('00000');
           // $('.url').mask('http://#.#', {'translation': {
              //  A: {pattern: /[A-Za-z0-9]/},
              //  S: {pattern: /[A-Za-z]/}
               
             // }
        //});
            

        });

        // for the type of customer
        
    </script>