<?php
if (count($docs) > 0) {
    ?>
<div class="item col-xs-12 col-lg-12">
	<div class="panel panel-default paper-shadow" data-z="0.5">
		<div class="panel-heading">
			<h4 class="text-headline margin-none">My Courses</h4>
			<p class="text-subhead text-light">Your recent courses</p>
		</div>
		<ul class="list-group">
    <?php
    foreach ($docs as $doc) {
        $jsonData = json_encode(array(
            "data" => $doc->getid()
        ));
        ?>
    
    <div style='text-align: center;'>
				<i id='removeDocument' class='fa fa-lg'
					style='display: none; text-align: center;'><img alt=''
					src='<?php echo  $this->basePath('/processin.gif')  ?>' height=50>
					<hr></i>
			</div>

			<li class="list-group-item media v-middle">
				<div class="media-body">
					<a class="text-subhead list-group-link"><?php  echo $doc->getDocName()?></a>
				</div>
				<div class="media-right">
					<a id="sending_data_button" data-ajax-loader="removeDocument"
						data-json='<?php echo $jsonData; ?>' style="width: 100%;" data-href="<?php  echo $this->url("cus_proposal/default", array("action"=>"removedocument"))?>"
						class="btn btn-xs btn-danger ajax_element">REMOVE</a>

				</div>
			</li>
                  
                
               
    <?php
    }
    ?>
    </ul>
		<div class="panel-footer text-right">
			<a href="website-instructor-courses.html"
				class="btn btn-white paper-shadow relative" data-z="0"
				data-hover-z="1" data-animated>View all</a> <a
				href="website-instructor-course-edit-course.html"
				class="btn btn-primary paper-shadow relative" data-z="0"
				data-hover-z="1" data-animated>CREATE COURSE <i class="fa fa-plus"></i></a>
		</div>
	</div>
</div>

<?php
} else {
    echo "No Document Available";
}