
<?php
$the_background = "/images/bg2.jpg";
// $the_background = " "
// echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
<div class="jumbotron" style="background-image: url(<?php echo $the_background; ?>);">
	<div class="container">
		<div class="form-div">

			<a href="<?php //echo $this->url('home') ?>"><img
				src="/img/myBroker200.png" alt="Insurance Manager App" /></a>



			<h4><?php echo $this->translate('Registration Successfull')?></h4>	
<?php
/**
 * CsnUser - Coolcsn Zend Framework 2 User Module
 *
 * @link https://github.com/coolcsn/CsnUser for the canonical source repository
 * @copyright Copyright (c) 2005-2013 LightSoft 2005 Ltd. Bulgaria
 * @license https://github.com/coolcsn/CsnUser/blob/master/LICENSE BSDLicense
 * @author Stoyan Cheresharov <stoyan@coolcsn.com>
 * @author Svetoslav Chonkov <svetoslav.chonkov@gmail.com>
 * @author Nikola Vasilev <niko7vasilev@gmail.com>
 * @author Stoyan Revov <st.revov@gmail.com>
 * @author Martin Briglia <martin@mgscreativa.com>
 */

echo $this->partial('csn-user/layout/nav-menu', array(
    'navMenu' => $this->navMenu,
    'user' => $this->identity()
));

?>


  <h4>
    <?php echo sprintf($this->translate('An email has been sent to <span class="zf-green">%s</span>. Please, check your inbox and confirm your registration!'), $email);?>
  </h4>
		</div>

	</div>
</div>
