<?php
echo $this->headtitle("General Settings");
?><div class="row">
	<div class='col-md-3 col-sm-3 col-xs-12'>
		<br><br>
		<br>
      <?php  echo $this->partial("settings-navigation")?>
    </div>
	<div class='col-md-9 col-sm-9 col-xs-12'>hjrsg wenfgk,dfh ADHJVBGf
		ADHMVHG ISDUFV BSKDVGHd hFBKZCU VDKKJVBHJNhjhb,iadf jxcha dxbfgk,uvh
		diufdukvyh izudfbvi,uzxdhf kjdhv izgvj sfg bfub hsdvhlizxufh djgh
		hjrsg wenfgk,dfh ADHJVBGf
		ADHMVHG ISDUFV BSKDVGHd hFBKZCU VDKKJVBHJNhjhb,iadf jxcha dxbfgk,uvh
		diufdukvyh izudfbvi,uzxdhf kjdhv izgvj sfg bfub hsdvhlizxufh djgh
		hjrsg wenfgk,dfh ADHJVBGf
		ADHMVHG ISDUFV BSKDVGHd hFBKZCU VDKKJVBHJNhjhb,iadf jxcha dxbfgk,uvh
		diufdukvyh izudfbvi,uzxdhf kjdhv izgvj sfg bfub hsdvhlizxufh djgh
		hjrsg wenfgk,dfh ADHJVBGf
		ADHMVHG ISDUFV BSKDVGHd hFBKZCU VDKKJVBHJNhjhb,iadf jxcha dxbfgk,uvh
		diufdukvyh izudfbvi,uzxdhf kjdhv izgvj sfg bfub hsdvhlizxufh djgh
		hjrsg wenfgk,dfh ADHJVBGf
		ADHMVHG ISDUFV BSKDVGHd hFBKZCU VDKKJVBHJNhjhb,iadf jxcha dxbfgk,uvh
		diufdukvyh izudfbvi,uzxdhf kjdhv izgvj sfg bfub hsdvhlizxufh djgh
		hjrsg wenfgk,dfh ADHJVBGf
		ADHMVHG ISDUFV BSKDVGHd hFBKZCU VDKKJVBHJNhjhb,iadf jxcha dxbfgk,uvh
		diufdukvyh izudfbvi,uzxdhf kjdhv izgvj sfg bfub hsdvhlizxufh djgh
		hjrsg wenfgk,dfh ADHJVBGf
		ADHMVHG ISDUFV BSKDVGHd hFBKZCU VDKKJVBHJNhjhb,iadf jxcha dxbfgk,uvh
		diufdukvyh izudfbvi,uzxdhf kjdhv izgvj sfg bfub hsdvhlizxufh djgh
		hjrsg wenfgk,dfh ADHJVBGf
		ADHMVHG ISDUFV BSKDVGHd hFBKZCU VDKKJVBHJNhjhb,iadf jxcha dxbfgk,uvh
		diufdukvyh izudfbvi,uzxdhf kjdhv izgvj sfg bfub hsdvhlizxufh djgh</div>
</div>