<?php

?>

<section class="content invoice">
                      <!-- title row -->
                      <div class="row">
                        <div class="col-xs-12 invoice-header">
                          <h1>
                                          <i class="fa fa-globe"></i> Invoice.
                                          <small class="pull-right">Generated On: <?php  echo $this->dateFormat($invoice->getGeneratedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_US")?></small>
                                      </h1>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- info row -->
                      <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                          From
                          <address>
                                          <strong><?php echo $broker->getBrokerName()?></strong>
                                          <br><?php  echo $broker->getBrokerAddress()?>
                                          <br>New York, CA 94107
                                          <br>Phone: <?php echo $broker->getOfficialPhone()?>
                                          <br>Email: <?php echo $broker->getBrokerEmail() ?>
                                      </address>
                        </div>
          
                        <div class="col-sm-4 invoice-col">
                          <b>Invoice : <?php  echo strtoupper($invoice->getInvoiceUid())?></b>
                          <br>
                          
                          <b>Customer Name: </b>  <?php  echo $invoice->getCustomer()->getName() ?>
                          <br>
                          <b>Payment Due:</b> <?php  echo $this->dateFormat($invoice->getExpiryDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_US")?>
                          
                          <br>
<!--                           <b>Account:</b> 968-34567 -->
                        </div>
                        <!-- /.col -->
                        
                                      <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                         <?php  echo $this->invoicePaymentStatus($invoice)?>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <!-- Table row -->
                      <div class="row table-responsive">
                    
                        <div class="col-xs-12 table">
                          <table class="table table-striped">
                            <thead>
                              <tr>
                                <th>Qty</th>
                                <th>Product</th>
                                <th>Serial #</th>
                                <th style="width: 59%">Description</th>
                                <th>Subtotal</th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <td></td>
                                <td><?php  echo ($invoice->getInvoiceCategory() == NULL ? " No Category Available" : $invoice->getInvoiceCategory()->getCategory())?></td>
                                <td><?php  echo ($this->invoice->getInvoiceUid() == NULL ? "NO UId Available" : strtoupper($invoice->getInvoiceUid()))?></td>
                                <td>The is full payment for <?php  echo ($invoice->getInvoiceCategory() == NULL ? " No Category Available" : $invoice->getInvoiceCategory()->getCategory())?>
                                </td>
                                <td><?php  echo $this->myCurrencyFormat(($invoice->getAmount() == NULL ? " " : $invoice->getAmount()), $invoice->getCurrency()->getCode() )?></td>
                              </tr>
                             
                            </tbody>
                          </table>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <div class="row">
                        <!-- accepted payments column -->
                        <div class="col-xs-6">
                          <p class="lead">Payment Methods:</p>
                           <?php  echo $this->paymentMethodViewHelper();?>
                        </div>
                        <!-- /.col -->
                        <div class="col-xs-6">
                          <p class="lead">Due Date:   <?php  echo $this->dateFormat($invoice->getExpiryDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_US")?></p>
                          <div class="table-responsive">
                            <table class="table">
                              <tbody>
<!--                                 <tr> -->
                                 
<!--                                   <td>$250.30</td> -->
<!--                                 </tr> -->
<!--                                 <tr> -->
<!--                                   <th>Tax (9.3%)</th> -->
<!--                                   <td>$10.34</td> -->
<!--                                 </tr> -->
<!--                                 <tr> -->
<!--                                   <th>Shipping:</th> -->
<!--                                   <td>$5.80</td> -->
<!--                                 </tr> -->
                                <tr>
                                  <th>Total:</th>
                                  <td><?php echo $this->myCurrencyFormat($invoice->getAmount(), $invoice->getCurrency()->getCode())?></td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->

                      <!-- this row will not appear when printing -->
                      
                    </section>
                    