<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Transactions\Module' => __DIR__ . '/Module.php',
    'Transactions\Controller\TransactionsController' => __DIR__ . '/src/Transactions/Controller/TransactionsController.php',
    'TransactionsTest\Framework\TestCase' => __DIR__ . '/tests/Transactions/Framework/TestCase.php',
    'TransactionsTest\SampleTest' => __DIR__ . '/tests/Transactions/SampleTest.php'
);
