<?php


?>

<div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
            <div class="panel-heading panel-collapse-trigger">
              <h4 class="panel-title">Offer Menu</h4>
            </div>
            <div class="panel-body list-group">
              <ul class="list-group list-group-menu">
                <li class="list-group-item"><a class="link-text-color" href="<?php echo $this->url("cus_offer/default", array("action"=>"prenew"))?>">New Offer</a></li>
                <li class="list-group-item"><a class="link-text-color" href="<?php  echo $this->url("cus_offer")?>">Active Offers</a></li>
           
              </ul>
            </div>
          </div>