<?php


?>
<div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
            <div class="panel-heading panel-collapse-trigger">
              <h4 class="panel-title">Offer Actions</h4>
            </div>
            <div class="panel-body list-group">
              <ul class="list-group list-group-menu">
                <li class="list-group-item"><a class="link-text-color" href="<?php echo $this->url("cus_offer/default", array())?>">Edit Offer</a></li>
                <li class="list-group-item"><a class="link-text-color" href="#">Add Propery</a></li>
                <li class="list-group-item"><a class="link-text-color" href="#">Upload Document</a></li>
                <li class="list-group-item"><a class="link-text-color" href="#">Comment</a></li>
              </ul>
            </div>
          </div>