<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Help\Module'                        => __DIR__ . '/Module.php',
    'Help\Controller\HelpController' => __DIR__ . '/src/Help/Controller/HelpController.php',
    'HelpTest\Framework\TestCase'        => __DIR__ . '/tests/Help/Framework/TestCase.php',
    'HelpTest\SampleTest'                => __DIR__ . '/tests/Help/SampleTest.php',
);
