<?php
/**
 *  This phtml proives a template form customer payment error
 */
?>
<div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                    </button>
                    <strong><?php  echo $error ?></strong>
                    <p>Please try again later </p>
                  </div>