<?php
?>
<style type="text/css">
@media only screen {
	.container {
		padding: 10px;
	}
}

@media only screen {
	.content {
		padding: 10px;
	}
}

@media only screen and (max-width: 620px) {
	table[class=body] h1, table[class=body] h2, table[class=body] h3, table[class=body] h4
		{
		font-weight: 600 !important;
	}
}

@media only screen and (max-width: 620px) {
	table[class=body] h1 {
		font-size: 22px !important;
	}
}

@media only screen and (max-width: 620px) {
	table[class=body] h2 {
		font-size: 18px !important;
	}
}

@media only screen and (max-width: 620px) {
	table[class=body] h3 {
		font-size: 16px !important;
	}
}

@media only screen and (max-width: 620px) {
	table[class=body] .content, table[class=body] .wrapper {
		padding: 10px !important;
	}
}

@media only screen and (max-width: 620px) {
	table[class=body] .container {
		padding: 0 !important;
		width: 100% !important;
	}
}

@media only screen and (max-width: 620px) {
	table[class=body] .btn table, table[class=body] .btn a {
		width: 100% !important;
	}
}

@media only screen and (max-width: 620px) {
	.header {
		margin-bottom: 10px !important;
		margin-top: 20px !important;
	}
}

@media only screen and (max-width: 620px) {
	table[class=body] .wrapper {
		padding: 40px 20px !important;
	}
}

@media only screen and (max-width: 620px) {
	.main.signup .panel:nth-of-type(2), .main.signup .panel:nth-of-type(3) {
		padding-bottom: 10px !important;
	}
}

@media only screen and (max-width: 620px) {
	.main.signup .panel:nth-of-type(1) img.intro {
		width: 120px !important;
	}
}

@media only screen and (max-width: 620px) {
	.no-media-query {
		display: none !important;
	}
}

@media only screen and (max-width: 620px) {
	.small-screen-block {
		width: 100% !important;
		height: auto !important;
		overflow: inherit !important;
		float: none !important;
		display: block !important;
		max-height: none !important;
		position: relative !important;
	}
}

@media only screen {
	.media-query-available--inline {
		width: auto !important;
		min-height: auto !important;
		overflow: auto !important;
		float: none !important;
		display: inline !important;
		max-height: auto !important;
	}
}

@media only screen {
	.media-query-not-vailable {
		display: none !important;
	}
}
</style>


<body
	style="margin: 0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; height: 100% !important; line-height: 1.6em; -webkit-font-smoothing: antialiased; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; width: 100% !important; background-color: #f6f6f6;">

	<table class="body"
		style="box-sizing: border-box; background-color: white; border-collapse: separate !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"
		width="100%" bgcolor="white">
		<tbody>
			<tr>
				<td
					style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top;"
					valign="top"></td>
				<td class="container"
					style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top; display: block; margin: 0 auto !important; max-width: 580px; padding: 10px 0; width: 580px;"
					width="580" valign="top">
					<div class="content"
						style="box-sizing: border-box; display: block; margin: 0 auto; max-width: 580px; padding: 10px 0;">

						<div class="header"
							style="box-sizing: border-box; margin-bottom: 10px; margin-top: 0; width: 100%;">
							<table
								style="box-sizing: border-box; border-collapse: separate !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"
								width="100%">
								<tbody>
									<tr>
										<td
											style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top;"
											valign="top"></td>
									</tr>
								</tbody>
							</table>
						</div>

						<table class="main signup"
							style="box-sizing: border-box; background: #ffffff; border: none; border-radius: 3px; font-size: 15px; line-height: 24px; border-collapse: separate !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"
							width="100%">
							<tbody>
								<tr>
									<td
										style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top;"
										valign="top">
										<table class="panel panel-dark"
											style="box-sizing: border-box; border-radius: 8px; margin-top: 0; background-color: #15233b; color: white; font-size: 15px; padding: 60px 20px; mso-table-rspace: 0pt; width: 100%; border-collapse: separate !important; mso-table-lspace: 0pt;"
											width="100%" bgcolor="#15233b">
											<tbody>
												<tr>
													<td class="align-center"
														style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top; text-align: center;"
														valign="top" align="center">


														<h1
															style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-weight: 600; line-height: 32px; margin: auto; font-size: 24px; text-transform: none; max-width: 400px; color: #9bbba7; margin-bottom: 26px;">
															You are about to authorize a payment of</h1>

														<p class="shrink-400"
															style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-weight: normal; margin: 0; max-width: 400px; margin-left: auto; margin-right: auto; font-size: 25px; color: red; margin-bottom: 0px;">
                             <?php echo $this->myCurrencyFormat($invoiceEntity->getAmount(), $invoiceEntity->getCurrency()->getCode()); ?>
                              
                            </p> <br> <i id="addcardLoader"
														class="fa fa-lg" style="display: none;"><img alt=""
															src="<?php  echo $this->basepath("/ver_loader.gif")?>"
															height=150></i> <a
														style="box-sizing: border-box; text-align: center; text-decoration: none; line-height: 1.1; font-size: 17px; border-radius: 5px; border: 15px solid #f5f5f5; color: white; border-right: 10px; display: block; font-family: sans-serif; border-left: 10px; border-color: #55b8da; background-color: #55b8da;"
														id="btn3" class="ajax_element"
														data-json='{"type":"standard"}'
														data-ajax-loader="addcardLoader"
														data-href="<?php  echo $this->url("board", array("action"=>"preauthprocess"))?>">
															<!--[if mso]>    <![endif]--> Pay Now <!--[if mso]>    <![endif]-->
													</a>


													</td>
												</tr>
											</tbody>
										</table>


									</td>
								</tr>

							</tbody>
						</table>


					</div>
				</td>
				<td
					style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top;"
					valign="top"></td>
			</tr>
		</tbody>
	</table>

</body>