<?php
use Policy\Service\PolicyService;

$thisdate = new DateTime();
if ($policy->getPolicyStatus()->getId() == PolicyService::POLICY_STATUS_INACTIVE) {
    echo "<span class='btn btn-danger' style='width: 60%'>EXPIRED policy</span>";
} elseif ($policy->getPolicyStatus()->getId() == PolicyService::POLICY_STATUS_SUSPENDED) {
    echo "<span class='btn btn-danger' style='width: 60%'>POILICY SUSPENDED</span>";
} 
else {
    ?>

<header>
<!--         <div class="container"> -->
            <div class="row">
                <div class="nine columns">
                    <h2><?php  echo $policy->getPolicyName() ?></h2>
                    <p> <?php  echo strtoupper($policy->getPolicyCode())?></p>
                </div>
                <div class="three columns pic">
                    <img class="profile" src="<?php echo $this->insurerLogohelper($policy->getCoverNote()->getInsurer()->getId())?>" alt="" height=100>
                    
                    <br>
                    <a href="#"><?php  echo $policy->getCoverNote()->getCustomer()->getName()?></a>
                    <a href="#"><?php  echo $policy->getCoverNote()->getCustomer()->getUser()->getEmail();?></a>
                    <a href="#"><?php  echo $policy->getCoverNote()->getCustomer()->getUser()->getUsername();?></a>
                </div>
            </div>
<!--         </div> -->
    </header>
<!--     <div class="container"> -->
        <div class="maincontent">
            <div class="row">
                <div class="four columns timeline">
                    <h1>Service</h1>
<!--                     <h4>May 2010 -  Current</h4> -->
                </div>
                <div class="seven columns offset-by-one">
                    <h2><?php  echo $this->covernote_service_type_helper($policy->getCoverNote());?></h2>
                    <h3><?php  echo $this->covernote_specific_service_type_helper($policy->getCoverNote())?></h3>
                    <p> </p>
                </div>
            </div>
<!--             <div class="row"> -->
<!--                 <div class="four columns timeline"> -->
<!--                  <h1>Cover</h1> -->
<!--                     <h4>April 2008 -  May 2010</h4> -->
<!--                 </div> -->
<!--                 <div class="seven columns offset-by-one"> -->
<!--                     <h2></h2> -->
<!--                     <h3>Senior Developer</h3> -->
<!--                     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur veniam illo, vel, non repudiandae? Quisquam laudantium beatae eius debitis repudiandae nostrum, eaque necessitatibus quibusdam numquam voluptatibus dicta iste perferendis.</p> -->
<!--                 </div> -->
<!--             </div> -->
<!--             <div class="row"> -->
<!--                 <div class="four columns timeline"> -->
<!--                     <h4>April 2008 -  May 2010</h4> -->
<!--                 </div> -->
<!--                 <div class="seven columns offset-by-one"> -->
<!--                     <h2>Twitter, INC</h2> -->
<!--                     <h3>Senior Developer</h3> -->
<!--                     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur veniam illo, vel, non repudiandae? Quisquam laudantium beatae eius debitis repudiandae nostrum, eaque necessitatibus quibusdam numquam voluptatibus dicta iste perferendis.</p> -->
<!--                 </div> -->
<!--             </div> -->
<!--             <div class="row skills"> -->
<!--                 <div class="four columns"> -->
<!--                     <h1>Skills</h1> -->
<!--                 </div> -->
<!--                 <div class="seven columns offset-by-one"> -->
<!--                     <span>HTML</span> -->
<!--                     <span>CSS</span> -->
<!--                     <span>Javascript</span> -->
<!--                     <span>ajax</span> -->
<!--                     <span>Photoshop</span> -->
<!--                     <span>Illustrator</span> -->
<!--                     <span>Sketch</span> -->
<!--                     <span>Project Management</span> -->
<!--                     <span>Sales</span> -->
<!--                     <span>Microsoft Office</span> -->
<!--                     <span>Animation Design</span> -->
<!--                 </div> -->
<!--             </div> -->
<!--             <div class="row education"> -->
<!--                 <div class="four columns"> -->
<!--                     <h1>Education</h1> -->
<!--                 </div> -->
<!--                 <div class="seven columns offset-by-one"> -->
<!--                     <h2>College / University</h2> -->
<!--                     <h3>Qualification</h3> -->
<!--                     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur veniam illo, vel, non repudiandae? Quisquam laudantium beatae eius debitis repudiandae nostrum, eaque necessitatibus quibusdam numquam voluptatibus dicta iste perferendis.</p> -->
<!--                 </div> -->
<!--             </div> -->
        </div>
<!--         <footer> -->
<!--             John Doe | Email@address.com | 123-456-0789 -->
<!--         </footer> -->
<!--     </div> -->

<?php }?>
<?php echo $this->headLink()->appendStylesheet('/css/mainr.css');?>