<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate(\Application\Controller\IndexController::APP_TITLE))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php

        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>
            
            <link rel="apple-touch-icon" sizes="57x57"
	href="/img/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60"
	href="/img/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72"
	href="/img/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76"
	href="/img/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114"
	href="/img/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120"
	href="/img/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144"
	href="/img/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152"
	href="/img/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180"
	href="/img/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"
	href="/img/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32"
	href="/img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96"
	href="/img/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16"
	href="/img/favicon-16x16.png">

<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
<link href="/vendors/dropzone/dist/min/dropzone.min.css"
	rel="stylesheet">
<!-- Le styles -->
<link
	href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css"
	rel="stylesheet" />
        <?php

        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->
        // ->prependStylesheet($this->basePath('ui/dropdown.min.css'))
        // ->prependStylesheet($this->basePath('chosen/chosen.css'))
        prependStylesheet($this->basePath('css/wasabi.gritter.css'))
            ->prependStylesheet($this->basePath('css/wasabi.modal.css'))
            ->prependStylesheet($this->basePath('css/wasabi.suggest.css'))
            ->prependStylesheet($this->basePath('css/wasabi.wizard.css'))
            ->prependStylesheet($this->basePath('css/icheck/flat/green.css'))
            ->prependStylesheet($this->basePath('css/custom.css'))
            ->prependStylesheet($this->basePath('css/animate.min.css'))
            ->prependStylesheet($this->basePath('fonts/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))?>
          

        <!-- Scripts -->
        <?php

        echo $this->headScript()
            ->prependFile($this->basePath('/js/vue.js'))
            ->prependFile($this->basePath('js/bootstrap-pincode-input.js'))
            ->prependFile($this->basePath('js/jquery.mask.min.js'))
            ->prependFile($this->basePath('js/jquery.numpad.js'))
            ->prependFile($this->basePath('chosen/chosen.jquery.js'))
            ->prependFile($this->basePath('js/wasabi.gritter.js'))
            ->prependFile($this->basePath('js/wasabi.suggest.js'))
            ->prependFile($this->basePath('js/wasabilib.min.js'))
            ->prependFile($this->basePath('js/nprogress.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath('js/imApp.js'))
            ->prependFile($this->basePath('angular/lib/angular.js'))?>
        
								



<script
	src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<!-- <script src="/js/vue.js"></script> -->

</head>
<body class="nav-md footer_fixed">
	<div class="container body">
		<script>
// var app = new Vue({
// 	el:"#hi",
// 	data:{
// 		a1:"Please i dont know",
// 		seen: true
// 	}
// });
</script>
		<script>

var vm = new Vue({});
</script>

		<div class="main_container">

			<div class="col-md-3 left_col menu_fixed">
				<div class="left_col scroll-view">

					<div class="navbar nav_title" style="border: 0;">
						<a href="#" class="site_title"><i class="fa fa-umbrella"></i> <span><?php echo $this->imprintHelper() ;?></span></a>
					</div>

					<div class="clearfix"></div>

					<!-- menu prile quick info -->
					<div class="profile">
						<div class="profile_pic">
                        <?php // TODO -- if the user image is set, use image else if it not set use the available avatar ?>
                            <img
								src="<?php echo  $this->imprintLogo()?>"
								class="img-circle profile_img">

						</div>
						<div class="profile_info">
							<span>.............</span>
							<h2>Welcome,</h2>
                            
                            <?php	// TODO -- if the fullname (firstname and lastname or company name) is set, display it else display the username available 	?>
                        </div>
					</div>
					<!-- /menu prile quick info -->

					<br />

					<!-- sidebar menu -->
					<div id="sidebar-menu"
						class="main_menu_side hidden-print main_menu">

						<div class="menu_section ">
							<h3><?php echo $this->imprintHelper();?></h3>
                            <?php

                            echo $this->navigation('mnavigation')
                                ->menu()
                                ->setPartial('partials/main-navigation.phtml')
                                ->setUlClass('nav side-menu')
                                ->setOnlyActiveBranch();
                            // echo $this->navigation('main-navigation')
                            // ->menu()
                            // ->render();
                            ?> 

                            
                        </div>
					</div>

					<!-- /sidebar menu -->

					<!-- /menu footer buttons -->
					<div class="sidebar-footer hidden-small">
						<a data-toggle="tooltip" data-placement="top" title="Settings"> <span
							class="glyphicon glyphicon-cog" aria-hidden="true"></span>
						</a> <a data-toggle="tooltip" data-placement="top"
							title="FullScreen"> <span class="glyphicon glyphicon-fullscreen"
							aria-hidden="true"></span>
						</a> <a data-toggle="tooltip" data-placement="top" title="Lock"> <span
							class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
						</a> <a data-toggle="tooltip" data-placement="top" title="Logout"
							href="<?php echo $this->url('logout')?>"> <span
							class="glyphicon glyphicon-off" aria-hidden="true"></span>
						</a>
					</div>
					<!-- /menu footer buttons -->
				</div>
			</div>


			<!-- top navigation -->

			<div class="top_nav">

				<div class="nav_menu">
					<nav class="" role="navigation">
						<div class="nav toggle">
							<a id="menu_toggle"><i class="fa fa-bars"></i></a>
						</div>

						<ul class="nav navbar-nav navbar-right">

							<li class=""><a href="javascript:;"
								class="user-profile dropdown-toggle" data-toggle="dropdown"
								aria-expanded="false"> <strong><?php // echo $this->imprintHelper();?></strong><img
									src="<?php echo  $this->basePath() ?>/images/img.jpg" alt=""> <span
									class=" fa fa-angle-down"></span>
							</a>
								<ul
									class="dropdown-menu dropdown-usermenu animated fadeInDown pull-right">
									<!-- 									<li><a href="javascript:;"> Profile</a></li> -->

									<!-- 									<li><a href="javascript:;">Help</a></li> -->
									<li><a target="__blank"
										href="<?php  echo $this->url("settings/default", array("action"=>"profile"))?>"><i
											class="fa fa-info-circle pull-right"></i> Help</a></li>
									<li><a
										href="<?php  echo $this->url("settings/default", array("action"=>"profile"))?>"><i
											class="fa fa-user pull-right"></i> My Profile</a></li>
									<li><a
										href="<?php echo $this->url('logout', array('action'=>'logout'))?>"><i
											class="fa fa-sign-out pull-right"></i> Log Out</a></li>
								</ul></li>
							<li role='presentation' class='dropdown'><a href='javascript:;'
								class='dropdown-toggle info-number' data-toggle='dropdown'
								aria-expanded='false'> <i class='fa fa-envelope-o'></i> <span
									class='badge bg-green'> <?php  echo ($this->brokerMessageSnippet() == NULL ? "0" : "+"); ?></span>
							</a>
								<?php  echo $this->brokerMessageSnippet()?>
								</li>
							<!-- 							<li role="presentation" class="dropdown"><a href="javascript:;" -->
							<!-- 								class="dropdown-toggle info-number" data-toggle="dropdown" -->
							<!-- 								aria-expanded="false"> <i class="fa fa-envelope-o"></i> <span -->
							<!-- 									class="badge bg-green">6</span> -->
							<!-- 							</a> -->
							<!-- 								<ul id="menu1" class="dropdown-menu list-unstyled msg_list" -->
							<!-- 									role="menu"> -->
							<!-- 									<li><a> <span class="image"><img src="images/img.jpg" -->
							<!-- 												alt="Profile Image" /></span> <span> <span>John Smith</span> -->
							<!-- 												<span class="time">3 mins ago</span> -->
							<!-- 										</span> <span class="message"> Film festivals used to be -->
							<!-- 												do-or-die moments for movie makers. They were where... </span> -->
							<!-- 									</a></li> -->
							<!-- 									<li><a> <span class="image"><img src="images/img.jpg" -->
							<!-- 												alt="Profile Image" /></span> <span> <span>John Smith</span> -->
							<!-- 												<span class="time">3 mins ago</span> -->
							<!-- 										</span> <span class="message"> Film festivals used to be -->
							<!-- 												do-or-die moments for movie makers. They were where... </span> -->
							<!-- 									</a></li> -->
							<!-- 									<li><a> <span class="image"><img src="images/img.jpg" -->
							<!-- 												alt="Profile Image" /></span> <span> <span>John Smith</span> -->
							<!-- 												<span class="time">3 mins ago</span> -->
							<!-- 										</span> <span class="message"> Film festivals used to be -->
							<!-- 												do-or-die moments for movie makers. They were where... </span> -->
							<!-- 									</a></li> -->
							<!-- 									<li><a> <span class="image"><img src="images/img.jpg" -->
							<!-- 												alt="Profile Image" /></span> <span> <span>John Smith</span> -->
							<!-- 												<span class="time">3 mins ago</span> -->
							<!-- 										</span> <span class="message"> Film festivals used to be -->
							<!-- 												do-or-die moments for movie makers. They were where... </span> -->
							<!-- 									</a></li> -->
							<!-- 									<li> -->
							<!-- 										<div class="text-center"> -->
							<!-- 											<a> <strong>See All Alerts</strong> <i -->
							<!-- 												class="fa fa-angle-right"></i> -->
							<!-- 											</a> -->
							<!-- 										</div> -->
							<!-- 									</li> -->
							<!-- 								</ul></li> -->

						</ul>
					</nav>
				</div>

			</div>
			<!-- /top navigation -->

			<!-- page content -->
			<div class="right_col" role="main">

				<div class="">
					<div class="page-title">
						<div class="title_left">
							<?php // thie breadcrumbs go here ?>
						</div>

						<!-- 						<div class="title_right"> -->
						<!-- 							<div -->
						<!-- 								class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search"> -->
						<!-- 								<div class="input-group"> -->
						<!-- 									<input type="text" class="form-control" -->
						<!-- 										placeholder="Search for..."> <span class="input-group-btn"> -->
						<!-- 										<button class="btn btn-default" type="button">Go!</button> -->
						<!-- 									</span> -->
						<!-- 								</div> -->
						<!-- 							</div> -->
						<!-- 						</div> -->
					</div>
					<div class="clearfix"></div>
       
        
            <?php echo $this->content; ?>
            <?php //echo $this->partial("application_chat_popup")?>
            </div>

				<!-- footer content -->

				<!-- 				<footer> -->
				<!-- 					<div class=""> -->
				<!-- 						<p class="pull-right"> -->
				<!-- 							Powered by <a>Swoop Effects</a> -->

				<!-- 						</p> -->
				<!-- 					</div> -->
				<!-- 					<div class="clearfix"></div> -->
				<!-- 				</footer> -->
				<!-- /footer content -->
			</div>
			<!-- /page content -->

		</div>

	</div>
        <?php echo $this->inlineScript()?>
       
        

	<!-- chart js -->
	<script src="/js/chartjs/chart.min.js"></script>
	<!-- bootstrap progress js -->
	<script src="/js/progressbar/bootstrap-progressbar.min.js"></script>
	<script src="/js/nicescroll/jquery.nicescroll.min.js"></script>
	<!-- icheck -->
	<script src="/js/icheck/icheck.min.js"></script>

	<script src="/js/custom.js"></script>
	<script src="/vendors/validator/validator.js"></script>
	<script src="/vendors/dropzone/dist/min/dropzone.min.js"></script>





</body>

</html>
