<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Comments\Module'                        => __DIR__ . '/Module.php',
    'Comments\Controller\IndexController' => __DIR__ . '/src/Comments/Controller/IndexController.php',
    'CommentsTest\Framework\TestCase'        => __DIR__ . '/tests/Comments/Framework/TestCase.php',
    'CommentsTest\SampleTest'                => __DIR__ . '/tests/Comments/SampleTest.php',
);
