<?php
use GeneralServicer\Service\GeneralService;

?>

<div class="table-responsive">
	<table id="datatable-responsive"
		class="table table-striped table-bordered dt-responsive nowrap"
		cellspacing="0" width="100%">
		<thead>
			<tr>
				<th>ID</th>
				<th>New Expiry Date</th>
				<th>Action</th>
			</tr>
		</thead>

		<tbody>
						
                    <?php
                    if (count($hooks) > 0) {
                        foreach ($hooks as $hook) :
                        $jsonData = json_encode(array(
                            "data"=>$hook->getHookId()
                        ));
                            ?>
                    <tr>
				<td><?php echo ($hook->getHookId() == NULL ? GeneralService::GENERAL_EMPTY_FIELD : $hook->getHookId())?></td>
				<td><?php echo ($hook->getPolicyEndDate() == NULL ? GeneralService::GENERAL_EMPTY_FIELD : $this->dateFormat($hook->getPolicyEndDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_us"))?></td>
				<td><a 
				style="width: 100%;" id="sending_data_button"
								data-ajax-loader="sendreminder"
								class=" ajax_element btn btn-primary btn-xs"
								data-json='<?php echo $jsonData; ?>'
								data-href="<?php echo $this->url("policy/default", array("action"=>"policyhookreminder"))?>">Send Reminder</a> 
					<div style="text-align: center;">
							<i id="sendreminder" class="fa  fa-lg"
								style="display: none;"><img alt=""
								src="<?php  echo $this->basepath("/processin.gif")?>" height=25></i>
						</div>
						</td>


			</tr>
                    <?php
                        endforeach
                        ;
                    } else {
                        ;

                        echo "No Outstanding renewable policy request";
                    }
                    ?>
                    </tbody>
	</table>
</div>