<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Proposal\Module'                        => __DIR__ . '/Module.php',
    'Proposal\Controller\IndexController' => __DIR__ . '/src/Proposal/Controller/IndexController.php',
    'ProposalTest\Framework\TestCase'        => __DIR__ . '/tests/Proposal/Framework/TestCase.php',
    'ProposalTest\SampleTest'                => __DIR__ . '/tests/Proposal/SampleTest.php',
);
