<?php
    
    echo $this->form()->openTag($paymentForm)?>
              <div id="billing" class="tab-pane">
            
              <?php  echo $this->partial("transaction_user_card_payment_snipet", array("payForm"=>$paymentForm->get("card_payment"), "invoice"=>$invoiceEntity))?>
               <i id="myLoader" class="fa  fa-pulse fa-lg"
										style="display: none;"><img alt=""
										src="<?php  echo $this->basepath("/animated-loading-gif-2.gif")?>"
										height=100></i>

									
									<?php
                echo $this->formrow($paymentForm->get("csrf"));
                echo $this->formrow($paymentForm->get("submit"))?>

									<div class="media v-middle s-container">

										<div class="media-right">
										
                  
<!--                     <a href="#modal-update-credit-card" data-toggle="modal" class="btn btn-white paper-shadow relative" data-animated data-z="0.5" data-hover-z="1" href="">Add Credit Card</a> -->
										</div>
									</div>

								</div>
<?php  echo $this->form()->closeTag(); ?>