<?php
echo $this->headtitle("Invoices");

if ($this->identity()) {
    ?>

<div class="row">
<?php  echo $this->partial("general-error-ponters") ?>
	<!-- /.col -->
	<div class="col-md-9 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Invoices</h2>

				<div class="clearfix"></div>
			</div>
			<div class="x_content">


				<div class="col-md-12 col-sm-12 col-xs-12">


					<div class="x_content">
						<!-- 						<p class="text-muted font-13 m-b-30">This example shows -->
						<!-- 							FixedHeader being styling by the Bootstrap CSS framework.</p> -->
						<div class="table-responsive datatables">
							<table id="datatable"
								class="table table-striped table-bordered">
								<thead>

									<tr>
										<th>INVOICE No.</th>
										<th>Customer Details</th>
										<th>Invoice Category</th>
										<th>Amount</th>
										<th>Due Date</th>
										<th>Actions</th>
									</tr>
								</thead>


								<tbody>
									<?php  echo $this->partial('transaction-invoice-all-snipet', array("invoices"=>$invoices))?>
									
								</tbody>
							</table>
						</div>
					</div>



				</div>
			</div>
		</div>
		<!-- /.nav-tabs-custom -->
	</div>
	<!-- /.col -->

	<div class="col-md-3 col-xs-12">

		<div class="x_panel">

			<div class="x_content">
				<img alt="" style='width: 100%;'
					src="<?php echo $this->basepath("imappadd/banner1.jpg")?>">
			</div>
		</div>
	</div>

</div>
<?php }?>
<br>




<?php

echo $this->headScript()
    ->appendFile($this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js'))
    ->appendFile($this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js'));
?>
<!-- <script src="../vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script> -->
<script>
      $(document).ready(function() {
        var handleDataTableButtons = function() {
          if ($("#datatable-buttons").length) {
            $("#datatable-buttons").DataTable({
              dom: "Bfrtip",
              buttons: [
                {
                  extend: "copy",
                  className: "btn-sm"
                },
                {
                  extend: "csv",
                  className: "btn-sm"
                },
                {
                  extend: "excel",
                  className: "btn-sm"
                },
                {
                  extend: "pdfHtml5",
                  className: "btn-sm"
                },
                {
                  extend: "print",
                  className: "btn-sm"
                },
              ],
              responsive: true
            });
          }
        };

        TableManageButtons = function() {
          "use strict";
          return {
            init: function() {
              handleDataTableButtons();
            }
          };
        }();

        $('#datatable').dataTable({
        		ordering: false
        });

        $('#datatable-keytable').DataTable({
          keys: true
        });

        $('#datatable-responsive').DataTable();

        $('#datatable-scroller').DataTable({
          ajax: "js/datatables/json/scroller-demo.json",
          deferRender: true,
          scrollY: 380,
          scrollCollapse: true,
          scroller: true
        });

        $('#datatable-fixed-header').DataTable({
          fixedHeader: true
        });

        var $datatable = $('#datatable-checkbox');

        $datatable.dataTable({
          'order': [[ 1, 'desc' ]],
          'columnDefs': [
            { orderable: false, targets: [0] }
          ]
        });
        $datatable.on('draw.dt', function() {
          $('input').iCheck({
            checkboxClass: 'icheckbox_flat-green'
          });
        });

        TableManageButtons.init();
      });
    </script>