<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Claims\Module' => __DIR__ . '/Module.php',
    'Claims\Controller\ClaimsController' => __DIR__ . '/src/Claims/Controller/ClaimsController.php',
    'ClaimsTest\Framework\TestCase' => __DIR__ . '/tests/Claims/Framework/TestCase.php',
    'ClaimsTest\SampleTest' => __DIR__ . '/tests/Claims/SampleTest.php'
);
