<?php
echo $this->headtitle("Add Staff");
$staffForm = $this->form;
$registeredStaff = $this->registeredStaff;

$flashMessenger = $this->flashMessenger()
    ->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

$staffForm->prepare()?>
<div id="wasabi_modal"></div>
<div class="row">
	<div class="col-md-9 col-sm-9 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Register Staff</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


				</ul>
				<div class="clearfix"></div>
			</div>
			
 <?php echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger')); ?>
 <?php echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info')); ?>
 <?php echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning')); ?>
 <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>

			<div class="x_content">
				
			<?php echo $this->partial("broker-tool-add-staff-fieldset-snippet", array("staffForm"=>$staffForm))?>
			
			</div>
		</div>
	</div>

	<div class="col-md-3 col-sm-12 col-xs-12">
		<div>
			<div class="x_title">
				<h2>Registered Staffs</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


				</ul>
				<div class="clearfix"></div>
			</div>
			<ul class="list-unstyled top_profiles scroll-view">
                          
                          <?php  echo $this->partial('registered-staff-snipet', array('staffs'=>$registeredStaff))?>
				<li class="media event"><a
					class="pull-left border-green profile_thumb"> <i
						class="fa fa-user green"></i>
				</a></li>
				
				<li class="media event"><a
					class="pull-left border-green profile_thumb"> <i
						class="fa fa-user green"></i>
				</a></li>
				<li class="media event"><a
					class="pull-left border-green profile_thumb"> <i
						class="fa fa-user green"></i>
				</a></li>
				<li class="media event"><a
					class="pull-left border-green profile_thumb"> <i
						class="fa fa-user green"></i>
				</a></li>
				<li class="media event"><a
					class="pull-left border-green profile_thumb"> <i
						class="fa fa-user green"></i>
				</a></li>
				<li class="media event"><a
					class="pull-left border-green profile_thumb"> <i
						class="fa fa-user green"></i>
				</a></li>
				<li class="media event"><a
					class="pull-left border-green profile_thumb"> <i
						class="fa fa-user green"></i>
				</a></li>
				<li class="media event"><a
					class="pull-left border-green profile_thumb"> <i
						class="fa fa-user green"></i>
				</a></li>
			</ul>
		</div>
	</div>


</div>

<div class="row">
	<div class="col-md-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Registered Staff</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">

				<p>List of Registered Staff</p>

				<!-- start project list -->
				<div class="table-responsive">
					<table
						<?php
    
    if (count($registeredStaff) != 0) {
        echo "id='datatable'";
    }
    ?>
						class="table table-striped projects ">
						<thead>
							<tr>
								<th>#</th>
								<th>Staff Details</th>
								<th>Last Login</th>
								<!--                           <th>Project Progress</th> -->
								<th></th>
								<th></th>
							</tr>
						</thead>
						<tbody>
                      <?php
                    
                    if (count($registeredStaff) == 0) {
                        echo "No Staff Registered";
                    } else {
                        foreach ($registeredStaff as $reg) {
                            ?>
                        <tr>
								<td>#</td>
								<td><a class="ajax_element" id="sendingData"
									data-href="viewstaffmodal"
									data-json='{"data":"<?= $reg->getBrokerChildUid() ?>"}'><?php  echo $reg->getFullName() ?></a>
									<br /> <small>Created <?php echo $this->dateFormat($reg->getCreatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT, "en_us")?></small>
								</td>
								<td>
                            <?php if($userEntity = $this->identity()){ 
//                                 echo $this->dateFormat($userEntity->getLastLogin()->getLastlogin(), IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT, "en_us");
                                echo ($reg->getUser()->getLastLogin() != NULL ? $this->dateFormat($reg->getUser()->getLastLogin()->getLastlogin(), IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT, "en_us") : "Not logged in yet");
                            }?>
                          </td>
								<!--                           <td class="project_progress"> -->
								<!--                             <div class="progress progress_sm"> -->
								<!--                               <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="57"></div> -->
								<!--                             </div> -->
								<!--                             <small>57% Complete</small> -->
								<!--                           </td> -->
								<td><a class="btn btn-info btn-xs ajax_element" id="sendingData"
									data-href="changephonemodal" style="width: 80%"
									data-json='{"data":"<?= $reg->getBrokerChildUid() ?>"}'><i
										class="fa fa-phone"></i> Change Phone </a><i
									class="fa fa-info-circle" data-toggle="tooltip"
									data-placement="top"
									title="All customer assigned to the previous phone number would be reassigned to the new phone number "></i><br>
									<a class="btn btn-success btn-xs ajax_element"
									style="width: 80%" id="sendingData"
									data-href="changeemailmodal"
									data-json='{"data":"<?= $reg->getBrokerChildUid() ?>"}'><i
										class="fa fa-envelope"></i> Change Email </a><i
									class="fa fa-info-circle" data-toggle="tooltip"
									data-placement="top"
									title="All customer assigned to the previous email would be reassigned to the new email"></i></td>
								<td><a class="btn btn-info btn-xs ajax_element" id="sendingData"
									data-href="editstaffmodal"
									data-json='{"data":"<?= $reg->getBrokerChildUid() ?>"}'><i
										class="fa fa-retweet"></i> Edit</a> <i
									class="fa fa-info-circle" data-toggle="tooltip"
									data-placement="top"
									title="Make changes to the names and password of the stafff"></i><br>
								<a class="btn btn-primary btn-xs ajax_element" id="sendingData"
									data-href="viewstaffmodal"
									data-json='{"data":"<?= $reg->getBrokerChildUid() ?>"}'><i
										class="fa fa-eye"></i> View</a></td>
							</tr>
                        <?php }}?>
                        
                      </tbody>
					</table>
				</div>
				<!-- end project list -->

			</div>
		</div>
	</div>
</div>
<?php

echo $this->headScript()->appendFile($this->basePath('js/jquery.mask.min.js'))?>

<script
	src="<?php echo $this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.flash.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-scroller/js/datatables.scroller.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/jszip/dist/jszip.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/pdfmake/build/pdfmake.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/pdfmake/build/vfs_fonts.js') ?>"></script>
<script>
      $(document).ready(function() {
        var handleDataTableButtons = function() {
          if ($("#datatable-buttons").length) {
            $("#datatable-buttons").DataTable({
              dom: "Bfrtip",
              buttons: [
                {
                  extend: "copy",
                  className: "btn-sm"
                },
                {
                  extend: "csv",
                  className: "btn-sm"
                },
                {
                  extend: "excel",
                  className: "btn-sm"
                },
                {
                  extend: "pdfHtml5",
                  className: "btn-sm"
                },
                {
                  extend: "print",
                  className: "btn-sm"
                },
              ],
              responsive: true
            });
          }
        };

        TableManageButtons = function() {
          "use strict";
          return {
            init: function() {
              handleDataTableButtons();
            }
          };
        }();

        $('#datatable').dataTable();

        $('#datatable-keytable').DataTable({
          keys: true
        });

        $('#datatable-responsive').DataTable();

        $('#datatable-scroller').DataTable({
          ajax: "js/datatables/json/scroller-demo.json",
          deferRender: true,
          scrollY: 380,
          scrollCollapse: true,
          scroller: true
        });

        $('#datatable-fixed-header').DataTable({
          fixedHeader: true
        });

        var $datatable = $('#datatable-checkbox');

        $datatable.dataTable({
          'order': [[ 1, 'asc' ]],
          'columnDefs': [
            { orderable: false, targets: [0] }
          ]
        });
        $datatable.on('draw.dt', function() {
          $('input').iCheck({
            checkboxClass: 'icheckbox_flat-green'
          });
        });

        TableManageButtons.init();
      });
    </script>

<script type="text/javascript">


        $(document).ready(function () {
            
            $('.phone').mask('00000000000');
            
            

        });

        // for the type of customer
        
    </script>