<?php


?>
<div class="row">
<?php ?>
		<div class='col-md-3 col-sm-3 col-xs-12'>
			<br> <br> <br>
      <?php  echo $this->partial("settings-navigation")?>
    </div>
<?php
$this->headtitle("Flutterwave Account");

    $flutterForm = $this->flutterForm;
    $flutterForm->get("submit")->setAttributes(array(
        "value"=>"EDIT ACCOUNT"
    ));
    $flutterFieldset = $flutterForm->get("brokerFlutterwaveFieldset");
    $flutterForm->prepare();
    $flashMessenger = $this->flashMessenger()
        ->setMessageOpenFormat("<div%s>
     <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>
         &times;
     </button>
     <ul><li style='color: red'>")
        ->setMessageSeparatorString("</li><li>")
        ->setMessageCloseString('</li></ul></div>');
    ?>


	
	<div class="col-md-9 col-sm-9  col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>
						<i class="fa fa-bars"></i> Payment Gateway Setup
					</h2>
				<?php echo $flashMessenger->render('error',   array('alert', 'alert-dismissable', 'alert-danger')); ?>
 <?php echo $flashMessenger->render('info',    array('alert', 'alert-dismissable', 'alert-info')); ?>
 <?php echo $flashMessenger->render('default', array('alert', 'alert-dismissable', 'alert-warning')); ?>
 <?php echo $flashMessenger->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
				<ul class="nav navbar-right panel_toolbox">
						<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">


					<?php   echo  $this->form()->openTag($flutterForm); ?>
							<br>



								<div class="form-group">
							
								<?php  echo $this->formLabel($flutterFieldset->get('merchantId'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php  echo $this->formElement($flutterFieldset->get('merchantId'));?>
									
								</div>

									<div style="font-size: 9px; color: red;">
		
								<?php  echo $this->formElementErrors($flutterFieldset->get('merchantId'));  // this defines the error?> 
							</div>
									<div id="progressNumber"></div>
								</div>

								<div class="form-group">
							
								<?php  echo $this->formLabel($flutterFieldset->get('encryptKey'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php  echo $this->formElement($flutterFieldset->get('encryptKey'));?>
									
								</div>

									<div style="font-size: 9px; color: red;">
		
								<?php  echo $this->formElementErrors($flutterFieldset->get('encryptKey'));  // this defines the error?> 
							</div>
									<div id="progressNumber"></div>
								</div>

								<div
									class="form-group col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
									
							<?php  echo $this->formrow($flutterForm->get('submit'))?>
							</div>
							
								<?php   echo  $this->form()->closeTag();?>

				</div>
			</div>
		</div>
		</div>