<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Job\Module'                        => __DIR__ . '/Module.php',
    'Job\Controller\JobController' => __DIR__ . '/src/Job/Controller/JobController.php',
    'JobTest\Framework\TestCase'        => __DIR__ . '/tests/Job/Framework/TestCase.php',
    'JobTest\SampleTest'                => __DIR__ . '/tests/Job/SampleTest.php',
);
