<?php
echo $this->headtitle('Company Policy');
if ($this->identity()){
?>
<div class="row">
	<div class="col-md-9 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Copmay Policies</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<table class="table table-striped projects">
					<thead>
						<tr>
							<th >Policy ID</th>
							<th >Title</th>
							<th>Policy</th>
							<th>Status</th>
							<th style="width: 20%">Action</th>
						</tr>
					</thead>
					<tbody>
			<?php // echo $this->partial('claims-all-broker-snipet', array('claims'=>$claims))?>
				  </tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<?php }?>