<?php

echo $this->headtitle("My Policy:Brokers:");
$policy = $this->policy;

if ($this->identity()){
?>


<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>My Customer Policies</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<div class="row">
				 <div class="clearfix"></div>
				 <?php echo $this->partial('policy-my-policy-snipet', array("policyy"=>$policy));?>
				</div>
			</div>
		</div>
	</div>
</div>

<?php }?>