<div id="success"></div>
	<div id="error"></div>

	<i id="myLoader" class="fa  fa-pulse fa-lg" style="display: none;"><img
		alt=""
		src="<?php  echo $this->basepath("/animated-loading-gif-2.gif")?>"
		height=100></i>
		
<?php
$objectForm->prepare();
$objectForm->get("submit")->setAttributes(array(
    "value"=>"UPDATE"
));
echo $this->form()->openTag($objectForm);
//echo $this->objectCompleteObjectPartialFormViewHelper($objectEntity, $objectForm);
echo $this->form()->closeTag() ;
//echo $objectEntity->getObjectName();
?>
