<div id="success"></div>
	<div id="error"></div>

	<i id="myLoader" class="fa  fa-pulse fa-lg" style="display: none;"><img
		alt=""
		src="<?php  echo $this->basepath("/animated-loading-gif-2.gif")?>"
		height=100></i>
<div id="res">
<?php
$objectForm->get("objectFieldset")
    ->get("objectType")
    ->setAttributes(array(
    "disabled" => "disabled"
));
$objectForm->get("submit")->setAttributes(array(
    "value" => "UPDATE"
));
$objectForm->prepare();
echo $this->form()->openTag($objectForm);
?>

<?php 
echo $this->partial("object-form-snipet", array(
    "objectField" => $objectForm->get("objectFieldset")
));
echo $this->formrow($objectForm->get("csrf"));
echo $this->formsubmit($objectForm->get("submit"));
echo $this->form()->closeTag();
?>

</div>