
<div id="success"></div>
	<div id="error"></div>

	<i id="myLoader" class="fa  fa-pulse fa-lg" style="display: none;"><img
		alt=""
		src="<?php  echo $this->basepath("/animated-loading-gif-2.gif")?>"
		height=100></i>
		<div id="res">
		<?php
		$objectBuildingForm->prepare();;
		echo $this->form()->openTag($objectBuildingForm);
		echo $this->partial("object-building-data-snipet", array("objectBuilding"=>$objectBuildingForm->get("objectBuildingFieldset")));
		echo $this->formrow($objectBuildingForm->get("csrf"));
		echo $this->formsubmit($objectBuildingForm->get("submit"));
		echo $this->form()->closeTag();


?>
</div>