<?php
use Zend\Session\Container;

$microFieldsetCounterSession = new Container("micro_fieldset_counter_session");
$countId = "count" . $microFieldsetCounterSession->agricProductList;
?>

<div id="<?= $countId ?>">
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('propertyName'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('propertyName'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Property Name"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('propertyName'));  // this defines the error?> 
							</div>
	</div>
	
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('value'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('value'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Property Value"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('value'));  // this defines the error?> 
							</div>
	</div>
	
	
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('desc'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('desc'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Property Description"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('desc'));  // this defines the error?> 
							</div>
	</div>
	<?php

$json = json_encode(array(
    "data" => $countId
));
?>
	<div class="form-group">
		<a id="sending_data_button"
			class="ajax_element btn btn-danger btn-xs pull-right"
			data-json='<?php  echo $json ?>'
			data-href="<?php echo $this->url("proposalmodal/default", array("action"=>"removediv")) ?>">remove</a>
	</div>
	<hr>
</div>
