<?php
use Zend\Session\Container;

$microFieldsetCounterSession = new Container("micro_fieldset_counter_session");
$countId = "count" . $microFieldsetCounterSession->buglarSafeDetails;
?>
<div id="<?= $countId ?>">
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('productName'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('productName'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Product Name"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('productName'));  // this defines the error?> 
							</div>
	</div>
	
	
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('maker'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('maker'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Product Make"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('maker'));  // this defines the error?> 
							</div>
	</div>
	
	
	
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('model'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('model'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Product Model"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('model'));  // this defines the error?> 
							</div>
	</div>
	
	
	
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('cost'))?>
								<div class="col-md-1 col-sm-1 col-xs-1"> &#8358;</div>
								<div class="col-md-6 col-sm-6 col-xs-10"> 
								<?php echo $this->formElement($field->get('cost'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Product Price"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('cost'));  // this defines the error?> 
							</div>
	</div>
	
	
	
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('size'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-110">
								<?php echo $this->formElement($field->get('size'));?>
									
								</div>
								<div class="col-md-2 col-sm-2 col-xs-2">
								kg
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Product Name"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('size'));  // this defines the error?> 
							</div>
	</div>
	
		<?php  $json = json_encode(array(
    "data"=>$countId 
                ));
?>
	<div class="form-group">
		<a id="sending_data_button" class="ajax_element btn btn-danger btn-xs pull-right"
			 data-json='<?php  echo $json ?>'
			data-href="<?php echo $this->url("proposalmodal/default", array("action"=>"removediv")) ?>">remove</a>
	</div>
	<hr>
</div>