<?php 
$cropAgricInsuranceFieldset = $form->get("cropAgricInsuranceFieldset");
?>

<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('coverStartDate'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('coverStartDate'));?>
									
								</div> <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Prefered date for cover to start"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('coverStartDate'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('coverEndDate'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('coverEndDate'));?>
									
								</div>
								<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Prefered date for cover to end"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('coverEndDate'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('farmAddress'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('farmAddress'));?>
									
								</div>
								<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Location of farm"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('farmAddress'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('farmNearestVillage'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('farmNearestVillage'));?>
									
								</div>
								<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Nearest Village or landmark to identify the farm"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('farmNearestVillage'));  // this defines the error?> 
							</div>
</div>



<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('farmState'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('farmState'));?>
									
								</div>
								<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="State farm is located"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('farmState'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('farmSize'))?>
								
								<div class="col-md-5 col-sm-5 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('farmSize'));?>
									
								</div> sqm <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Size of farm in square meters"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('farmState'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('farmAreaPlanted'))?>
								
								<div class="col-md-5 col-sm-5 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('farmAreaPlanted'));?>
									
								</div> sqm <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Area active plantation is situated is square meters"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('farmAreaPlanted'));  // this defines the error?> 
							</div>
</div>



<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('cropPlantingDate'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('cropPlantingDate'));?>
									
								</div>
								<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Estimated planting date"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('cropPlantingDate'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('estimatedHarvetDate'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('estimatedHarvetDate'));?>
									
								</div>
								<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Estimated Date of harvest"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('estimatedHarvetDate'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('seasonCommencement'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('seasonCommencement'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('seasonCommencement'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('seasonEnd'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('seasonEnd'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('seasonEnd'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('yearInBusiness'))?>
								
								<div class="col-md-5 col-sm-5 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('yearInBusiness'));?>
									
								</div> <strong>Years</strong>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('yearInBusiness'));  // this defines the error?> 
							</div>
</div>

<hr>
<h4>Estimated Cost (&#8358;)</h4>

<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('estimatedCostLandClearing'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('estimatedCostLandClearing'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('estimatedCostLandClearing'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('estimatedCostPlanting'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('estimatedCostPlanting'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('estimatedCostPlanting'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('estimatesCostIrrigation'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('estimatesCostIrrigation'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('estimatesCostIrrigation'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('estimatedCostWeedPestControl'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('estimatedCostWeedPestControl'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('estimatedCostWeedPestControl'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('estinmatedCostTransportation'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('estinmatedCostTransportation'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('estinmatedCostTransportation'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('estimatedCostInterestLoan'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('estimatedCostInterestLoan'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('estimatedCostInterestLoan'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('estmatedCostHarvesting'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('estmatedCostHarvesting'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('estmatedCostHarvesting'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('estimatedCostMiscellanous'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('estimatedCostMiscellanous'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('estimatedCostMiscellanous'));  // this defines the error?> 
							</div>
</div>
<hr>

<h4>Crop Details</h4>

<div class="form-group">
	<a id="btn2" class="ajax_element btn btn-default btn-xs pull-right"
		data-json='{"type":"standard"}'
		data-href="<?php echo $this->url("proposalmodal/default", array("action"=>"cropstafflist")) ?>">
		Staff Details</a>
</div>

<div class="form-group" id="div_crop_staff_fieldset"
	style="margin: 10px; padding: 10px; background: #c2f4e0;">
<?php  //echo $this->partial("imservice_motor_non_standard_inner", array("nonStandardCollecton"=>$nonStandardCollecton))?>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($cropAgricInsuranceFieldset->get('cropPerilCoverList'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($cropAgricInsuranceFieldset->get('cropPerilCoverList'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($cropAgricInsuranceFieldset->get('cropPerilCoverList'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">
	<a id="btn2" class="ajax_element btn btn-default btn-xs pull-right"
		data-json='{"type":"standard"}'
		data-href="<?php echo $this->url("proposalmodal/default", array("action"=>"cropagriclist")) ?>">
		Crop Details</a>
</div>

<div class="form-group" id="div_crop_agric_fieldset"
	style="margin: 10px; padding: 10px; background: #c2f4e0;">
<?php  //echo $this->partial("imservice_motor_non_standard_inner", array("nonStandardCollecton"=>$nonStandardCollecton))?>
</div>

<script type="text/javascript">


$("#cropPerilCoverList").chosen({width: "100%"});


    
  
    </script>
