<?php
use Zend\Session\Container;

$microFieldsetCounterSession = new Container("micro_fieldset_counter_session");
$countId = "count" . $microFieldsetCounterSession->cropStaffList;
?>

<div id="<?= $countId ?>">
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('post'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('post'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Staff Position/Post"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('post'));  // this defines the error?> 
							</div>
	</div>



	<div class="form-group">

								 <?php echo $this->formLabel($field->get('name'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php
        
echo $this->formElement($field->get('name'));
        
        ?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Staff Name"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('name'));  // this defines the error?> 
							</div>
	</div>



	<div class="form-group">

								 <?php echo $this->formLabel($field->get('qualification'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('qualification'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Staff Quailfication"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('qualification'));  // this defines the error?> 
							</div>
	</div>



	<div class="form-group">

								 <?php echo $this->formLabel($field->get('yearsInService'))?>
								
								<div class="col-md-5 col-sm-5 col-xs-5">
								<?php echo $this->formElement($field->get('yearsInService'));?>
									
								</div>
		<strong>years</strong> <i class="fa fa-info-circle"
			data-toggle="tooltip" data-placement="top"
			title="Number of years in service"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('yearsInService'));  // this defines the error?> 
							</div>
	</div>

<?php

$json = json_encode(array(
    "data" => $countId
));
?>

	<div class="form-group">
		<a id="sending_data_button"
			class="ajax_element btn btn-danger btn-xs pull-right"
			data-json='<?php  echo $json ?>'
			data-href="<?php echo $this->url("proposalmodal/default", array("action"=>"removediv")) ?>">remove</a>
	</div>
	<hr>
</div>