<?php
use Zend\Session\Container;
$microFieldsetCounterSession = new Container("micro_fieldset_counter_session");
$countId = "count" . $microFieldsetCounterSession->employeeLiabilityDetailFieldset;

?>

<div id="<?= $countId ?>">
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('employeeDescription'))?>
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($field->get('employeeDescription'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Employee Category/Description"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('employeeDescription'));  // this defines the error?> 
							</div>
	</div>

	<div class="form-group">

								 <?php echo $this->formLabel($field->get('numbersOfEmployee'))?>
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($field->get('numbersOfEmployee'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Number of employees in such category"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('numbersOfEmployee'));  // this defines the error?> 
							</div>
	</div>

	<div class="form-group">

								 <?php echo $this->formLabel($field->get('estimatedPeriodWage'))?>
								<div id="row">
			<div class="col-md-1 col-sm-1 col-xs-1">&#8358;</div>
			<div class="col-md-5 col-sm-5 col-xs-10">
								<?php echo $this->formElement($field->get('estimatedPeriodWage'));?>
									
								</div>
		</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Estimated wage"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('estimatedPeriodWage'));  // this defines the error?> 
							</div>
	</div>
	<?php

$json = json_encode(array(
    "data" => $countId
));
?>

	<div class="form-group">
		<a id="sending_data_button"
			class="ajax_element btn btn-danger btn-xs pull-right"
			data-json='<?php  echo $json ?>'
			data-href="<?php echo $this->url("proposalmodal/default", array("action"=>"removediv")) ?>">remove</a>
	</div>
	<hr>
</div>