<?php
$gitFieldset = $form->get("gitFieldset");

?>
<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('specificGoods'))?>
								
								<div class="col-md-8 col-sm-8 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('specificGoods'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('specificGoods'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('goodDescription'))?>
								
								<div class="col-md-8 col-sm-8 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('goodDescription'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('goodDescription'));  // this defines the error?> 
							</div>
</div>



<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('geographicalArea'))?>
								
								<div class="col-md-8 col-sm-8 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('geographicalArea'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('geographicalArea'));  // this defines the error?> 
							</div>
</div>


<div id="div_otherGeographicalArea" class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('otherGeographicalArea'))?>
								
								<div class="col-md-8 col-sm-8 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('otherGeographicalArea'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('otherGeographicalArea'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('transportMedium'))?>
								
								<div class="col-md-8 col-sm-8 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('transportMedium'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('transportMedium'));  // this defines the error?> 
							</div>
</div>

<div id="div_otherTransportMedium" class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('otherTransportMedium'))?>
								
								<div class="col-md-8 col-sm-8 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('otherTransportMedium'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('otherTransportMedium'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('isLockeNAttended'))?>
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('isLockeNAttended'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('isLockeNAttended'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('isAntiTheftDevice'))?>
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('isAntiTheftDevice'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('isAntiTheftDevice'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('antiTheftDevice'))?>
								
								<div class="col-md-8 col-sm-8 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('antiTheftDevice'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('antiTheftDevice'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('yearlyTotalEstimate'))?>
								
								<div class="col-md-8 col-sm-8 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('yearlyTotalEstimate'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('yearlyTotalEstimate'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('estimatedLimit'))?>
								
								<div class="col-md-8 col-sm-8 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('estimatedLimit'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('estimatedLimit'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('isOtherInsurance'))?>
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('isOtherInsurance'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('isOtherInsurance'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('isPreviousDecline'))?>
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('isPreviousDecline'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('isPreviousDecline'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('isIncreaseContribution'))?>
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('isIncreaseContribution'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('isIncreaseContribution'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('isRequireSpecialTerm'))?>
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('isRequireSpecialTerm'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('isRequireSpecialTerm'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($gitFieldset->get('specialTerm'))?>
								
								<div class="col-md-8 col-sm-8 col-xs-12">
								<?php echo $this->formElement($gitFieldset->get('specialTerm'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($gitFieldset->get('specialTerm'));  // this defines the error?> 
							</div>
</div>
<div class="form-group">
	<a id="btn2" class="ajax_element btn btn-default btn-xs pull-right"
		data-json='{"type":"standard"}' data-ajax-loader="microFieldset"
		data-href="<?php echo $this->url("proposalmodal/default", array("action"=>"gitvehiclelist")) ?>">
		Vehicle List <i
					id="microFieldset" class="fa fa-spinner  fa-pulse fa-lg"
					style="display: none;"> </i> </a>
</div>

<div id="gitVehicleList" style="margin: 10px; padding: 10px; background: #c2f4e0;">
</div>


<script type="text/javascript">


$("#specificGoods").chosen({width: "95%"});
    $(document).ready(function(){
        $("#div_otherGeographicalArea").hide();
        $("#div_otherTransportMedium").hide();
        $("#").hide();
        })
  
    </script>