<?php
use Zend\Session\Container;

$microFieldsetCounterSession = new Container("micro_fieldset_counter_session");
$countId = "count" . $microFieldsetCounterSession->goodslistFieldset;
?>

<div id="<?= $countId ?>">
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('goodsName'))?>
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($field->get('goodsName'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Name of Goods"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('goodsName'));  // this defines the error?> 
							</div>
	</div>
	
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('value'))?>
								<div class="col-md-1 col-sm-1 col-xs-1">
								&#8358;
								</div>
								<div class="col-md-5 col-sm-5 col-xs-10">
								<?php echo $this->formElement($field->get('value'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="Name of Goods"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('value'));  // this defines the error?> 
							</div>
	</div>
	
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('serialNumber'))?>
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($field->get('serialNumber'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top" title="A unique identifier of the good"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('serialNumber'));  // this defines the error?> 
							</div>
	</div>
	
	<?php

$json = json_encode(array(
    "data" => $countId
));
?>
	<div class="form-group">
		<a id="sending_data_button"
			class="ajax_element btn btn-danger btn-xs pull-right"
			data-json='<?php  echo $json ?>'
			data-href="<?php echo $this->url("proposalmodal/default", array("action"=>"removediv")) ?>">remove</a>
	</div>
	<hr>

</div>