<?php
$personalAccidentFieldset = $form->get("personalAccidentFieldset");
?>

<div class="form-group">

								 <?php echo $this->formLabel($personalAccidentFieldset->get('estimatedPremium'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($personalAccidentFieldset->get('estimatedPremium'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Nature of safe,please provide the make and type"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($personalAccidentFieldset->get('estimatedPremium'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($personalAccidentFieldset->get('coverStartDate'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($personalAccidentFieldset->get('coverStartDate'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Nature of safe,please provide the make and type"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($personalAccidentFieldset->get('coverStartDate'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($personalAccidentFieldset->get('coverEndDate'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($personalAccidentFieldset->get('coverEndDate'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Nature of safe,please provide the make and type"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($personalAccidentFieldset->get('coverEndDate'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($personalAccidentFieldset->get('isEngageInHazardSport'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($personalAccidentFieldset->get('isEngageInHazardSport'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Nature of safe,please provide the make and type"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($personalAccidentFieldset->get('isEngageInHazardSport'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($personalAccidentFieldset->get('hazardDetails'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($personalAccidentFieldset->get('hazardDetails'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Nature of safe,please provide the make and type"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($personalAccidentFieldset->get('hazardDetails'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($personalAccidentFieldset->get('isAnyAffectedByDisease'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($personalAccidentFieldset->get('isAnyAffectedByDisease'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Nature of safe,please provide the make and type"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($personalAccidentFieldset->get('isAnyAffectedByDisease'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($personalAccidentFieldset->get('diseaseDetails'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($personalAccidentFieldset->get('diseaseDetails'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Nature of safe,please provide the make and type"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($personalAccidentFieldset->get('diseaseDetails'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($personalAccidentFieldset->get('isPreviousInsurer'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($personalAccidentFieldset->get('isPreviousInsurer'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Nature of safe,please provide the make and type"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($personalAccidentFieldset->get('isPreviousInsurer'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($personalAccidentFieldset->get('isPreviousDecline'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($personalAccidentFieldset->get('isPreviousDecline'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Nature of safe,please provide the make and type"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($personalAccidentFieldset->get('isPreviousDecline'));  // this defines the error?> 
							</div>
</div>