<?php
use Zend\Session\Container;

$microFieldsetCounterSession = new Container("micro_fieldset_counter_session");
$countId = "count" . $microFieldsetCounterSession->publicLiabilityEmployeeDetails;
?>
<div id="<?= $countId ?>">
<div class="form-group">

								 <?php echo $this->formLabel($field->get('noOfEmployees'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('noOfEmployees'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Number Of employees?"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('noOfEmployees'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">

								 <?php echo $this->formLabel($field->get('natureOfWork'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('natureOfWork'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Number Of employees?"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('natureOfWork'));  // this defines the error?> 
							</div>
</div>


<div class="form-group">

								 <?php echo $this->formLabel($field->get('insuranceConnection'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('insuranceConnection'));?>
									
								</div>
	<i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
		title="Number Of employees?"></i>
	<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('insuranceConnection'));  // this defines the error?> 
							</div>
</div>

<?php

$json = json_encode(array(
    "data" => $countId
));
?>
	<div class="form-group">
		<a id="sending_data_button"
			class="ajax_element btn btn-danger btn-xs pull-right"
			data-json='<?php  echo $json ?>'
			data-href="<?php echo $this->url("proposalmodal/default", array("action"=>"removediv")) ?>">remove</a>
	</div>
	<hr>

</div>