<?php
use Zend\Session\Container;

$microFieldsetCounterSession = new Container("micro_fieldset_counter_session");
$countId = "count" . $microFieldsetCounterSession->workmenDecreeList;
?>
<div id="<?= $countId ?>">
	<div class="form-group">

								 <?php echo $this->formLabel($field->get('employeeCategoree'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('employeeCategoree'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top"
			title="Category of the employee, Senior Staff, Junior Staff"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('employeeCategoree'));  // this defines the error?> 
							</div>
	</div>



	<div class="form-group">

								 <?php echo $this->formLabel($field->get('numberOfEmployee'))?>
								
								<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $this->formElement($field->get('numberOfEmployee'));?>
									
								</div>
		<i class="fa fa-info-circle" data-toggle="tooltip"
			data-placement="top"
			title="Number of employee to be covered in this categroy"></i>
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('numberOfEmployee'));  // this defines the error?> 
							</div>
	</div>


	<div class="form-group">

								 <?php echo $this->formLabel($field->get('cashCompensation'))?>
								
			<div class="col-md-1 col-sm-1 col-xs-1">&#8358;</div>
			<div class="col-md-6 col-sm-6 col-xs-10">
								<?php echo $this->formElement($field->get('cashCompensation'));?>
									
								</div>

			<i class="fa fa-info-circle" data-toggle="tooltip"
				data-placement="top"
				title="Cash compensation "></i>
		
	</div>

	<div class="form-group">

								 <?php echo $this->formLabel($field->get('otherCompensation'))?>
								
			<div class="col-md-1 col-sm-1 col-xs-1">&#8358;</div>
			<div class="col-md-6 col-sm-6 col-xs-10">
								<?php echo $this->formElement($field->get('otherCompensation'));?>
									
								</div>

			<i class="fa fa-info-circle" data-toggle="tooltip"
				data-placement="top"
				title="Value of Food, Fuel and Quarters or other Considerations in addition to money earnings"></i>
		
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('otherCompensation'));  // this defines the error?> 
							</div>
	</div>

	<div class="form-group">

								 <?php echo $this->formLabel($field->get('totalCompensation'))?>
								
			<div class="col-md-1 col-sm-1 col-xs-1">&#8358;</div>
			<div class="col-md-6 col-sm-6 col-xs-10">
								<?php echo $this->formElement($field->get('totalCompensation'));?>
									
								</div>

			<i class="fa fa-info-circle" data-toggle="tooltip"
				data-placement="top" title="Sum total of listed compensation"></i>
		
		<div style="font-size: 9px; color: red;">
								<?php echo  $this->formElementErrors($field->get('totalCompensation'));  // this defines the error?> 
							</div>
	</div>

<?php

$json = json_encode(array(
    "data" => $countId
));
?>
	<div class="form-group">
		<a id="sending_data_button"
			class="ajax_element btn btn-danger btn-xs pull-right"
			data-json='<?php  echo $json ?>'
			data-href="<?php echo $this->url("proposalmodal/default", array("action"=>"removediv")) ?>">remove</a>
	</div>
	<hr>
</div>