<?php
//$offerInfo = $this->offerInfo;
$userInfo = $this->userInfo;
echo $this->headtitle('Edit Offer '.$offerInfo->getId());
?>

<div class="row" ng-app="OfferModule">
              <div class="col-md-6  col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2><?php echo "OFFER NAME:  ". $offerInfo->getOfferName()?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  
               <div class="profile_details">
                        <div class="well profile_view">
                          <div class="col-sm-12">
                            <h2 class="brief"><i>Users Profile</i></h2>
                            <div class="left col-xs-7">
                              <h2><?php //echo $userInfo->getLastname()." ".$userInfo->getFirstname(); ?> </h2>
                              <p><strong>Email: </strong> <?php echo $userInfo->getEmail();?> </p>
                              <?php //$contact = $userInfo->getContact();?>
                              <ul class="list-unstyled">
                                <li><i class="fa fa-building"></i> Address: <?php //echo $contact->getAddress1();?></li>
                                <li><i class="fa fa-phone"></i> Phone #: <?php //echo $contact->getPhoneNumber1();?> </li>
                              </ul>
                              <br>  <br>  <br>  <br>  <br>  <br>  <br>  <br>  <br>  <br>  <br>  <br>  <br>  <br>  <br>  <br>
                            </div>
                            <div class="right col-xs-5 text-center">
                              
                            </div>
                          </div>
                          <div class="col-xs-12 bottom text-center">
                            <div class="col-xs-12 col-sm-6 emphasis">
                              
                            </div>
                            <div class="col-xs-12 col-sm-6 emphasis">
<!--                               <button type="button" class="btn btn-success btn-xs"> <i class="fa fa-user"> -->
<!--                                 </i> <i class="fa fa-comments-o"></i> </button> -->
                              <button type="button" class="btn btn-primary btn-xs">
                                <i class="fa fa-user"> </i> View Profile
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                  
                   </div>
                </div>
              </div>
              
              <div class="col-md-6 col-xs-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Offer Premium:</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  
               The premium Status goes here 
                  
                   </div>
                </div>
              </div>
              
              
              
              <div class="col-md-6 col-xs-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Related Documents:</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  
               The premium Status goes here 
                  
                   </div>
                </div>
              </div>
              
              <div class="col-md-6 col-xs-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Property/Object:</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  
               Objects goes here 
                  
                   </div>
                </div>
              </div>
              
              
            </div>