<?php
echo $this->headtitle('Premium Invoice - New Offer')
?>

<div class="row" ng-app="OfferModule">
              <div class="col-md-9 col-xs-9">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Premium Invoice </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  
                  <?php echo $this->partial('invoice_offer_partial_view', array(
                      '$invoiceData'=>NULL,
                      'userInfo'=>NULL, //userInfo
                      'offerInfo'=>NULL, //
                      'payment'=>NULL ,//
                      'policy'=> NULL, // $policy
                  ))?>
                  
                   </div>
                </div>
              </div>
            </div>
            
            <?php

echo $this->headScript()
    ->appendFile($this->basePath('js/jquery.mask.min.js'))
    ->appendFile($this->basePath('angular/OfferModule.js'))
    ->appendFile($this->basePath('angular/controllers/offerController.js'));
?>