<?php
echo $this->headtitle("Active Offers");
$activeOffers = $this->offers;
if ($this->identity()) {
    ?>
<div class="row">
	<div class="col-md-9 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>View Active Offers</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>



				</ul>
				<div class="clearfix"></div>
			</div>
                  <?php  echo $this->partial("general-error-ponters")?>
                  <div class="x_content">

				<!--                     <p>Simple table with project listing with progress and editing options</p> -->

				<!-- start project list  -->
				<div class="table-responsive">

					<table
						<?php
    
if (count($activeOffers) != 0) {
        echo "id='datatable'";
    }
    ?>
						class="table table-striped table-bordered">
                     <?php
    
    if (count($activeOffers) == 0) {
        echo "<span>No Active Offer</span>";
    } else {
        ?>
                      <thead>
							<tr>
								<th style="width: 4%">#</th>
								<th style="width: 40%">Offer Information</th>

								<th>Status</th>
								<th style="width: 30%">Actions</th>
							</tr>
						</thead>
						<tbody>
                        <?php foreach ($activeOffers as $offer){?>
                        <tr>
								<td>#</td>
								<td><a><strong><?php echo strtoupper($offer->getOfferCode()); ?></strong></a>
									<br /> <a><?php echo ($offer->getOfferName() != NULL ? $offer->getOfferName() : "No Name indicated")?></a>
									<br /> <a><?php  echo ($offer->getOfferServiceType() == NULL ? "" : $offer->getOfferServiceType()->getInsuranceService())?></a>
									<br /> <small>Updated : <?php echo $this->dateFormat($offer->getUpdatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, "en_US")?></small>
								</td>


								<td>
                           <?php  echo ($offer->getOfferStatuses() != NULL ? $this->statusHelper($offer->getOfferStatuses()->getOfferStatusId()): 'No Status' )?>
                          </td>
								<td>
                           
                            
                            <?php  echo $this->offer_all_condition_button($offer)?>
                           
                          </td>
							</tr>
                        
                         <?php   }}?>  
                      </tbody>
					</table>
				</div>
				<!-- end project list -->

			</div>
		</div>
	</div>
	<div class="col-md-3 col-xs-1">

		<div class="x_panel">

			<div class="x_content">
				<img alt="" style='width: 100%;'
					src="<?php echo $this->basepath("imappadd/banner2.jpg")?>">
			</div>
		</div>
	</div>
</div>

<?php  }?>
<script
	src="<?php echo $this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.flash.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/datatables.net-scroller/js/datatables.scroller.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/jszip/dist/jszip.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/pdfmake/build/pdfmake.min.js') ?>"></script>
<script
	src="<?php echo $this->basePath('vendors/pdfmake/build/vfs_fonts.js') ?>"></script>
<script>
      $(document).ready(function() {
        var handleDataTableButtons = function() {
          if ($("#datatable-buttons").length) {
            $("#datatable-buttons").DataTable({
              dom: "Bfrtip",
              buttons: [
                {
                  extend: "copy",
                  className: "btn-sm"
                },
                {
                  extend: "csv",
                  className: "btn-sm"
                },
                {
                  extend: "excel",
                  className: "btn-sm"
                },
                {
                  extend: "pdfHtml5",
                  className: "btn-sm"
                },
                {
                  extend: "print",
                  className: "btn-sm"
                },
              ],
              responsive: true
            });
          }
        };

        TableManageButtons = function() {
          "use strict";
          return {
            init: function() {
              handleDataTableButtons();
            }
          };
        }();

        $('#datatable').dataTable();

        $('#datatable-keytable').DataTable({
          keys: true
        });

        $('#datatable-responsive').DataTable();

        $('#datatable-scroller').DataTable({
          ajax: "js/datatables/json/scroller-demo.json",
          deferRender: true,
          scrollY: 380,
          scrollCollapse: true,
          scroller: true
        });

        $('#datatable-fixed-header').DataTable({
          fixedHeader: true
        });

        var $datatable = $('#datatable-checkbox');

        $datatable.dataTable({
          'order': [[ 1, 'asc' ]],
          'columnDefs': [
            { orderable: false, targets: [0] }
          ]
        });
        $datatable.on('draw.dt', function() {
          $('input').iCheck({
            checkboxClass: 'icheckbox_flat-green'
          });
        });

        TableManageButtons.init();
      });
    </script>

