<?php

?>

<div class="form-group">
								<?php echo $this->formLabel( $coverNoteFieldset->get('cover_duration'))?> 
								<div class="col-md-6 col-sm-6 col-xs-12">
									<?php echo $this->formElement( $coverNoteFieldset->get('cover_duration'))?>  
								</div>
								
								<?php echo $this->formElementErrors( $coverNoteFieldset->get('cover_duration'))?> 
								
							</div>