<?php
echo $this->headTitle("Active Proposals");
if($this->identity()){
    ?>
<div class="row">
	<div class="col-md-9">
	<?php  echo $this->partial("general-error-ponters")?>
	<div class="panel panel-default">
           <div class="table-responsive">
              <table id="myTable"  class="table v-middle">
                <thead>
                  <tr>
                    <th width="20">
                      Creatd On 
                    </th>
                    <th>Proposal Info. </th>
                    <th>Proposaed Service</th>
                    <th>Proposed Insurer</th>
                    
                    <th class="text-right">Action</th>
                  </tr>
                </thead>
                <tbody id="responsive-table-body">
                  <?php  echo $this->partial("customer-proposal-my-proposal", array("proposals"=>$proposals))?>
                  
                </tbody>
              </table>
            </div>
            <!-- // Data table -->
          </div>
	</div>
	<div class="col-md-3">
	<?php  echo $this->partial("customer-board-featured-packages")?>
	</div>
</div>
<?php }?>