<?php

?>

<div class="form-group">
							
								<?php echo $this->formLabel($form->get('bankName'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($form->get('bankName'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
		<br>
								<?php echo $this->formElementErrors($form->get('bankName'));  // this defines the error?> 
							</div>
</div>

<div class="form-group">
							
								<?php echo $this->formLabel($form->get('bankAccountNo'))?> 
								
								<div class="col-md-6 col-sm-6 col-xs-12">
								<?php echo $this->formElement($form->get('bankAccountNo'));?>
									
								</div>
	<div style="font-size: 9px; color: red;">
		<br>
								<?php echo $this->formElementErrors($form->get('bankAccountNo'));  // this defines the error?> 
							</div>
</div>

<div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
 <i id="myLoader" class="fa fa-spinner fa-pulse fa-lg" style="display: none; color: red;">...Please Wait Getting Information</i> <?php echo $this->formrow($form->get('submit'))?>
 </div>