
<div id="wrapper-600">

		<ul class="accordion">
			
			<li id="one3" class="files">

				<a href="#one3">SMS</a>

				<ul class="sub-menu">
					
					<li><a href="<?php echo $this->url("s-m-s/default", array("action"=>'buy-sms'))?>"><em>01</em>Buy SMS<span>42</span></a></li>
					
<!-- 					<li><a href="#one3"><em>02</em>Skydrive<span>87</span></a></li> -->

<!-- 					<li><a href="#one3"><em>03</em>FTP Server<span>366</span></a></li> -->

				</ul>

			</li>
			
			<li id="two3" class="mail">

				<a href="#two3">Mail<span>26</span></a>

				<ul class="sub-menu">
					
					<li><a href="#two3"><em>01</em>Hotmail<span>9</span></a></li>
					
					<li><a href="#two3"><em>02</em>Yahoo<span>14</span></a></li>

					<li><a href="#two3"><em>03</em>Gmail<span>3</span></a></li>

				</ul>

			</li>
			
			<li id="three3" class="cloud">

				<a href="#three3">Cloud<span>58</span></a>

				<ul class="sub-menu">
					
					<li><a href="#three3"><em>01</em>Connect<span>12</span></a></li>
					
					<li><a href="#three3"><em>02</em>Profiles<span>19</span></a></li>

					<li><a href="#three3"><em>03</em>Options<span>27</span></a></li>

				</ul>

			</li>
			
			<li id="four3" class="sign">

				<a href="#four3">Sign Out</a>

				<ul class="sub-menu">
					
					<li><a href="#four3"><em>01</em>Log Out</a></li>
					
					<li><a href="#four3"><em>02</em>Delete Account</a></li>

					<li><a href="#four3"><em>03</em>Freeze Account</a></li>

				</ul>

			</li>
		
		</ul>
		
	</div>
<!--  Put the css of the menu here      -->

<?php echo $this->headLink()->appendStylesheet("/css/accordionmenu.css")?>