<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'GeneralServicer\Module' => __DIR__ . '/Module.php',
    'GeneralServicer\Controller\ServicerController' => __DIR__ . '/src/GeneralServicer/Controller/ServicerController.php',
    'GeneralServicerTest\Framework\TestCase' => __DIR__ . '/tests/GeneralServicer/Framework/TestCase.php',
    'GeneralServicerTest\SampleTest' => __DIR__ . '/tests/GeneralServicer/SampleTest.php'
);
