<?php
echo $this->headtitle("My Cover Note");
?>

<div class="row">
	<div class="col-md-9">
		<div class="col-md-12">
		<h3>COVERNOTE: <?php  echo strtoupper($coverNoteEntity->getCoverUid()) ?></h3>
			<div class="text-subhead-2 text-light"></div>
			<div class="panel panel-default paper-shadow" data-z="0.5">
				<div class="panel-body">
					<?php echo $this->partial("policy_covernote_view_snippet", array("coverNote"=>$coverNoteEntity, "brokerEntity"=>$brokerEntity))?>
	
				</div>
			</div>

		</div>
		<br />



	</div>

	<div class="col-lg-3 col-md-3 col-sm-3"> 
	<?php  echo $this->partial("customer-policy-menu")?>
	</div>
</div>