<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Proparty\Module'                        => __DIR__ . '/Module.php',
    'Proparty\Controller\PropartyController' => __DIR__ . '/src/Proparty/Controller/PropartyController.php',
    'PropartyTest\Framework\TestCase'        => __DIR__ . '/tests/Proparty/Framework/TestCase.php',
    'PropartyTest\SampleTest'                => __DIR__ . '/tests/Proparty/SampleTest.php',
);
