<?php
use Policy\Service\PolicyService;

$policyForm->prepare();
echo $this->form()->openTag($policyForm);
?>
<div id="div_insurer" class="form-group">
								<label class="control-label col-md-4 col-sm-4 col-xs-12">Insurer</label>
	<div class="col-md-6 col-sm-6 col-xs-12">
									<?php echo PolicyService::getInsurerName($policyEntity)?> 
								</div>

	
</div>
<?php
echo $this->partial("policy-generate-policy-form-snippet", array("policyFieldset"=>$policyForm->get("policyFieldset")));
echo $this->formsubmit($policyForm->get("submit"));
echo $this->form()->closeTag();

?>
<div style="text-align: center;">
								<i id="editpolicy" class="fa  fa-lg" style="display: none;"><img
									alt="" src="<?php  echo $this->basepath("/processin.gif")?>"
									height=50></i>
							</div>

<script>
$(document).ready(function(){
	//$("#div_insurer").hide();
})
</script>
