<?php
$count = 200;
$i = 0;
// var_dump($policy);
if (count($policy) != 0) {

    while ($i < count($policy) && count($policy) < $count) {

        ?>

<tr>
	<td><a
		href="<?php //echo $this->url("packages/default", array("action"=>"view", "id"=>$policy[$i]->getId()))?>"><?php // echo strtoupper(($policy[$i]->getPolicyCode() != NULL ? $policy[$i]->getPolicyCode() : " No Code"))?></a>

	</td>
	<td><?php  echo $policy[$i]->getCustomer()->getName() ?><br>
		<?php  echo $policy[$i]->getCustomer()->getUser()->getUserName()?><br>
		<?php  echo ($policy[$i]->getCustomer()->getUser()->getEmail() != NULL ? $policy[$i]->getCustomer()->getUser()->getEmail() : "No Email")?>
		</td>
	<td><strong>Policy Code: </strong><?php  echo $policy[$i]->getPolicy()->getPolicyCode() ?> <br>
		<strong>Poly Name: </strong><?php  echo ($policy[$i]->getPolicy()->getPolicyName() != NULL ? $policy[$i]->getPolicy()->getPolicyName() : "No Policy Name ")?><br>
		<strong>Status: </strong><?php  echo $this->statusHelper($policy[$i]->getPolicy()->getPolicyStatus()->getStatus())?><br>
		<strong>Expires : </strong><?php  echo $this->dateformat($policy[$i]->getPolicy()->getEndDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::SHORT, "en_us")?><br>
		<strong>Insurer : </strong><img alt=""
		src="<?php echo $this->insurerLogohelper($policy[$i]->getInsurer()->getId())?>"
		class="img-circle   img-responsive" width=100></td>



	<td>
	<div style='text-align: center;'>
	<i id='policyd<?php echo $policy[$i]->getPolicy()->getId()?>' class='fa fa-lg'
		style='display: none; text-align: center;'><img alt=''
		src='<?php echo  $this->basePath('/processin.gif')  ?>' height=30>
		<hr></i>
</div>
	<?php

        $json = json_encode(array(
            "data" => $policy[$i]->getPolicy()->getPolicyUid()
        ));
        $viewSon = json_encode(array(
            'data' => $policy[$i]->getPolicy()->getId()
        ));
        ?>
	<a data-ajax-loader="policyd<?php echo $policy[$i]->getPolicy()->getId()?>" id="sending_data_button"
		style="width: 100%" class="ajax_element btn btn-app"
		data-json='<?php echo $json ?>'
		data-href="<?php  echo $this->url("policy/default", array("action"=>"premanagemodal"))?>"><i
			class="fa fa-play"></i>MANAGE POLICY</a>
	<?php if($policy[$i]->getPolicy()->getPolicyStatus()->getId() == \Policy\Service\PolicyService::POLICY_STATUS_ISSUED_AND_VALID){ ?>
	<a data-ajax-loader="policyd<?php echo $policy[$i]->getPolicy()->getId()?>" id="sending_data_button"
		style="width: 100%" class="ajax_element btn btn-app"
		data-toggle="tooltip" data-placement="top" title="View the policy"
		data-json='<?php echo $viewSon ?>'
		data-href="<?php  echo $this->url("policy/default", array("action"=>"viewpolicymodal"))?>"
		style="width: 100%"> <i class="fa fa-eye"></i> VIEW POLICY
	</a>
	<?php
        }
        ?>
        
	<?php
        echo $this->policy_all_action_condition($policy[$i])?> 
        
	</td>

</tr>
<?php
        $i ++;
    }
}
?>