<?php
$policyRevokeForm->prepare();
echo $this->form()->openTag($policyRevokeForm);
echo $this->partial("policy_revoke_fieldset", array("policyRevokeForm"=>$policyRevokeForm));
?>

<?php
echo $this->formsubmit($policyRevokeForm->get("submit"));
?><?php
echo $this->form()->closeTag();

?>

<div style="text-align: center;">
								<i id="revoke" class="fa  fa-lg" style="display: none;"><img
									alt="" src="<?php  echo $this->basepath("/processin.gif")?>"
									height=50></i>
							</div>