<?php
$broker = $this->broker;
if ($broker != NULL) {
    $brokerName = $broker->getBrokerName();
    echo $this->headtitle($brokerName . " ");
    
    $form->prepare();
    ?>
	<?php  echo $this->partial("general-error-ponters")?>
<script src="https://code.jquery.com/jquery-1.12.4.min.js"
	type="text/javascript"></script>
<?php
    echo $this->headLink()->appendStylesheet("http://www.jqueryscript.net/css/jquerysctipttop.css");
    echo $this->headScript()->appendFile($this->basePath('js/digitalKeyboard.js'));
    ?>


<h2 class="text-display-1 text-center margin-bottom-none">Welcome</h2>
<h4><?php  echo $brokerName?></h4>

<img alt="company logo"
	src="<?php echo $this->customer_login_broker_logo_helper($broker->getId()) ?>"
	height="80" class="img-circle width-80">

<?php  echo $this->form()->openTag($form)?>
<div class="panel-body">
	<div class="form-group">
		
                 <?php $ele = $form->get('clientLoginField');   
                 $ele->get('phonenumber')->setAttributes(array(
                     "class"=>"form-control col-xs-12"
                 ));
                 echo $this->formlabel($ele->get('phonenumber'));
                 echo $this->formElement($ele->get('phonenumber'))?>
               
              
		<div style="font-size: 9px; color: red;">
		
								<?php echo $this->formelementerrors($ele->get('phonenumber'))?> 
							</div>
	</div>
	<div class="form-group">
		<!-- 		<div class="form-control-material"> -->
               <?php
    $ele->get("pin")->setAttributes(array(
        "class" => "pin"
    ));
    echo $this->formElement($ele->get('pin'))?>
                <?php // echo $this->formlabel($ele->get('pin'))?> 
               
		<!-- 		</div> -->
		<div style="font-size: 9px; color: red;">
		
								<?php echo $this->formelementerrors($ele->get('pin'))?> 
							</div>
	</div>
	<div class="form-group text-center">
<?php  echo $this->formrow($form->get('rememberme'), 'append')?>
</div>
	<div class="form-group text-center">
 <?php echo $this->formRow($form->get('csrf'))?>
 </div>
	<div class="form-group text-center">
 <?php echo $this->formRow($form->get('submit'))?>
 </div>

	<a
		href="<?php echo $this->url("client_forgot", array("brokerid"=>$broker->getBrokerUid()))?>"
		class="forgot-password">Forgot password?</a> <a
		href="<?php echo $this->url("client_register", array('brokerid'=>$broker->getBrokerUid()));?>"
		class="link-text-color">Register</a>
</div>

<?php  echo $this->form()->closeTag()?>

<?php
    
    echo $this->headScript()->appendFile($this->basePath('js/digitalKeyboard.js'))?>
    
 

    <?php  }else{?>
<a
	href="<?php // echo $this->url("client_login", array("brokerid"=>$broker->getBrokerUid()))?>"
	class="btn btn-default">Login</a>
<?php }?>
<script type="text/javascript">
	// Initialize the numpad
	$("#pin").numKey({
		limit:4
		})
</script>


