<?php

$customers = $this->customers;
$count = (count($customers) < 10 ? count($customers): 10);
?>
<div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>My Customers</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <div class="table-responsive">
					<table class="table table-hover">
                                    <?php
    
    if (count($customers) == 0) {
        echo "<span> No  Customer Registered </span> <a href='\customer' class='btn btn-default'>Register Customer</a>";
    } else {
        ?>
                                        <thead>
							<tr>
								<th>Customer Name</th>
								<th>Registered On</th>
								

								<th></th>
							</tr>
						</thead>
						<tbody>
                                         <?php for($i=0; $i < $count ; $i++){?>
                                            <tr>
								<th scope="row"><?php echo $customers[$i]->getName()?></th>
								<td><?php echo $this->dateFormat($customers[$i]->getCreatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, 'en_US') ?></td>
								
								

								<td>
									<a href="<?php  echo $this->url('customer/default', array('action'=>'pre-profile', 'id'=>$customers[$i]->getAccountId()));?>">View</a>
								</td>
							</tr>
                                             <?php   }}?>
                                        </tbody>
					</table>
					</div>

                  </div>
                </div>
              </div>
