<?php
$offer = $this->offer;
$count = (count($offer) < 10 ? count($offer) : 10);
?>

<div class="col-md-6 col-sm-6 col-xs-12">
	<div class="x_panel">
		<div class="x_title">
			<h2>Active Quotes</h2>
			<ul class="nav navbar-right panel_toolbox">
				<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
			</ul>
			<div class="clearfix"></div>
		</div>
		<div class="x_content">

			<div class="table-responsive">
				<div style='text-align: center;'>
					<i id='offerreminder' class='fa fa-lg'
						style='display: none; text-align: center;'><img alt=''
						src='<?php echo  $this->basePath('/processin.gif')  ?>' height=50>
						<hr></i>
				</div>
				<table class="table table-hover">
				
                                    <?php

                                    if (count($offer) == 0) {
                                        echo "<span> No  Active Offer </span>";
                                    } else {
                                        ?>
                                        <thead>
						<tr>
							<th>Active Offer</th>
							<th>Registered On</th>


							<th></th>
						</tr>
					</thead>
					<tbody>
                                         <?php for($i=0; $i < $count ; $i++){?>
                                            <tr>
							<td>
								<div class="media-body">
									<strong><?php  echo strtoupper($offer[$i]->getOfferCode())?></strong><br>
									<strong> Offer Name :</strong><?php  echo ($offer[$i]->getOfferName() != NULL ? $offer[$i]->getOfferName() : '')?><br>
									<strong>Customer Name: </strong> <?php  echo $offer[$i]->getCustomer()->getName()?> <br>

								</div>
							</td>
							<td><small>Created <?php  echo $this->dateFormat($offer[$i]->getCreatedOn(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, "en_US") ?></small></td>


							<td><?php  echo $this->offer_all_condition_button($offer[$i])?>
							
							</td>
						</tr>
						
                                             <?php   }}?>
                                        </tbody>
				</table>
			</div>

		</div>

		<a
			href="<?php  echo $this->url('offer/default', array('action'=>'view-all' ))?>"
			class="btn btn-default">View All</a>
	</div>
</div>