<?php
$invoices = $this->expiringInvoice;
//var_dump($invoices);
$currentDate = new DateTime();
$count = (count($invoices) < 10 ? count($invoices): 10);
?>

<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Expiring Invoices</h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>


				</ul>
				<div class="clearfix"></div>
			</div>
			<div class="x_content">
				<div class="table-responsive">
					<table class="table table-hover">

						<thead>
                                        <?php
    
    if (count($invoices) == 0) {
        echo "No Expiring Invoice";
    } else {
        ?>
                                            <tr>
								<th>Invoice Details</th>
								<th>Remaining Days</th>
								<th>Expiry Date</th>
								
								<th>STATUS</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
						<?php for($i=0; $i < $count ; $i++){?>
                                            <tr>
								<th scope="row"><a href="<?php  echo $this->url('invoice/default', array('action'=>'view', 'id'=>$invoices[$i]->getId()));?>"><?php echo strtoupper($invoices[$i]->getInvoiceUid())?></a><br>
								Amount : <?php echo $this->myCurrencyFormat($invoices[$i]->getAmount(), $invoices[$i]->getCurrency()->getCode())?>
								</th>
								<td style="color: red;"><strong><?php echo $currentDate->diff($invoices[$i]->getExpiryDate())->format("%a")." days Left";?></strong></td>
								<td><?php  echo $this->dateFormat($invoices[$i]->getExpiryDate(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, 'en_US') ?></td>
								
								

								<td>
									<a href="<?php  echo $this->url('invoice/default', array('action'=>'view', 'id'=>$invoices[$i]->getId()));?>">View</a>
								</td>
							</tr>
                                             <?php   }}?>
                                       
                                           

					</tbody>
					</table>
				</div>
			</div>
			<a href="<?php echo $this->url("invoice/default");?>" class="btn btn-default"> View All Invoices</a>
		</div>
	</div>