<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SMS\Module'                        => __DIR__ . '/Module.php',
    'SMS\Controller\IndexController' => __DIR__ . '/src/SMS/Controller/IndexController.php',
    'SMSTest\Framework\TestCase'        => __DIR__ . '/tests/SMS/Framework/TestCase.php',
    'SMSTest\SampleTest'                => __DIR__ . '/tests/SMS/SampleTest.php',
);
