<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Messages\Module'                        => __DIR__ . '/Module.php',
    'Messages\Controller\MessagesController' => __DIR__ . '/src/Messages/Controller/MessagesController.php',
    'MessagesTest\Framework\TestCase'        => __DIR__ . '/tests/Messages/Framework/TestCase.php',
    'MessagesTest\SampleTest'                => __DIR__ . '/tests/Messages/SampleTest.php',
);
