<?php
?>

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<title></title>

</head>
<body
	style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #282828; font-family: 'Helvetica Neue', Helvetica, Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px; line-height: 1.5; margin: 0; min-width: 100%; padding: 0; width: 100% !important;"
	bgcolor="#FBFBFA">
	<style type="text/css">
body {
	width: 100% !important;
	min-width: 100%;
	background-color: #FBFBFA;
	margin: 0;
	padding: 0;
	font-family: "Helvetica Neue", Helvetica, Arial, "Liberation Sans",
		FreeSans, sans-serif;
	font-size: 14px;
	line-height: 1.5;
	color: #282828;
	-webkit-text-size-adjust: 100%;
	-ms-text-size-adjust: 100%;
}

img {
	border: 0;
	-ms-interpolation-mode: bicubic;
	outline: none;
}

.link-blue:hover svg {
	fill: currentColor !important;
}

.link-blue:hover {
	color: #003BFF;
}

.link-green:hover svg {
	fill: currentColor !important;
}

.link-green:hover {
	color: #282828;
}

.link-navy:hover svg {
	fill: currentColor !important;
}

.link-navy:hover {
	color: #007460;
}

.link-soft-black:hover {
	color: #037362;
	fill: #037362;
	text-decoration: underline;
}

.link-dark-grey-500:hover {
	color: #009E74;
	text-decoration: underline;
}

.link-ksr-green-700:hover {
	color: #282828;
	text-decoration: underline;
}

@media all and (max-width: 540px) {
	.img-responsive {
		height: auto !important;
		max-width: 100%;
		width: 100% !important;
	}
	table[class*="container"] {
		width: 320px !important;
	}
	.sm-col-1 {
		width: 3.66667% !important;
	}
	.sm-col-2 {
		width: 7.83333% !important;
	}
	.sm-col-3 {
		width: 12% !important;
	}
	.sm-col-4 {
		width: 16.16667% !important;
	}
	.sm-col-5 {
		width: 20.33333% !important;
	}
	.sm-col-6 {
		width: 24.5% !important;
	}
	.sm-col-7 {
		width: 28.66667% !important;
	}
	.sm-col-8 {
		width: 32.83333% !important;
	}
	.sm-col-9 {
		width: 37% !important;
	}
	.sm-col-10 {
		width: 41.16667% !important;
	}
	.sm-col-11 {
		width: 45.33333% !important;
	}
	.sm-col-12 {
		width: 49.5% !important;
	}
	.sm-col-13 {
		width: 53.66667% !important;
	}
	.sm-col-14 {
		width: 57.83333% !important;
	}
	.sm-col-15 {
		width: 62% !important;
	}
	.sm-col-16 {
		width: 66.16667% !important;
	}
	.sm-col-17 {
		width: 70.33333% !important;
	}
	.sm-col-18 {
		width: 74.5% !important;
	}
	.sm-col-19 {
		width: 78.66667% !important;
	}
	.sm-col-20 {
		width: 82.83333% !important;
	}
	.sm-col-21 {
		width: 87% !important;
	}
	.sm-col-22 {
		width: 91.16667% !important;
	}
	.sm-col-23 {
		width: 95.33333% !important;
	}
	.sm-col-0 {
		width: 0px !important;
	}
	.sm-col-24 {
		width: 100% !important;
	}
	.hide-sm {
		display: none !important;
	}
}
</style>
	<table class="mailer-body"
		style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; border-collapse: collapse; border-spacing: 0; color: #282828; font-family: 'Helvetica Neue', Helvetica, Arial, 'Liberation Sans', FreeSans, sans-serif; font-size: 14px; line-height: 1.5; margin: 0; min-width: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 0; width: 100% !important;"
		bgcolor="#FBFBFA" width="100%" height="auto" cellpadding="0"
		cellspacing="0">
		<tbody>
			<tr>
				<td>
					<center>
						<table align="center" class="mx-auto container"
							style="border-collapse: collapse; border-spacing: 0; margin-left: auto; margin-right: auto; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 540px;"
							width="540px" height="auto" cellpadding="0" cellspacing="0">
							<tbody>
								<tr>
									<td>

										<table class="hide-sm"
											style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											width="100%" height="auto" cellpadding="0" cellspacing="0">
											<tbody>
												<tr>
													<td class="type-0 hide-sm"
														style="font-size: 0px; line-height: 0px; min-width: 540px;">
														<img height="1"
														style="-ms-interpolation-mode: bicubic; border: 0; height: 1px; min-width: 540px; outline: none;"
														src="https://d3mlfyygrfdi2i.cloudfront.net/36ab/utility-spacer.png"
														alt="Utility spacer">
													</td>
												</tr>
											</tbody>
										</table>
										<table
											style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											width="100%" height="auto" cellpadding="0" cellspacing="0">
											<tbody>
												<tr>
													<td class="text-center py5"
														style="padding-bottom: 30px; padding-top: 30px;"
														align="center"><a target="_blank"
														href="https://www.kickstarter.com/?ref=email"
														style="color: inherit; text-decoration: none;"><img
															alt="Kickstarter" width="124"
															style="-ms-interpolation-mode: bicubic; border: 0; display: block; outline: none; text-decoration: none; width: 124px;"
															class="block"
															src="https://d3mlfyygrfdi2i.cloudfront.net/kickstarter-logo-color.png">
													</a></td>
												</tr>
											</tbody>
										</table>
										<table
											class="bg-white w100p border border-grey-500 border-regular"
											style="border: 1px solid #dcdedd; border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"
											bgcolor="#FFFFFF" width="100%" height="auto" cellpadding="0"
											cellspacing="0">
											<tbody>
												<tr>
													<td class="text-center pt5" style="padding-top: 30px;"
														align="center">
														<div class="type-24 mt2 black"
															style="color: #000000; font-size: 24px; line-height: 30px; margin-top: 12px;">
															You're backer 15.</div>
													</td>
												</tr>
												<tr>
													<td>
														<table align="center" class="col-16 sm-col-20 mx-auto"
															style="border-collapse: collapse; border-spacing: 0; margin-left: auto; margin-right: auto; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 66.16667%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="type-14 text-center pt2 pb5 soft-black"
																		style="color: #282828; font-size: 14px; line-height: 21px; padding-bottom: 30px; padding-top: 12px;"
																		align="center">You have successfully pledged <span
																		class="bold navy-700"
																		style="color: #282828; font-weight: 700;">$350.00</span>
																		to <a class="bold navy-700"
																		href="https://www.kickstarter.com/projects/390812913/stool-no1?ref=email"
																		style="color: #282828; font-weight: 700; text-decoration: none;"
																		target="_blank">Stool Nº1</a>. This project is now one
																		step closer to becoming a reality.
																	</td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
												<tr>
													<td>
														<table align="center" class="col-24 border-top mx-auto"
															style="border-collapse: collapse; border-spacing: 0; border-top-color: #DCDEDD; border-top-style: solid; border-top-width: 1px; margin-left: auto; margin-right: auto; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 100%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td
																		class="col-20 sm-col-20 type-14 text-center pt4 pb4"
																		style="font-size: 14px; line-height: 21px; padding-bottom: 24px; padding-top: 24px; width: 82.83333%;"
																		align="center">Confirmation number: <span
																		class="bold navy-700"
																		style="color: #282828; font-weight: 700;">65000RGE5006500</span>
																	</td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
											</tbody>
										</table>

										<table class="h2"
											style="border-collapse: collapse; border-spacing: 0; height: 12px; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											width="100%" height="auto" cellpadding="0" cellspacing="0">
											<tbody>
												<tr>
													<td class="h2 type-0"
														style="font-size: 0px; height: 12px; line-height: 0px;"><img
														height="12"
														style="-ms-interpolation-mode: bicubic; border: 0; height: 12px; outline: none;"
														src="https://d3mlfyygrfdi2i.cloudfront.net/36ab/utility-spacer.png"
														alt="Utility spacer"></td>
												</tr>
											</tbody>
										</table>
										<table
											class="bg-white w100p border border-grey-500 border-regular"
											style="border: 1px solid #dcdedd; border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"
											bgcolor="#FFFFFF" width="100%" height="auto" cellpadding="0"
											cellspacing="0">
											<tbody>
												<tr>
													<td class="pr1 pb1 pl1 pt2" style="padding: 12px 6px 6px;">
														<table align="left" class="col-8 sm-col-24"
															style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 32.83333%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="pr2 pb2 pl2 pt1"
																		style="padding: 6px 12px 12px;"><a
																		href="https://www.kickstarter.com/projects/390812913/stool-no1?ref=email"
																		style="color: inherit; text-decoration: none;"
																		target="_blank"><img alt="Stool Nº1"
																			style="-ms-interpolation-mode: bicubic; border: 0; display: block; outline: none; text-decoration: none; width: 148px;"
																			class="block img-responsive"
																			src="https://ksr-ugc.imgix.net/assets/021/692/559/be7be463e981716a74daaae6727ccce8_original.jpg?crop=faces&amp;w=576&amp;h=324&amp;fit=crop&amp;v=1532839788&amp;auto=format&amp;q=92&amp;s=1bd325286bbd543788299d3db23f238b"
																			width="148" height="83"></a></td>
																</tr>
															</tbody>
														</table>
														<table align="left" class="col-16 sm-col-24"
															style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 66.16667%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="pr2 pb2 pl2 pt1"
																		style="padding: 6px 12px 12px;">
																		<div class="type-16 black"
																			style="color: #000000; font-size: 16px; line-height: 24px;">
																			<a class="navy-700"
																				href="https://www.kickstarter.com/projects/390812913/stool-no1?ref=email"
																				style="color: #282828; text-decoration: none;"
																				target="_blank">Stool Nº1</a>
																		</div>
																		<div class="type-12 soft-black"
																			style="color: #282828; font-size: 12px; line-height: 18px;">
																			by Craighton Berman</div>
																		<div class="mt3" style="margin-top: 18px;">
																			<div
																				class="bg-navy-300 h1_2 w100p rounded-bold block"
																				style="background: #EFEFF3; display: block; height: 3px; width: 100%;">
																				<div
																					class="bg-ksr-green-700 h1_2 block rounded-bold"
																					style="background: #037362; display: block; height: 3px; width: 36.21%;"></div>
																			</div>
																		</div>
																		<div class="mt1" style="margin-top: 6px;">
																			<table
																				style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
																				width="100%" height="auto" cellpadding="0"
																				cellspacing="0">
																				<tbody>
																					<tr>
																						<td class="pr3 ksr-green-700 type-12 text-nowrap"
																							style="color: #037362; font-size: 12px; line-height: 18px; padding-right: 18px; white-space: nowrap;">
																							<span class="ksr-green-700"
																							style="color: #037362;"> 36% </span> <span
																							class="dark-grey-500" style="color: #656969;">
																								funded </span>
																						</td>
																						<td class="pr3 type-12 text-nowrap dark-grey-500"
																							style="color: #656969; font-size: 12px; line-height: 18px; padding-right: 18px; white-space: nowrap;">
																							22 days left</td>
																						<td class="pr3 type-12 text-nowrap dark-grey-500"
																							style="color: #656969; font-size: 12px; line-height: 18px; padding-right: 18px; white-space: nowrap;">
																							28 backers</td>
																						<td class="w100p" style="width: 100%;">&nbsp;</td>
																					</tr>
																				</tbody>
																			</table>
																		</div>
																	</td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
											</tbody>
										</table>
										<table
											class="bg-white w100p border-bottom border-right border-left border-grey-500 border-regular"
											style="border-bottom-color: #DCDEDD; border-bottom-style: solid; border-bottom-width: 1px; border-collapse: collapse; border-left-color: #DCDEDD; border-left-style: solid; border-left-width: 1px; border-right-color: #DCDEDD; border-right-style: solid; border-right-width: 1px; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"
											bgcolor="#FFFFFF" width="100%" height="auto" cellpadding="0"
											cellspacing="0">
											<tbody>
												<tr>
													<td>
														<table align="left" class="col-12 sm-col-12"
															style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 49.5%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td
																		class="text-center border-right border-regular py2 type-14 bold black"
																		style="border-right-color: #DCDEDD; border-right-style: solid; border-right-width: 1px; color: #000000; font-size: 14px; font-weight: 700; line-height: 21px; padding-bottom: 12px; padding-top: 12px;"
																		align="center"><a class="navy-700"
																		href="https://m.facebook.com/login.php?skip_api_login=1&amp;api_key=966242223397117&amp;signed_next=1&amp;next=https%3A%2F%2Fm.facebook.com%2Fshare.php%3Ft%3DKickstarter%2B-%2BStool%2BN%25C2%25BA1%26u%3Dhttps%253A%252F%252Fwww.kickstarter.com%252Fprojects%252F390812913%252Fstool-no1%253Fref%253Dthanks_email_share%26v%3D4&amp;cancel_url=https%3A%2F%2Fm.facebook.com%2Fdialog%2Fclose_window%2F%3Fapp_id%3D966242223397117%26connect%3D0%23_%3D_&amp;display=touch&amp;locale=en_US&amp;_rdr"
																		style="color: #282828; text-decoration: none;"
																		target="_blank"><img
																			style="-ms-interpolation-mode: bicubic; border: 0; height: 12px; outline: none; text-decoration: none; vertical-align: -5%; width: 12px;"
																			height="12" width="12"
																			src="https://d3mlfyygrfdi2i.cloudfront.net/7b05/facebook-h2-navy-700@4x.png"
																			alt="Facebook h2 navy 700@4x"> Share </a></td>
																</tr>
															</tbody>
														</table>
														<table align="left" class="col-12 sm-col-12"
															style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 49.5%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="text-center py2 type-14 bold black"
																		style="color: #000000; font-size: 14px; font-weight: 700; line-height: 21px; padding-bottom: 12px; padding-top: 12px;"
																		align="center"><a class="navy-700"
																		href="https://twitter.com/intent/tweet?text=I%20just%20backed%20Stool+N%C2%BA1%20on%20@Kickstarter%20http%3A%2F%2Fkck.st%2F2Mih95a"
																		style="color: #282828; text-decoration: none;"
																		target="_blank"><img
																			style="-ms-interpolation-mode: bicubic; border: 0; height: 12px; outline: none; text-decoration: none; vertical-align: -5%; width: 15px;"
																			height="12" width="15"
																			src="https://d3mlfyygrfdi2i.cloudfront.net/188a/twitter-h2-navy-700@4x.png"
																			alt="Twitter h2 navy 700@4x"> Tweet </a></td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
											</tbody>
										</table>
										<table class="h2"
											style="border-collapse: collapse; border-spacing: 0; height: 12px; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											width="100%" height="auto" cellpadding="0" cellspacing="0">
											<tbody>
												<tr>
													<td class="h2 type-0"
														style="font-size: 0px; height: 12px; line-height: 0px;"><img
														height="12"
														style="-ms-interpolation-mode: bicubic; border: 0; height: 12px; outline: none;"
														src="https://d3mlfyygrfdi2i.cloudfront.net/36ab/utility-spacer.png"
														alt="Utility spacer"></td>
												</tr>
											</tbody>
										</table>
										<table
											class="bg-white w100p border border-grey-500 border-regular"
											style="border: 1px solid #dcdedd; border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"
											bgcolor="#FFFFFF" width="100%" height="auto" cellpadding="0"
											cellspacing="0">
											<tbody>
												<tr>
													<td>
														<table align="center" class="col-20 sm-col-20 mx-auto"
															style="border-collapse: collapse; border-spacing: 0; margin-left: auto; margin-right: auto; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 82.83333%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="type-24 py4 black"
																		style="color: #000000; font-size: 24px; line-height: 30px; padding-bottom: 24px; padding-top: 24px;">
																		Pledge details <span
																		class="type-12 ksr-green-700 normal"
																		style="color: #037362; font-size: 12px; font-weight: 400; line-height: 18px;">
																			<a class="ksr-green-700" href="#"
																			style="color: #037362; text-decoration: none;"
																			target="_blank">Manage</a>
																	</span>
																	</td>
																</tr>
																<tr>
																	<td class="border-top py4 border-regular"
																		style="border-top-color: #DCDEDD; border-top-style: solid; border-top-width: 1px; padding-bottom: 24px; padding-top: 24px;">
																		<table align="left" class="col-10 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 41.16667%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td class="type-12 soft-black"
																						style="color: #282828; font-size: 12px; line-height: 18px;">
																						Backer name</td>
																				</tr>
																			</tbody>
																		</table>
																		<table align="left" class="col-14 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 57.83333%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td class="type-18"
																						style="font-size: 18px; line-height: 30px;">
																						Smiles Davis</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
																<tr>
																	<td class="border-top py4 border-regular"
																		style="border-top-color: #DCDEDD; border-top-style: solid; border-top-width: 1px; padding-bottom: 24px; padding-top: 24px;">
																		<table align="left" class="col-10 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 41.16667%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td class="type-12 soft-black"
																						style="color: #282828; font-size: 12px; line-height: 18px;">
																						Amount pledged</td>
																				</tr>
																			</tbody>
																		</table>
																		<table align="left" class="col-14 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 57.83333%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td>
																						<div class="type-18"
																							style="font-size: 18px; line-height: 30px;">
																							$350.00</div>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
																<tr>
																	<td class="border-regular border-top pt4 py4"
																		style="border-top-color: #DCDEDD; border-top-style: solid; border-top-width: 1px; padding-bottom: 24px; padding-top: 24px;">
																		<table align="left" class="col-10 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 41.16667%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td class="type-12 soft-black"
																						style="color: #282828; font-size: 12px; line-height: 18px;">
																						Reward</td>
																				</tr>
																			</tbody>
																		</table>
																		<table align="left" class="col-14 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 57.83333%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td>
																						<div class="type-18"
																							style="font-size: 18px; line-height: 30px;">
																							EARLYBIRD — Shipped</div>
																						<div class="type-14 soft-black mt1"
																							style="color: #282828; font-size: 14px; line-height: 21px; margin-top: 6px;">
																							<p>• Single stool, shipped</p>

																							<p>• Multiply your pledge by the number you would
																								like. (ie 2 stools = $350, 4 stools = $700).</p>

																							<p>• Options such as height and finishes will be
																								selected during the survey after the campaign.</p>
																						</div>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
																<tr>
																	<td class="pb4" style="padding-bottom: 24px;">
																		<table align="left" class="col-9 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 37%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td class="type-12 dark-grey-500"
																						style="color: #656969; font-size: 12px; line-height: 18px;">
																						&nbsp;</td>
																				</tr>
																			</tbody>
																		</table>
																		<table align="left" class="col-15 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 62%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td>
																						<table
																							style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
																							width="100%" height="auto" cellpadding="0"
																							cellspacing="0">
																							<tbody>
																								<tr>
																									<td
																										class="col-2 text-nowrap soft-black valign-top"
																										valign="top"
																										style="color: #282828; white-space: nowrap; width: 7.83333%;">
																										&nbsp;</td>
																									<td
																										class="w100p type-12 mt2 bold dark-grey-500 valign-top"
																										valign="top"
																										style="color: #656969; font-size: 12px; font-weight: 700; line-height: 18px; margin-top: 12px; width: 100%;">
																										INCLUDES</td>
																								</tr>
																								<tr>
																									<td
																										class="col-2 text-nowrap soft-black valign-top"
																										valign="top"
																										style="color: #282828; white-space: nowrap; width: 7.83333%;">
																										•</td>
																									<td class="w100p type-14 soft-black valign-top"
																										valign="top"
																										style="color: #282828; font-size: 14px; line-height: 21px; width: 100%;">
																										Stool Nº1</td>
																								</tr>
																								<tr>
																									<td
																										class="col-2 text-nowrap soft-black valign-top"
																										valign="top"
																										style="color: #282828; white-space: nowrap; width: 7.83333%;">
																										•</td>
																									<td class="w100p type-14 soft-black valign-top"
																										valign="top"
																										style="color: #282828; font-size: 14px; line-height: 21px; width: 100%;">
																										Process Zine</td>
																								</tr>
																							</tbody>
																						</table>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
																<tr>
																	<td class="border-top py4 border-regular"
																		style="border-top-color: #DCDEDD; border-top-style: solid; border-top-width: 1px; padding-bottom: 24px; padding-top: 24px;">
																		<table align="left" class="col-10 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 41.16667%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td class="type-12 soft-black"
																						style="color: #282828; font-size: 12px; line-height: 18px;">
																						Estimated delivery</td>
																				</tr>
																			</tbody>
																		</table>
																		<table align="left" class="col-14 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 57.83333%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td class="type-18"
																						style="font-size: 18px; line-height: 30px;"><time
																							datetime="2018-11-01" data-format="MMM YYYY"
																							class="invisible-if-js js-adjust-time">Nov 2018</time>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
											</tbody>
										</table>

										<table class="h2"
											style="border-collapse: collapse; border-spacing: 0; height: 12px; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											width="100%" height="auto" cellpadding="0" cellspacing="0">
											<tbody>
												<tr>
													<td class="h2 type-0"
														style="font-size: 0px; height: 12px; line-height: 0px;"><img
														height="12"
														style="-ms-interpolation-mode: bicubic; border: 0; height: 12px; outline: none;"
														src="https://d3mlfyygrfdi2i.cloudfront.net/36ab/utility-spacer.png"
														alt="Utility spacer"></td>
												</tr>
											</tbody>
										</table>
										<table
											class="bg-white w100p border border-grey-500 border-regular"
											style="border: 1px solid #dcdedd; border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;"
											bgcolor="#FFFFFF" width="100%" height="auto" cellpadding="0"
											cellspacing="0">
											<tbody>
												<tr>
													<td>
														<table align="center" class="col-20 sm-col-20 mx-auto"
															style="border-collapse: collapse; border-spacing: 0; margin-left: auto; margin-right: auto; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 82.83333%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="pb5 pt2"
																		style="padding-bottom: 30px; padding-top: 12px;">
																		<table align="left" class="col-9 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 37%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td class="type-12 soft-black pt3"
																						style="color: #282828; font-size: 12px; line-height: 18px; padding-top: 18px;">
																						What’s next?</td>
																				</tr>
																			</tbody>
																		</table>
																		<table align="left" class="col-15 sm-col-24"
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 62%;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td>
																						<table
																							style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
																							width="100%" height="auto" cellpadding="0"
																							cellspacing="0">
																							<tbody>
																								<tr>
																									<td
																										class="col-2 pt3 text-nowrap soft-black valign-top"
																										valign="top"
																										style="color: #282828; padding-top: 18px; white-space: nowrap; width: 7.83333%;">
																										•</td>
																									<td
																										class="w100p pt3 type-14 soft-black valign-top"
																										valign="top"
																										style="color: #282828; font-size: 14px; line-height: 21px; padding-top: 18px; width: 100%;">
																										If this project is successfully funded, your
																										card will be charged <span
																										class="bold navy-700"
																										style="color: #282828; font-weight: 700;">$350.00</span>
																										on <span class="bold navy-700"
																										style="color: #282828; font-weight: 700;">September
																											1, 2018 at 12:00 am</span>.
																									</td>
																								</tr>
																								<tr>
																									<td
																										class="col-2 pt2 text-nowrap soft-black valign-top"
																										valign="top"
																										style="color: #282828; padding-top: 12px; white-space: nowrap; width: 7.83333%;">
																										•</td>
																									<td
																										class="w100p pt2 type-14 soft-black valign-top"
																										valign="top"
																										style="color: #282828; font-size: 14px; line-height: 21px; padding-top: 12px; width: 100%;">
																										Keep checking your inbox. The creator will
																										send project updates periodically.</td>
																								</tr>
																								<tr>
																									<td
																										class="col-2 pt2 text-nowrap soft-black valign-top"
																										valign="top"
																										style="color: #282828; padding-top: 12px; white-space: nowrap; width: 7.83333%;">
																										•</td>
																									<td
																										class="w100p pt2 type-14 soft-black valign-top"
																										valign="top"
																										style="color: #282828; font-size: 14px; line-height: 21px; padding-top: 12px; width: 100%;">
																										<a class="text-underline soft-black"
																										href="https://www.kickstarter.com/"
																										style="color: #282828; text-decoration: underline;"
																										target="_blank">Send a message</a> to the
																										creator if you have any questions about the
																										project.
																									</td>
																								</tr>
																								<tr>
																									<td
																										class="col-2 pt2 text-nowrap soft-black valign-top"
																										valign="top"
																										style="color: #282828; padding-top: 12px; white-space: nowrap; width: 7.83333%;">
																										•</td>
																									<td
																										class="w100p pt2 type-14 soft-black valign-top"
																										valign="top"
																										style="color: #282828; font-size: 14px; line-height: 21px; padding-top: 12px; width: 100%;">
																										When the reward you’ve chosen is ready for
																										delivery, the creator will reach out to get
																										your mailing address and other details if
																										necessary.</td>
																								</tr>
																							</tbody>
																						</table>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
											</tbody>
										</table>
										<table
											style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											width="100%" height="auto" cellpadding="0" cellspacing="0">
											<tbody>
												<tr>
													<td class="text-center py5 type-14"
														style="font-size: 14px; line-height: 21px; padding-bottom: 30px; padding-top: 30px;"
														align="center">You’ll love these projects, too:</td>
												</tr>
											</tbody>
										</table>
										<table
											style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											width="100%" height="auto" cellpadding="0" cellspacing="0">
											<tbody>
												<tr>
													<td>
														<table align="left" class="col-12 sm-col-24"
															style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 49.5%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="p1" style="padding: 6px;">
																		<table
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td
																						class="bg-white w100p border border-grey-500 border-regular rounded-medium"
																						style="border: 1px solid #dcdedd; border-radius: 4px !important; width: 100%;"
																						bgcolor="#FFFFFF">
																						<table
																							style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
																							width="100%" height="auto" cellpadding="0"
																							cellspacing="0">
																							<tbody>
																								<tr>
																									<td><a
																										href="https://www.kickstarter.com/projects/1573076370/okewa-rainwear-meets-recycled-plastic-bottles?ref=email_backerconfirm_rec1"
																										style="color: inherit; text-decoration: none;"
																										target="_blank"><img alt="Project image"
																											style="-ms-interpolation-mode: bicubic; border: 0; border-top-left-radius: 2px; border-top-right-radius: 2px; display: block; outline: none; text-decoration: none; width: 253px;"
																											class="w100p rounded-top-left rounded-top-right block img-responsive"
																											src="https://ksr-ugc.imgix.net/assets/021/032/502/eba5b58fce793bbb16af618d8cf29c5b_original.jpg?crop=faces&amp;w=624&amp;h=351&amp;fit=crop&amp;v=1533441317&amp;auto=format&amp;q=92&amp;s=0e5bde62f12ede114b7321d494242ad3"
																											width="253" height="142"> </a></td>
																								</tr>
																								<tr>
																									<td class="pt2 px2 type-12 soft-black"
																										style="color: #282828; font-size: 12px; line-height: 18px; padding-left: 12px; padding-right: 12px; padding-top: 12px;">
																										by <span class="navy-700"
																										style="color: #282828;">Okewa Rainwear</span>
																									</td>
																								</tr>
																								<tr>
																									<td class="type-16 navy-700 pt1 px2"
																										style="color: #282828; font-size: 16px; line-height: 24px; padding-left: 12px; padding-right: 12px; padding-top: 6px;">
																										<a
																										href="https://www.kickstarter.com/projects/1573076370/okewa-rainwear-meets-recycled-plastic-bottles?ref=email_backerconfirm_rec1"
																										style="color: inherit; text-decoration: none;"
																										target="_blank">OKEWA — Rainwear Meets
																											Recycled Plastic Bottles: <span
																											class="soft-black" style="color: #282828;">
																												Waterproof, seam-sealed raincoats from
																												Wellington, New Zealand t... </span>
																									</a>
																									</td>
																								</tr>
																								<tr>
																									<td class="pt1 px2 pb2"
																										style="padding: 6px 12px 12px;">
																										<table
																											style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
																											width="100%" height="auto" cellpadding="0"
																											cellspacing="0">
																											<tbody>
																												<tr>
																													<td
																														class="ksr-green-700 text-nowrap type-12 pr1"
																														style="color: #037362; font-size: 12px; line-height: 18px; padding-right: 6px; white-space: nowrap;">
																														92% funded</td>
																													<td
																														class="dark-grey-500 text-nowrap type-12"
																														style="color: #656969; font-size: 12px; line-height: 18px; white-space: nowrap;">
																														Ending August 14</td>
																													<td class="w100p" style="width: 100%;">
																														&nbsp;</td>
																												</tr>
																											</tbody>
																										</table>
																									</td>
																								</tr>
																							</tbody>
																						</table>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
															</tbody>
														</table>
														<table align="right" class="col-12 sm-col-24"
															style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 49.5%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="p1" style="padding: 6px;">
																		<table
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td
																						class="bg-white w100p border border-grey-500 border-regular rounded-medium"
																						style="border: 1px solid #dcdedd; border-radius: 4px !important; width: 100%;"
																						bgcolor="#FFFFFF">
																						<table
																							style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
																							width="100%" height="auto" cellpadding="0"
																							cellspacing="0">
																							<tbody>
																								<tr>
																									<td><a
																										href="https://www.kickstarter.com/projects/92481206/home-of-the-brave-starting-the-conversation-on-con?ref=email_backerconfirm_rec2"
																										style="color: inherit; text-decoration: none;"
																										target="_blank"><img alt="Project image"
																											style="-ms-interpolation-mode: bicubic; border: 0; border-top-left-radius: 2px; border-top-right-radius: 2px; display: block; outline: none; text-decoration: none; width: 253px;"
																											class="w100p rounded-top-left rounded-top-right block img-responsive"
																											src="https://ksr-ugc.imgix.net/assets/021/657/138/e4e452fe81430abfceccfea87a42a629_original.png?crop=faces&amp;w=624&amp;h=351&amp;fit=crop&amp;v=1532134115&amp;auto=format&amp;q=92&amp;s=0c6e84c29479e4ce88edd3af917b9839"
																											width="253" height="142"> </a></td>
																								</tr>
																								<tr>
																									<td class="pt2 px2 type-12 soft-black"
																										style="color: #282828; font-size: 12px; line-height: 18px; padding-left: 12px; padding-right: 12px; padding-top: 12px;">
																										by <span class="navy-700"
																										style="color: #282828;">Chelsie and Connyre
																											Corbett</span>
																									</td>
																								</tr>
																								<tr>
																									<td class="type-16 navy-700 pt1 px2"
																										style="color: #282828; font-size: 16px; line-height: 24px; padding-left: 12px; padding-right: 12px; padding-top: 6px;">
																										<a
																										href="https://www.kickstarter.com/projects/92481206/home-of-the-brave-starting-the-conversation-on-con?ref=email_backerconfirm_rec2"
																										style="color: inherit; text-decoration: none;"
																										target="_blank">Home of the Brave; Starting
																											the Conversation on Conversation: <span
																											class="soft-black" style="color: #282828;">
																												America feels broken, so we're traveling the
																												countr... </span>
																									</a>
																									</td>
																								</tr>
																								<tr>
																									<td class="pt1 px2 pb2"
																										style="padding: 6px 12px 12px;">
																										<table
																											style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
																											width="100%" height="auto" cellpadding="0"
																											cellspacing="0">
																											<tbody>
																												<tr>
																													<td
																														class="ksr-green-700 text-nowrap type-12 pr1"
																														style="color: #037362; font-size: 12px; line-height: 18px; padding-right: 6px; white-space: nowrap;">
																														28% funded</td>
																													<td
																														class="dark-grey-500 text-nowrap type-12"
																														style="color: #656969; font-size: 12px; line-height: 18px; white-space: nowrap;">
																														Ending August 24</td>
																													<td class="w100p" style="width: 100%;">
																														&nbsp;</td>
																												</tr>
																											</tbody>
																										</table>
																									</td>
																								</tr>
																							</tbody>
																						</table>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
															</tbody>
														</table>
														<table
															style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td
																		class="px1 pt4 pb8 border-bottom border-grey-500 border-regular"
																		style="border-bottom-color: #DCDEDD; border-bottom-style: solid; border-bottom-width: 1px; padding: 24px 6px 48px;">
																		<table
																			style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
																			width="100%" height="auto" cellpadding="0"
																			cellspacing="0">
																			<tbody>
																				<tr>
																					<td
																						class="rounded-medium bg-grey-500 soft-black p2 text-center type-14"
																						style="border-radius: 4px !important; color: #282828; font-size: 14px; line-height: 21px; padding: 12px;"
																						align="center" bgcolor="#DCDEDD"><a
																						class="soft-black"
																						href="https://www.kickstarter.com/discover/recommended?ref=email_backerconfirm"
																						style="color: #282828; text-decoration: none;"
																						target="_blank">Explore more recommended projects</a>
																					</td>
																				</tr>
																			</tbody>
																		</table>
																	</td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
											</tbody>
										</table>

										<table
											style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
											width="100%" height="auto" cellpadding="0" cellspacing="0">
											<tbody>
												<tr>
													<td class="pt8 pb12"
														style="padding-bottom: 72px; padding-top: 48px;">
														<table align="center" class="col-7 sm-col-14 mx-auto"
															style="border-collapse: collapse; border-spacing: 0; margin-left: auto; margin-right: auto; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 28.66667%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="text-center valign-middle" style=""
																		align="center" valign="middle"><a
																		href="https://www.instagram.com/Kickstarter/"
																		style="color: inherit; text-decoration: none;"
																		target="_blank"><img alt="Instagram" height="24"
																			width="24"
																			style="-ms-interpolation-mode: bicubic; border: 0; display: block; height: 24px; outline: none; text-decoration: none; width: 24px;"
																			class="block"
																			src="https://d3mlfyygrfdi2i.cloudfront.net/social-icon-ig_%281%29.png">
																	</a></td>
																	<td class="text-center valign-middle" style=""
																		align="center" valign="middle"><a
																		href="https://www.facebook.com/Kickstarter"
																		style="color: inherit; text-decoration: none;"
																		target="_blank"><img alt="Facebook" height="24"
																			width="24"
																			style="-ms-interpolation-mode: bicubic; border: 0; display: block; height: 24px; outline: none; text-decoration: none; width: 24px;"
																			class="block"
																			src="https://d3mlfyygrfdi2i.cloudfront.net/social-icon-fb.png">
																	</a></td>
																	<td class="text-center valign-middle" style=""
																		align="center" valign="middle"><a
																		href="https://twitter.com/Kickstarter"
																		style="color: inherit; text-decoration: none;"
																		target="_blank"><img alt="Twitter" width="24"
																			style="-ms-interpolation-mode: bicubic; border: 0; display: block; outline: none; text-decoration: none; width: 24px;"
																			class="block"
																			src="https://d3mlfyygrfdi2i.cloudfront.net/social-icon-tw.png">
																	</a></td>
																</tr>
															</tbody>
														</table>
														<table
															style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="text-center pt4 type-12 soft-black"
																		style="color: #282828; font-size: 12px; line-height: 18px; padding-top: 24px;"
																		align="center">Kickstarter · 58 Kent St, Brooklyn NY
																		11222</td>
																</tr>
															</tbody>
														</table>
														<table align="left" class="col-12 sm-col-12"
															style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 49.5%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="text-right type-12 soft-black px1"
																		style="color: #282828; font-size: 12px; line-height: 18px; padding-left: 6px; padding-right: 6px;"
																		align="right"><a class="soft-black text-underline"
																		href="https://help.kickstarter.com/hc/en-us/requests/new"
																		style="color: #282828; text-decoration: underline;"
																		target="_blank">Contact Us</a></td>
																</tr>
															</tbody>
														</table>
														<table align="left" class="col-12 sm-col-12"
															style="border-collapse: collapse; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; table-layout: fixed; width: 49.5%;"
															width="100%" height="auto" cellpadding="0"
															cellspacing="0">
															<tbody>
																<tr>
																	<td class="text-left type-12 soft-black px1"
																		style="color: #282828; font-size: 12px; line-height: 18px; padding-left: 6px; padding-right: 6px;"
																		align="left"><a class="soft-black text-underline"
																		href="https://www.kickstarter.com/jobs?ref=email"
																		style="color: #282828; text-decoration: underline;"
																		target="_blank">We're Hiring</a></td>
																</tr>
															</tbody>
														</table>
													</td>
												</tr>
											</tbody>
										</table>
									</td>
								</tr>
							</tbody>
						</table>
					</center>
				</td>
			</tr>
		</tbody>
	</table>





</body>