<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Authorization\Module' => __DIR__ . '/Module.php',
    'Authorization\Controller\IndexController' => __DIR__ . '/src/Authorization/Controller/IndexController.php',
    'AuthorizationTest\Framework\TestCase' => __DIR__ . '/tests/Authorization/Framework/TestCase.php',
    'AuthorizationTest\SampleTest' => __DIR__ . '/tests/Authorization/SampleTest.php'
);
